### ISSUE TITLE
Gui Controls doesn't work

### ISSUE THREAD

**Issue by 3rg00** [ImagicTheCat/vRP#1]
Hello, thank's a lot for your amazing work !
I try to learn from your API, but I have a problem for using GUI menu, controls set doesn't work for atm or markets (up/down and left/right are ok, but select not work).

Do you have any idea about this issue?

Thank's a lot.

**Comment by ImagicTheCat** [comment]
Hi, 

thank you for your feedback, I haven't really released vRP yet so I didn't documented it, but the controls are based on the cellphone bindings (LEFT,UP,RIGHT,DOWN,CANCEL,SELECT). For me cancel is "return", and select is "enter".

**Comment by 3rg00** [comment]
Thanks for your answer, 
I think I found the problem, binding are correct on my side now, but the  vRP.prompt not showing when I try to deposit/withdraw.

**Comment by ImagicTheCat** [comment]
There is a minor issue where you need to press enter twice after pressing tab for a second withdraw, but if it doesn't appear in the first try, there is an error somewhere. Do you have other resources using mysql loaded ?

**Comment by 3rg00** [comment]
Nope, I don't have any other resources using mysql

**Comment by 3rg00** [comment]
I tried to reuse it from scratch, and it doesn't work.

**Comment by ImagicTheCat** [comment]
I will do some testing on different servers today to reproduce the issue.

**Comment by 3rg00** [comment]
Okay, I have same problem in alll menus (market, atm, new gunshop :)).

**Comment by 3rg00** [comment]
Wich cfx server do you have ? The latest (30.04.17) release?

**Comment by ImagicTheCat** [comment]
Same version, under windows. I will try under linux if there is a difference, meanwhile try to add a prints before line 8 (to know if the choice is triggered and if the prompt).

**Comment by 3rg00** [comment]
I tried to add print debug into atm_choice_withdraw() and atm_choice_deposit(), no results when I try to select choice ingame...

**Comment by ImagicTheCat** [comment]
Try the last update and tell me if the problem still exists, no needs to update the cfg dir.

**Comment by 3rg00** [comment]
I Tried with the last update, but now i don't have any menus/progressbar shown.

**Comment by 3rg00** [comment]
Okay I found the problem, was related with git cloning ! I downloaded and updated manually, now its work perfectly !
Thank's a lot, now I will try to commit you a few improvments :)

**Comment by ImagicTheCat** [comment]
Nice !
