### ISSUE TITLE
useless variable (refactoring)

### ISSUE THREAD

**Issue by xchopin** [ImagicTheCat/vRP#10]
In https://github.com/ImagicTheCat/vRP/blob/master/vrp/client/basic_garage.lua at line 18 : 

```
  local i = 0
    while not HasModelLoaded(mhash) and i < 10000 do
      RequestModel(mhash)
      Citizen.Wait(10)
    end
```

variable i is never edited therefore the second condition is always true it might be refactored by 

```
    while not HasModelLoaded(mhash) do
      RequestModel(mhash)
      Citizen.Wait(10)
    end
```

**Comment by ImagicTheCat** [comment]
Thanks, the variable is used to prevent infinite request loop in case of invalid model (max 100 seconds).
Fixed.

**Comment by xchopin** [comment]
Ok that's what I was thinking too
