### ISSUE TITLE
vRP.setGPS doesnot working

### ISSUE THREAD

**Issue by CrazyForge** [ImagicTheCat/vRP#100]
Helo, in the groups.lua i have add this 

```lua
local orpailleur = {}
function orpailleur.onjoin(player)
  vRPclient.notify(player,{"Welcome to your new job, orpailleur ! "})
  vRP.setGPS(474.3488, -1951.734)
end
```

the notify work but the gps no i have try the vrpclient.setgps but it does not work too

**Comment by ImagicTheCat** [comment]
Please take your time before submitting issue, vRP in in beta, wait for the topic on the FiveM forum to have help and more tutorials.
This is not a vRP issue, but just a lack of understanding of the API. 
If you can't wait for the release, read the doc about tunnel, again and again, until you understand.

**Comment by CrazyForge** [comment]
Ok, thx for your reponse speedy !

i go read the readme so

**Comment by CrazyForge** [comment]
Hi, i shearch 3 days ago and i dont find anything for my problem...

**Comment by 3rg00** [comment]
SetGPS function works perfectly, I'm currently using it for missions. In your case, you didn't use the tunnel correctly. Check the documentation and made some tests.
