### ISSUE TITLE
Retrieve client value from server part

### ISSUE THREAD

**Issue by 3rg00** [ImagicTheCat/vRP#101]
Hello @ImagicTheCat, I want to know if its possible to retrieve some value from client part to server part.
For example, I have this function in client part:
_function tvRP.simpleReturnFunc()
    local valuetoreturn = "Test"
    return valuetoreturn
end_
and I try to set a variable with this function return (valuetoreturn) in the serverside:
_local testing = vRPclient.simpleReturnFunc(source,{})
  print("testing:"..testing)_

But not value will be set.. I think I correctly understood the Tunnel Client/Server principe, Server can send to client, but client cannot send specific value to server ?

Thanks in advance.

**Comment by ImagicTheCat** [comment]
Check the tunnel example in the readme, there is exactly what you need to know, I can't be more clear.

**Comment by 3rg00** [comment]
Instead of _vRPclient.simpleReturnFunc(source,{})_ this work better:   
_vRPclient.simpleReturnFunc(source,{},function(returnedval)
    print(returnedval)
 end)_

@ImagicTheCat thanks
