### ISSUE TITLE
getUserId returning null

### ISSUE THREAD

**Issue by AsiiFR** [ImagicTheCat/vRP#102]
Hello, i have a problem with vRP and i believe it's an issue related to vRP.
https://pastebin.com/bHYE4XTW
I have several problems

- it looks like vRP.getUserId(player) is returning null

I can't get the vRP player id (in the db i mean)

**Comment by ImagicTheCat** [comment]
Check the documentation of proxy if you are in another resource, if not, check the documentation of the function. You did many mistakes in the script you paste, read the doc carefully.
Seriously, "-- return user id or nil if the source is invalid", I will start to say RTFM and close any issue of people not reading what I took the time to write, if this is the only way to get people into it.

Nothing against you, but it begins to remind me me the dark age of help sections on programming forums, and that's bad. People will not improve their skills if they ask the solution before trying.

**Comment by AsiiFR** [comment]
I'm sorry
Have a nice day sir
