### ISSUE TITLE
vRP.getUserByGroup ??

### ISSUE THREAD

**Issue by CrazyForge** [ImagicTheCat/vRP#103]
Hiiii, i have a question, i have see vRP.getUserByAddress and i would know if vRP.getUserByGroup exist.. or a equivalent ?? :)

**Comment by 3rg00** [comment]
All described here: https://github.com/ImagicTheCat/vRP#grouppermission

**Comment by ImagicTheCat** [comment]
You want a function to get all connected users inside a group ? I will add some list functions, I reopen the issue just to remember it.

**Comment by CrazyForge** [comment]
Yep i want this ^^ i make a interphone for government and i want a function for get all users in a group exactly

**Comment by ImagicTheCat** [comment]
Done.
