### ISSUE TITLE
Wanted star

### ISSUE THREAD

**Issue by MagnanQC** [ImagicTheCat/vRP#104]
Hi, 
when i was on duty, just tried to put someone in under arrest, NPC cops around the police station, shoot at me (with at least 1 wanted star and probably did something not good).

Thanks

**Comment by ImagicTheCat** [comment]
Hi,

I will look into this while adding the wanted system feature, don't close the issue.

**Comment by MagnanQC** [comment]
Perfect :)

Thanks for your work !

**Comment by ImagicTheCat** [comment]
The last update of **cfg/groups.lua** solve the issue (use setCop for the police group).

**Comment by Aleweadan** [comment]
Thanks but now you can still have a wanted level if you are a cop. Maybe you can add a script like that for cops :

Citizen.CreateThread(function()
    while true do
        Citizen.Wait(0)
        if GetPlayerWantedLevel(PlayerId()) ~= 0 then
            SetPlayerWantedLevel(PlayerId(), 0, false)
            SetPlayerWantedLevelNow(PlayerId(), false)
        end
    end
end)
