### ISSUE TITLE
House + interphone + Enter into APT = How can we get the id ?

### ISSUE THREAD

**Issue by MagnanQC** [ImagicTheCat/vRP#106]
Hi. 
I see that the house system use the interphone to enter into the appt, but how can the user get his ID *appt #* ?

I can go into the apt, because i see the ID into database, but the player can't.

Thanks, your work is awesome. 
I'm willing to test everything and contribute :)

**Comment by SnaiCrys** [comment]
You can check your aptt ID in your identity.

**Comment by MagnanQC** [comment]
Sure, my bad.!   Thanks,
