### ISSUE TITLE
Server to client to server O_o help

### ISSUE THREAD

**Issue by CrazyForge** [ImagicTheCat/vRP#108]
Hi, i would know if it is possible to make a vRPclient.XXX to client an in client execute the tvRP.XXX and after tvRP.2XXX to server and server execute vRP.2XXX and ....

Or just use the command vRP.addUserGroup(user_id,group) in client with tvRP.addUserGroup(user_id,group)

**Comment by 3rg00** [comment]
Please stop ask stupid questions for nothing. You have your answer in the documentation. If that you trying is too complex for you, wait the official release and post you're questions later. 
The developer ask us at many times to not ask stupid questions like this.
