### ISSUE TITLE
Issue with coma

### ISSUE THREAD

**Issue by hadesfx8** [ImagicTheCat/vRP#110]
Hi, 
When I want to resuscitate a player in a coma, the system tells me that it is not and I have no script error.
I have another problem and I wanted to know if it was normal for some weapons not to be saved in the database, because when I reconnected I no longer have my arms bought.

Thank you in advance :) Your work is very nice !

**Comment by ImagicTheCat** [comment]
You shouldn't update your vRP version while in beta if you don't want issues, as you will see, vRP will tell you if a new stable version is available in the console. 
But I encourage people to use vRP, if they understand the risks.
So the coma system is not stable yet (you can disable it by setting the threshold to 0).

Not all weapons are in the weapon detection script, I need to add them all one day.
