### ISSUE TITLE
Issue with coma when in a vehicle

### ISSUE THREAD

**Issue by ARL64** [ImagicTheCat/vRP#112]
I had coma when I was driving and I could continue to drive until I get out of the car

**Comment by CrazyForge** [comment]
Yes he would make a system, when you are in coma then u exit the vehicle

**Comment by ImagicTheCat** [comment]
Just curious, how did you fall in coma while driving ?

**Comment by ARL64** [comment]
Starving and thirsty :)

**Comment by CrazyForge** [comment]
@ImagicTheCat sometimes, a niggar we attack free

**Comment by ARL64** [comment]
And also I think when you die you didn't loose your inventory and money now

**Comment by ImagicTheCat** [comment]
Fixed.

@ARL64 are you sure about that ?

**Comment by ARL64** [comment]
I think so, I will try on a fresh install because I have a customize version but when using NetworkRessurectLocalPlayer the playerSpawned isn't triggered so neither vRP:playerSpawned

**Comment by ImagicTheCat** [comment]
Yes, that's the point. NetworkRessurectLocalPlayer prevent the death of the player, but the player will be in coma, if the player wait and die, or disconnect and reconnect, he will die and loose everything.
