### ISSUE TITLE
Vehicle customization

### ISSUE THREAD

**Issue by T3rg0s** [ImagicTheCat/vRP#114]
Hello, did you planned to integrate the vehicle customization in the future? It the same system like the clothes?

**Comment by CrazyForge** [comment]
The Los Santos Customs ??

**Comment by 3rg00** [comment]
Hello @ImagicTheCat, I'm working on it but I have a little problem to made a menu with to levels (main menu for primary color categories, submenu for each colors). Do you have any short examples for to do this? 
Thanks in advance :)

**Comment by ImagicTheCat** [comment]
It's good that you explore this field, but I don't have time right now to do it, maybe soon.

**Comment by CruelAlpha** [comment]
Get the losantos customs plugin from the forums, everything works good with that

**Comment by HIsShadowONE** [comment]
@CruelAlpha  do you have a working example of los santos that connects to the vrp player money so you can charge players for the ls customs shops options and have it come out of vrp wallet ? it doesnt work natively does it ?

**Comment by CruelAlpha** [comment]
I actually do, my server has it integrated, however i don't charge people any money. If you do charge people money you just need to use the VRP api

**Comment by HIsShadowONE** [comment]
i have it working also but i cant figure out how to make ti charge players money from vrp wallet , do you have a working example you can share?
 also REQUEST a way to save customizations on owned cars in vrp player garages , currently you have to remod your car every time as the two arent connect so the changes do not save once you store your car and retrieve it

**Comment by TioSleepy** [comment]
Just make so database saves the car color and mods when stored in garage , then people will be able to use ls customs while you work on more important stuff @ImagicTheCat

**Comment by ImagicTheCat** [comment]
It's planned.

**Comment by ENDrain** [comment]
@T3rg0s if you are still working on it, could you commit your code to my repo so I could help you, please?

**Comment by Bretty12Qc** [comment]
vRP its your creation Imagic @ImagicTheCat

**Comment by Bretty12Qc** [comment]
??

**Comment by ImagicTheCat** [comment]
Added basic vehicle state (with customization). No menu (like the skinshop) is planned for now, but most modifications of vehicles by other resources should now be saved (same way as the player ped customization). https://github.com/ImagicTheCat/vRP/commit/468e2f2d5690ec7101dae8ae99bba69fc55664bf
