### ISSUE TITLE
Problem 1 player connected but others players Timed Out

### ISSUE THREAD

**Issue by CrazyForge** [ImagicTheCat/vRP#115]
Hiii, I indicate a problem, All in the title, but i describe the problem, ex: if i'm the first to be connected at the server, then its ok, but the 2nd, 3nd.... players have a timed out until have tried at least 10 times and after the 10 attempts, its ok (approximate)

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/issues/88 duplicate

**Comment by CrazyForge** [comment]
Sry :/
