### ISSUE TITLE
Problem job 

### ISSUE THREAD

**Issue by CrazyForge** [ImagicTheCat/vRP#116]
Hi, i indicate a new problem, if i have a job and i choose other job i have the old job..

Ex: I'm police man an i choose medic, i have medic and police in job

I have try to set the gtype for police in "police" and after for medic in "medic" and inverse.. "job" for all jobs, but its same

**Comment by 3rg00** [comment]
I haven't problems from my side, check your configuration and if players has double groups in the database.

**Comment by CrazyForge** [comment]
Ok ^^, but what is the good config ?? gtype in job for all jobs or police for police man and medic for medic ??

**Comment by 3rg00** [comment]
Get the default config from fresh install of vRP and look in groups.lua cfg.

**Comment by CrazyForge** [comment]
Ok ^^
