### ISSUE TITLE
Problem with emotes (last update)

### ISSUE THREAD

**Issue by CrazyForge** [ImagicTheCat/vRP#119]
Error: http://prntscr.com/faqjp4

At the line 4 i have this: local cfg = require("resources/vrp/cfg/emotes")

and my config is the same file to you:/

**Comment by ImagicTheCat** [comment]
Probably a comma issue, try to update only the cfg file.

**Comment by CrazyForge** [comment]
I dont have the old base.lua o_o xD

**Comment by CrazyForge** [comment]
I have other error now: http://prntscr.com/faqnf5

**Comment by SnaiCrys** [comment]
Upload everything from the beginning. The latest update works well.

**Comment by CrazyForge** [comment]
Okkkkkkk it is just a problem with the --  ["Cop"] = {false, {task="WORLD_HUMAN_COP_IDLES"}, false}, i have remove the space for --["Cop"] and is caused a error xDD

Resolved. Thx

**Comment by ImagicTheCat** [comment]
Probably parsed as lua comment blocks.
