### ISSUE TITLE
Idea: Police System, Police Menu, Police garage... :)

### ISSUE THREAD

**Issue by Zuqaa** [ImagicTheCat/vRP#12]
all in the title

**Comment by ImagicTheCat** [comment]
It is planned, but I miss a few things to fully do it. 
Do you know how a customized officer ped can be done, if it's a model or a function ?

**Comment by Zuqaa** [comment]
Yes i know (but i dont know how to explain this in english :( )

Mais sinon si tu comprend le FR en gros j'ai un police vestiaire est des que tu va sur le point sa te met le vetements (et non le skin) de policier :) Si tu veux je peux te l'envoyer mais j'ai que la partie client apres tu peux le modifier a ta sauce :) J'ai aussi un police menu, menu de police dans le comico... etc.....

**Comment by 3rg00** [comment]
There is native function = Set_ped_as_cop, and other functions for ped cop (set_as_random_cops for exemple)

**Comment by ImagicTheCat** [comment]
Okay, thanks, I will look into this.
