### ISSUE TITLE
Item.transformer error

### ISSUE THREAD

**Issue by cedricalpatch** [ImagicTheCat/vRP#121]
Hello,

I have problem with item.transformer some time I have this error and all jobs is over...
Not still same line of error and this ramdom... Some time with 10 players , some time few player=

I give picture about this problem.

[https://images.discordapp.net/.eJwNyEEOgyAQAMC_8ADApYL4gd6a_qAhSJFEXLO7PRn_Xo8zp_rRpma1ihw8G7M0zkiLZkFKteiKWLeSjsY6YzdJJOW1l13YuGGcgrcD2Bi9uwV3eZgsBBdDHAMAPEyT0j9CaecvUi-k36-nuv5TwCYr.vzM1yFmlTr6hJ_7iPtMWmZzSmPk?width=1032&height=332](url)

**Comment by ImagicTheCat** [comment]
You don't have any other resources using MySQL on the server  ?

**Comment by cedricalpatch** [comment]
yes just one [https://forum.fivem.net/t/release-simple-enters-exits-system-updated-v-0-2/9968](url)

**Comment by ImagicTheCat** [comment]
It can cause conflits, but maybe the last commits fixed this too.

**Comment by cedricalpatch** [comment]
ok thanks a lot, I try this and lets you know ;)

**Comment by cedricalpatch** [comment]
I have try you minor fix and remove the interiors and still same error ... And sure when I have 13 players :(

**Comment by cedricalpatch** [comment]
you thinks this come with players when crashing?

**Comment by cedricalpatch** [comment]
https://gist.github.com/cedricalpatch/8338d1705a9059e447c80cc7b082f2e5

**Comment by cedricalpatch** [comment]
I have the problem ... this is when the players crash in the transformers! You think you can fix this problem?

**Comment by ImagicTheCat** [comment]
After the crash, what are the errors ? And what do you mean by it's not working (no menu to start transforming, transforming don't do anything, the progress bar is visible, etc) ?

**Comment by cedricalpatch** [comment]
Still same error like I have send already : 

https://images.discordapp.net/.eJwNyEEOgyAQAMC_8ADApYL4gd6a_qAhSJFEXLO7PRn_Xo8zp_rRpma1ihw8G7M0zkiLZkFKteiKWLeSjsY6YzdJJOW1l13YuGGcgrcD2Bi9uwV3eZgsBBdDHAMAPEyT0j9CaecvUi-k36-nuv5TwCYr.vzM1yFmlTr6hJ_7iPtMWmZzSmPk?width=1032&height=332

All work just the job dont give item... progress bar is here but not move and for all jobs!
The menu work , menu user all work still...

**Comment by Bandit33800** [comment]
test avec ceci

{
    name="Fabrication de Lingots", -- menu name
    --permission="artisan.vehicle",-- you can add a permission
    r=0,g=125,b=255, -- color
    max_units=60,
    units_per_minute=3,
    x=1088.25,y=-2001.51,z=30.87, -- pos
    radius=5, height=1.5, -- area
    action="Allez au travail", -- action name
    description="Usinage de Lingots.", -- action description
    in_money=0, -- money taken per unit
    out_money=2400, -- money earned per unit
    reagents={
	  ["pierreprecieuse"] = 10
	}, -- items taken per unit
    products={ -- items given per unit
      ["or"] = 10
    }
  },

j ai modifier la partie 
 in_money=0, -- money taken per unit
    out_money=2400, -- money earned per unit
mais c est bizarre tu leur donne de l argent

**Comment by ImagicTheCat** [comment]
The exception break the SetTimeout loop, shutting down all item transformers. The problem is, I don't understand why there is an already opened DataReader, debug mode may help to find the issue.

**Comment by cedricalpatch** [comment]
hello,

I have run debug mode but I dont found file or log file or in db??
And for take picture of Rcon this impossible, lot of info run...
Can you tell me where is it?

@Bandit33800 thank for this info but I dont this the problem come from this... And yes for out and in money this what I whant ... we have privat business so this for new player's can have some money when boss of business is not here ;)

**Comment by jakepavek** [comment]
any idea what is causing this yet?

**Comment by Thalexs** [comment]
Reporting the same error, jobs stop working after some time/amount of players .
Sending log, so you can check
https://pastebin.com/V7sjQxJB

**Comment by Thalexs** [comment]
If you need any other log call me

**Comment by ImagicTheCat** [comment]
Since I can't solve right now those errors (I don't even know how a multiplication can trigger an exception, thanks to FiveM/NeoLua), I tried to save the item transformers loop, so it should stay alive even if people experience bugs sometimes. Let me know if it worked (cf https://github.com/ImagicTheCat/vRP/commit/aa61f3cbaac81c159ae637938120d5629534fcbb).

**Comment by ImagicTheCat** [comment]
Any news ?
