### ISSUE TITLE
First spawn

### ISSUE THREAD

**Issue by SnaiCrys** [ImagicTheCat/vRP#123]
On first entry to the server, the player appears in randomly place on the map, and not teleported to the spawn point.
![4ad33bb1550d408e8d29f9f32366ffca](https://cloud.githubusercontent.com/assets/4284827/26346779/f61f67be-3faf-11e7-9902-e4e8f42e57aa.jpeg)

base.lua:17
Function tvRP.teleport(x,y,z) works good.

**Comment by ImagicTheCat** [comment]
But after a while, they are teleported to their last position right ?

**Comment by SnaiCrys** [comment]
Yep

**Comment by ImagicTheCat** [comment]
Should be fixed.
