### ISSUE TITLE
tunnel error

### ISSUE THREAD

**Issue by cedricalpatch** [ImagicTheCat/vRP#125]
I have this error ramdomly ... Maybe gui.lua have problem ?
This come often when players come in or out the server...

[https://images.discordapp.net/.eJwNyEEOgyAQAMC_8ABwoYL4gd6a_qAhuEETZM2ynhr_rseZvzq5qlmtIkefjVm2nokX3YU4FdSFqFRMx9Z1pt0kkZTXHZt042Ccgh_ADjF698g-5QO8HETrJxjBxmDkbA3rD5mJ9ffzVtcNusMkhg.gdxYzFR3x4C07f2NqHZJI0IYn-4?width=1032&height=313](url)

**Comment by ImagicTheCat** [comment]
The console doesn't give all stack lines, so this can be an error outside vRP, in a menu choice callback.

**Comment by cedricalpatch** [comment]
please check again, this error on double in first picture

[https://cdn.discordapp.com/attachments/315876012099633152/316758367584387084/tunnel_error.PNG](url)

**Comment by ImagicTheCat** [comment]
I can't solve this issue if I can't know where it comes from, wait for someone else to experience it or enable debug mode and give me ALL the output in a text file.

**Comment by cedricalpatch** [comment]
ok I try with debug mode for give you more info

**Comment by ImagicTheCat** [comment]
Any news on this ?
