### ISSUE TITLE
Props (bandana , mask)

### ISSUE THREAD

**Issue by Geronimin** [ImagicTheCat/vRP#128]
Can you add this on shop ?

**Comment by Bandit33800** [comment]
Hi Geronimin, that it is lt interest to put mask or bandana in the store it is of the role play not gta online has the limit add an option put a hood in your personal menu

**Comment by Geronimin** [comment]
oui mes comment faire ?

**Comment by Bandit33800** [comment]
https://fivem-france.net/t/script-cagoule-masque/206
si cela peut t aider ,a toi de l adapter a vRP pour mettre la cagoule en option dans ton menu perso

If it can not help, you have to adapt it to vRP to put the hood in option in your personal menu

**Comment by ImagicTheCat** [comment]
Ped props and ped variations are all supported by the skinshop module. Check the skinshop configuration.

**Comment by Bandit33800** [comment]
I had test for the vest by bullet
Which is the 9
For my police uniform this creates
An error or was not functional
