### ISSUE TITLE
Indicator for die or call medic when in coma

### ISSUE THREAD

**Issue by CrazyForge** [ImagicTheCat/vRP#129]
Hi it's possible to add a function for die directly when i press X or others touch when i'm in coma or for call medic ??

**Comment by 3rg00** [comment]
Code it yourself

**Comment by CrazyForge** [comment]
It just a suggestion, dont thus not need to send flying me

**Comment by CrazyForge** [comment]
Pfff

**Comment by ImagicTheCat** [comment]
Death should be punitive for a more RP experience, what is the point of having a coma system if you want an instant respawn ? When players don't care about dying, the RP die.
But, if you are in a situation where you are sure that no one is gonna help you, you can disconnect/reconnect to the server, it will kill you.

You can't call a medic while in coma... I don't need to explain why. However, I added an option to keep the menu enabled while in coma, it's up to the players to follow your coma rules in this case.

vRP is a RP framework, not a gamemode, I will make sure to keep it RP, while giving freedom in the configuration. 

PS: you can disable the coma system by setting the coma duration to 0.
