### ISSUE TITLE
J'ai fix le problème pour les bâtiments invisible

### ISSUE THREAD

**Issue by Nadochima** [ImagicTheCat/vRP#13]
Je load juste les IPL pour les clients :D
Ajoute le dans vRP pour ajouté encor des function :)
- https://drive.google.com/open?id=0B2bkTMzQdNQPX3ZjeDYyV0p0eGM

**Comment by Zuqaa** [comment]
Le créa est FR ? 🗡

**Comment by ImagicTheCat** [comment]
Two things:
* english only, to keep everyone in the loop
* each submission must use git or it is pointless (but I will look into this one when I have time)

**Comment by Nadochima** [comment]
-FIX IPL Loader
https://gist.github.com/Nadochima/94732a5888c24946c45a0d0074fea0df
