### ISSUE TITLE
weight items

### ISSUE THREAD

**Issue by hadesfx8** [ImagicTheCat/vRP#131]
Hi,

The weight items of the cfg/items.lua don't work, is always shows 0kg.

Thanks in advance :)

**Comment by CrazyForge** [comment]
Its work perfectly for me.. Retry to make the update..

**Comment by hadesfx8** [comment]
Yes is the same, even with a blank copy, it still does not work. I'm talking about items that are in the cfg/items.lua file and not the modules basic_items.lua

**Comment by ImagicTheCat** [comment]
Yes, missing feature, will fix it soon. Thanks for the report.

**Comment by ImagicTheCat** [comment]
Should be fixed.

**Comment by hadesfx8** [comment]
It's nothing :) thanks to you
