### ISSUE TITLE
Progresse bar and icon money / dirty money

### ISSUE THREAD

**Issue by Geronimin** [ImagicTheCat/vRP#132]
You can modif this progresse barre i have screach good HUD maybe i can't use this you can help me my freind ? 

https://www.hostingpics.net/viewer.php?id=919714bank.png

https://www.hostingpics.net/viewer.php?id=811506blackmoney.png

https://forum.fivem.net/uploads/default/original/2X/5/5472c82d1dc49c95ad02cee84d50aadcdc38940d.PNG

Thank's bro , for your work 

PS : my English  is very bad so sorry .

**Comment by SnaiCrys** [comment]
All this is very easily changed. As the author says, wait for the release.
