### ISSUE TITLE
[Feature] Get the group of a user by a group type

### ISSUE THREAD

**Issue by ARL64** [ImagicTheCat/vRP#134]
In **_vrp/modules/group.lua_**
```lua
-- get a group of a user by group type
function vRP.getUserGroup(user_id,gtype)
  local user_groups = vRP.getUserGroups(user_id)
  for k,v in pairs(user_groups) do
    local kgroup = groups[k]
    if kgroup then
      if kgroup._config and kgroup._config.gtype and kgroup._config.gtype == gtype then
        return k
      end
    end
  end
  return false
end
```

Usefull to get the job of a user
```lua
local user_id = vRP.getUserId(player)
if user_id ~= nil then
  local job = vRP.getUserGroup(user_id, "job")
  if job then
    vRPclient.setDiv(...)
  end
end
```
Maybe **getUserGroupByType**(user_id,gtype) instead of **getUserGroup**(user_id, gtype)

**Comment by ARL64** [comment]
![Example](https://cloud.githubusercontent.com/assets/837109/26471838/aa837700-41a3-11e7-9447-82247b4361d6.png)

**Comment by Aleweadan** [comment]
Nice, you should make a pull requests for that.

**Comment by Geronimin** [comment]
how you change HUD for money and bank , job ?

**Comment by ARL64** [comment]
- learn css
- look at vRP documentation

**Comment by ImagicTheCat** [comment]
Added, thanks.

**Comment by RyUkApples** [comment]
Yes but the problem is, when you go to pole emploi for change your job the hud doesnt refresh

**Comment by ARL64** [comment]
You have to change the onjoin function or the onleave function of a group to refresh in **cfg/groups.lua**

**Comment by RyUkApples** [comment]
And what i add ?
