### ISSUE TITLE
modify vehicle max

### ISSUE THREAD

**Issue by CrazyForge** [ImagicTheCat/vRP#136]
Hi i have make a system of job with garage, but i can only take 1 vehicle.. But i want spawn Truck + Trailer and its impossible now, cause: only 1 vehicle can spawn

**Comment by ImagicTheCat** [comment]
There are no such things as maximum vehicles, you can only spawn one vehicle of the same vtype at a time. Look at the vRP LaTest FR config, trailer is a vtype.

**Comment by CrazyForge** [comment]
AH YES THANK YOU OMG !!!
