### ISSUE TITLE
Suggestion: Move left in menu

### ISSUE THREAD

**Issue by CrazyForge** [ImagicTheCat/vRP#137]
Hi i publish this for know if its possible for you to add thing for move left in menu

Exemple: i choose a face and i miss my favorite face in menu, its impossible to move left i must restart from the beginning

**Comment by ImagicTheCat** [comment]
At this point it's not planned. Skinshop will be more easy to use with the presets.

**Comment by CrazyForge** [comment]
Okey Thx ^^ Finally somebody who speaks to me friendly
