### ISSUE TITLE
Suggestion: Player List

### ISSUE THREAD

**Issue by CrazyForge** [ImagicTheCat/vRP#138]
Hiii ^^

Are you planning to make a list of players?

**Comment by 3rg00** [comment]
There is already a player list in admin functions...

**Comment by Aleweadan** [comment]
Yes already here... close issue pls

**Comment by CrazyForge** [comment]
Yes but for all players, and with a more beautiful style

**Comment by 3rg00** [comment]
Once again, the cosmetic part is not the objective of this framework. Please stop flood this git, and let ImagicTheCat do the most importants parts of this framework. We don't care about cosmetic, we can do it easily.

**Comment by CrazyForge** [comment]
Ok, u can talk with me gently pls im not a dog..

**Comment by CrazyForge** [comment]
And anyone its just a suggestion not a obligation

**Comment by 3rg00** [comment]
Stop flood this git for nothing. Not less not more.

**Comment by CrazyForge** [comment]
Pfff.

**Comment by Aleweadan** [comment]
Wait the fivem forum release for that questions. Imagic says that many many times...

**Comment by CrazyForge** [comment]
YES I KNOW BUT "ANYONE" IT JUST A "SUGGESTION", SUGGESTION DUDE A IDEA NOT A HELP

**Comment by ImagicTheCat** [comment]
I thank people who help me by answering on typical issues, but please don't start a fight. If someone is flooding, I will take care of it.
