### ISSUE TITLE
Style of walking after an action

### ISSUE THREAD

**Issue by Bandit33800** [ImagicTheCat/vRP#139]
Hi, here is the native for the walking style
If this can be interesting eg if he drinks vodka:
"move_m@drunk@verydrunk"

Or even to personalize his own character

Maybe the idea will interest you

static void SET_PED_MOVEMENT_CLIPSET(Any p0, const char *p1, Any p2) { invoke<Void>(0xA817CDEB, p0, p1, p2); } // 0xA817CDEB

 "ANIM_GROUP_MOVE_BALLISTIC"
 "ANIM_GROUP_MOVE_LEMAR_ALLEY"
 "clipset@move@trash_fast_turn"
 "FEMALE_FAST_RUNNER"
 "missfbi4prepp1_garbageman"
 "move_characters@franklin@fire"
 "move_characters@Jimmy@slow@"
 "move_characters@michael@fire"
 "move_f@flee@a"
 "move_f@scared"
 "move_f@sexy@a"
 "move_heist_lester"
 "move_injured_generic"
 "move_lester_CaneUp"
 "move_m@bag"
 "MOVE_M@BAIL_BOND_NOT_TAZERED"
 "MOVE_M@BAIL_BOND_TAZERED"
 "move_m@brave"
 "move_m@casual@d"
 "move_m@drunk@moderatedrunk"
 "MOVE_M@DRUNK@MODERATEDRUNK"
 "MOVE_M@DRUNK@MODERATEDRUNK_HEAD_UP"
 "MOVE_M@DRUNK@SLIGHTLYDRUNK"
 "MOVE_M@DRUNK@VERYDRUNK"
 "move_m@fire"
 "move_m@gangster@var_e"
 "move_m@gangster@var_f"
 "move_m@gangster@var_i"
 "move_m@JOG@"
 "MOVE_M@PRISON_GAURD"
 "MOVE_P_M_ONE"
 "MOVE_P_M_ONE_BRIEFCASE"
 "move_p_m_zero_janitor"
 "move_p_m_zero_slow"
 "move_ped_bucket"
 "move_ped_crouched"
 "move_ped_mop"
"MOVE_M@FEMME@"
"MOVE_F@FEMME@"
"MOVE_M@GANGSTER@NG"
"MOVE_F@GANGSTER@NG"
"MOVE_M@POSH@"
"MOVE_F@POSH@"
"MOVE_M@TOUGH_GUY@"
"MOVE_F@TOUGH_GUY@"

;)

**Comment by ImagicTheCat** [comment]
Didn't succeed to implement it a while ago, not planned at this point.
