### ISSUE TITLE
Bug + Fix temporary: Hud Deplaced (for some resolutions)

### ISSUE THREAD

**Issue by Zuqaa** [ImagicTheCat/vRP#14]
Hi i prevent You i have a problem.. The Hud is deplaced: http://prntscr.com/f4mjm5

**Comment by ImagicTheCat** [comment]
It is a known issue,  waiting to find a generic way to place it correctly on all resolutions.

**Comment by Zuqaa** [comment]
I'm in 1920x1080...

**Comment by Zuqaa** [comment]
So ?

**Comment by Zuqaa** [comment]
U have a solution for deplaced the hud ??

**Comment by ImagicTheCat** [comment]
I don't know yet what are the factors for the position and the width of the minimap, and I don't have time to search them right now. If you want to have this feature, try to help by finding those factors, comparing the screens of a maximum of players, to understand how to place it. FRFuel seems to nicely manage the position, so it's a start.

**Comment by Zuqaa** [comment]
Ok ;)

**Comment by Zuqaa** [comment]
I have found this: https://github.com/thers/FRFuel/blob/master/HUD.cs

**Comment by 3rg00** [comment]
I've fixed manually for 1920x1080, I need to make conditions for each resolution, do you have any idea about to retrieve current res ingame ?

**Comment by Zuqaa** [comment]
I search this ;)

**Comment by Zuqaa** [comment]
https://wiki.fivem.net/w/index.php?title=GetScreenActiveResolution&action=edit&redlink=1 i have found this native

**Comment by Zuqaa** [comment]
So ?

**Comment by 3rg00** [comment]
So try yourself and contribute :)

**Comment by Zuqaa** [comment]
Yep i try ;)

**Comment by Zuqaa** [comment]
3rg00 check ur PM in my forum evasionrp...

**Comment by Aleweadan** [comment]
Zuqaa do you find something ?

**Comment by Zuqaa** [comment]
For set the hud for any resolution... no but for the resolution 1920x1080 yes ^^ i publish this after

**Comment by Aleweadan** [comment]
Ok

**Comment by Zuqaa** [comment]
Ok, so if u use FrFuel use this code:
Goto Gui\ProgressBar.js and repace the line 63 and 64 by

`        this.div.style.left = (28+anchor_index*width)+"px";
        this.div.style.top = (document.body.offsetHeight-233)+"px";`

**Comment by Zuqaa** [comment]
And @ImagicTheCat, There is a problem with the size of the bar no ?
I send a screen soon

**Comment by Zuqaa** [comment]
Screenshot: http://prntscr.com/f5akmv

**Comment by 3rg00** [comment]
There is no problems with size, the parameter to change it is:
        //set size
        this.div.style.width = this.div_label.style.width = (width-2)+"px";
        this.div_inner.style.height = this.div.style.height = **this.div_label.style.height = (12)+"px"**;
        this.div_label.style.lineHeight = this.div_label.style.height;

But I think it's not a FIX, because we need to find a solution for to adapt it for each resolution.
I will pull soon a modification that use JS for adapt directly all positions of progressbar and other UI frame for each resolution.

**Comment by Zuqaa** [comment]
Ok nice ;)

**Comment by Zuqaa** [comment]
I have found this : https://wiki.rage.mp/index.php?title=Events::callRemote

I'm dont can work on this, i go to my work :/

**Comment by 3rg00** [comment]
@ImagicTheCat its ok for you if we only use CSS style instead of creating width and other styling parameters directly in JS?.
For example, I set the div container and styled my "money" div that will be directly injected by JS, with value setted, so now I have the money hud correctly displayed a the top right of display, for each resolution.

**Comment by ImagicTheCat** [comment]
I don't understand the question. About the vRP.setDiv ?

**Comment by 3rg00** [comment]
Nop, I created a #container directly in the index.html, styled my #money in .css, and created the #money div directly from JS, with value injection. So now, when I change resolution, everything is scaled fine :).
I made same thing for Bank account and "future" job name.
I just want to know if its interesting for you if pull it ?

**Comment by Zuqaa** [comment]
3rg00, Gg dude ^^

**Comment by ImagicTheCat** [comment]
I discourage you to do the hud by modifying vRP directly, because each update will break your work.
Also, vRP is generic, there is no such things as money to be pre-built client-side, so I can't accept the pull. 
But, if you succeeded to have a resolution independent code, it could be interesting to share your work somewhere, so I can understand it and apply it to the progress bars.

**Comment by 3rg00** [comment]
Yep, I will convert it to an external mod and link it to here tomorrow. Thanks :)

**Comment by Zuqaa** [comment]
So ? ^^

You have a news for the issue ?

**Comment by Zuqaa** [comment]
So @ImagicTheCat ?? :D

**Comment by Aleweadan** [comment]
So wait or done it yourself xD

**Comment by ImagicTheCat** [comment]
So, until I find a great way to do this (something changed in FiveM in the last update about the UI scaling), you can configure the progress bar position in **cfg/gui.lua**, using left and bottom position.
