### ISSUE TITLE
First Spawn...

### ISSUE THREAD

**Issue by CrazyForge** [ImagicTheCat/vRP#141]
Hiii, it is possible to make a system for open a menu at first spawn, if  yes what is the event ?? it's vRP:FirstSpawn ??

**Comment by ImagicTheCat** [comment]
RTFM.

**Comment by CrazyForge** [comment]
O_o ??

**Comment by CrazyForge** [comment]
Ah ok ReadTheFuckingManual :) but in the readme what is the FUCKING option FirstSpawn ?? if first_spawn then.... it draw the menu at some spawn dude and not a the FIRST spawn

**Comment by ImagicTheCat** [comment]
You submitted a lot of issues (~24) and I (and others) took my time to answer, and warn you about your behavior. This is not a forum, if you can't understand that, then you have nothing to do here. You will not be able to submit issues anymore.
(cf https://github.com/ImagicTheCat/vRP/issues/124 https://github.com/ImagicTheCat/vRP/issues/126 https://github.com/ImagicTheCat/vRP/issues/127 https://github.com/ImagicTheCat/vRP/issues/98 https://github.com/ImagicTheCat/vRP/issues/100  https://github.com/ImagicTheCat/vRP/issues/107  https://github.com/ImagicTheCat/vRP/issues/108 https://github.com/ImagicTheCat/vRP/issues/109 https://github.com/ImagicTheCat/vRP/issues/111 https://github.com/ImagicTheCat/vRP/issues/113  https://github.com/ImagicTheCat/vRP/issues/115 https://github.com/ImagicTheCat/vRP/issues/119)
