### ISSUE TITLE
Problem Handcuff

### ISSUE THREAD

**Issue by CrazyForge** [ImagicTheCat/vRP#142]
Hii, the handcuff doesnt work since some update... He work perfectly before :/

It's same for put a guy in vehicle

**Comment by ImagicTheCat** [comment]
I have banned you from the issues just after this one, but it will not prevent me of solving this, if it's a real issue.

**Comment by RyUkApples** [comment]
I have the same problem, and same for ask open chest

**Comment by ImagicTheCat** [comment]
Errors ? What is working or not working exactly ? Saying "it doesn't work" is not useful.

**Comment by RyUkApples** [comment]
For me, just when i push the button ask open chest and handcuff any action is executed..

**Comment by RyUkApples** [comment]
Okey, so handcuff re-work, put in vehicle: no

**Comment by ImagicTheCat** [comment]
With all vehicles ? Or only police vehicles ?

**Comment by RyUkApples** [comment]
All i have test on civil vehicle but i can test on my personal or my police vehicle wait..

**Comment by RyUkApples** [comment]
Its dont working for all vehicles but if the player is not nearest then i have the mess.. its the single function who work !

**Comment by RyUkApples** [comment]
You have news for putinveh ? thx in advance

**Comment by ImagicTheCat** [comment]
I don't understand your bug report, but put in vehicle has been reworked.
