### ISSUE TITLE
Menu order

### ISSUE THREAD

**Issue by T3rg0s** [ImagicTheCat/vRP#143]
Hello @ImagicTheCat, is it possible to re-organize the main menu?

Thank's in advance :).

**Comment by ImagicTheCat** [comment]
Not really, it depends on NeoLua when it comes to iteration order (doesn't seems alphabetic). It also depends on the "callback hell" order of execution. What is troubling you about the menu ?

**Comment by 3rg00** [comment]
Hmm ok, I will try to do some order in the callback hell :), I need to ordering my added interaction menu per job. Thanks for your answer :)
