### ISSUE TITLE
BIG PROBLEM

### ISSUE THREAD

**Issue by RyUkApples** [ImagicTheCat/vRP#144]
Hi, my vrp is full bugged, since 2 weeks he working perfectly, and today i have launch my server and i have this : 

https://image.prntscr.com/image/08c411906573452ea6c1843ad47d0f86.png

I dont have modified my vrp

**Comment by RyUkApples** [comment]
Nooooooooooooooooooooooooooooooooo... :'( it's a limit of group i have added too much group in groups.lua :/

**Comment by ImagicTheCat** [comment]
A limit of group ? I don't think it's possible but... well I don't know with NeoLua anymore.

**Comment by RyUkApples** [comment]
I have remove a group livreur de pizza and my vRP re-work perfectly :/
