### ISSUE TITLE
Character customization saving

### ISSUE THREAD

**Issue by 3rg00** [ImagicTheCat/vRP#145]
Hello @ImagicTheCat, There is any possibities to add option for to save character customization only when players choose it at the skinshop ?
I search a  solution for the job clothes function, for example, when player take cop service, he takes the cop clothes, but he can't retrieve theirs "civilians" clothes when he leave the cop service.

Thank's in advance for your answer :)

**Comment by ImagicTheCat** [comment]
Not a good idea, I will generalize the cloakroom to put/rollback clothes.

**Comment by 3rg00** [comment]
Thanks a lot for your commit, it's really nice :).
