### ISSUE TITLE
Missing a little "local" to avoid globals

### ISSUE THREAD

**Issue by ARL64** [ImagicTheCat/vRP#147]
In **modules/police.lua**

Line 329 :
```lua
x,y,z = table.unpack(cfg.pc)
```
to :
```lua
local x,y,z = table.unpack(cfg.pc)
```
Deleted on this commit : 258df6367a8beb2b1cd37d89b66cc573276d2a9b

**Comment by ImagicTheCat** [comment]
Thank you for the report, will be fixed in next commit.
