### ISSUE TITLE
[Feature] Improve fine system

### ISSUE THREAD

**Issue by SnaiCrys** [ImagicTheCat/vRP#149]
Add to try to take money from the bank in case of lack of money in the wallet.

**Comment by hadesfx8** [comment]
And if possible that the money of the fine is recovered by the policeman ? thx in advance :)

**Comment by Armagryzor** [comment]
Hi Imagic ,

I tried your last update  ( Always big thank's for your work ;) )but i saw a little problem..

All work nice ..But to make a fine ,if  the citizen haven't cash , the fines system doesn't work.. like the post 1 of SnaiCrys  , is it possible that you can modify your code to take the money in the bank account?

**Comment by ImagicTheCat** [comment]
It does work, but you can't fine people if they don't have the correct money amount right now.

**Comment by ImagicTheCat** [comment]
Now it takes in bank too. For now, the money will be lost for everyone until I find a good usage.
