### ISSUE TITLE
trailler inventory

### ISSUE THREAD

**Issue by cedricalpatch** [ImagicTheCat/vRP#150]
Hello ,

Great job for last update... all work fine for me=
For trailler when I atach the trailler my trunk is still 50kg?
This fonction work realy?

Thanks

**Comment by ImagicTheCat** [comment]
The trailer is a vehicle, so you have two trunks. Stay close to the trailer.

**Comment by cedricalpatch** [comment]
ok all is right, we need go right or left side for have the trunk of trailler ;)
