### ISSUE TITLE
Revive system?

### ISSUE THREAD

**Issue by ScottWuk** [ImagicTheCat/vRP#151]
Is it possible that you add EMS, which get the option to accept a call when someone dies (Similar to the F5 and F6 police system) And it sets a blip to the subject in the coma

**Comment by ImagicTheCat** [comment]
An auto call ? Like the peds are calling for you ? I could add an option, but I need to think about it. 
Calling when you fall in coma is too easy, and an easy death break the RP.

**Comment by ScottWuk** [comment]
ok then can you add EMS to the job selector? As then other people could call EMS and it would let them, know where the person calling is

**Comment by ImagicTheCat** [comment]
Issues are not for help, you already can do that in the configuration files.

**Comment by ImagicTheCat** [comment]
You can enable the menu while in coma in the options (cfg/client.lua), so they can call your emergency service with the phone. I will not add an auto call, too many problems.
