### ISSUE TITLE
Moyen tu go Discord ?? URGENT

### ISSUE THREAD

**Issue by RyUkApples** [ImagicTheCat/vRP#152]
Des gens foutre le zbeul sur le discord dans Aide

**Comment by rudzboy** [comment]
Tu sais lire ?

```Issues / Features / Help

The issue section is only for bug reports and feature requests. I will close (and ban) issues not related to the core of vRP, to keep the github clean.```

**Comment by ARL64** [comment]
Rudzboy, I am agree with you, but some people have no respect for work of others. Let's go see the discord, you will see... They need a ban. I talked to them and they insulted me and ban me from their discord. 
A server not to go  : TheftRP sorry for anti-server, but they are not good dev.
