### ISSUE TITLE
Wanted System

### ISSUE THREAD

**Issue by T3rg0s** [ImagicTheCat/vRP#154]
Hello @ImagicTheCat, there is any way to exclude cops from the wanted system ?
Because in RP, if cops fire or take car that not owned, its not really nice to have a wanted level and blip for others cops ^^.

Thank's in advance.

**Comment by ImagicTheCat** [comment]
I was thinking about it but found funny while coding that some cops could be arrested by other cops for bad behavior. Will see.

**Comment by T3rg0s** [comment]
I will test this: check cop permission and change the blip position of cop currently wanted. In this way, it will be possible for others cop's to assist on. What do you think about it @ImagicTheCat?

**Comment by ImagicTheCat** [comment]
I think I will disable the wanted level for cops, the idea about wanted cops is maybe too much.

**Comment by ImagicTheCat** [comment]
Done.
