### ISSUE TITLE
Hi! Where to buy med kits? Thanks

### ISSUE THREAD

**Issue by ScottWuk** [ImagicTheCat/vRP#155]
Hello!

Where do you buy medkits? As when EMS try to revive it says they have to have a medkit. For no i'm spawning them in

Thanks,
Scotty

**Comment by Bandit33800** [comment]
Hello, base when you ask for something, it's politeness
(Hello, hello, good night, etc ...)
If you want to get answers

**Comment by Bandit33800** [comment]
hi ,
You must follow this path:
Vrp/cfg/market.lua 
In it you have to create the point d where you wish to find your drugstore
expemple: 
{"food",-707.408996582031,-913.681701660156,19.2155857086182},
Except that you replace: food by drugstore
You have to collect the coordinates of the place where you want to have your drugstore

**Comment by ScottWuk** [comment]
Thanks a lot Bandit!
