### ISSUE TITLE
Question  ?

### ISSUE THREAD

**Issue by Armagryzor** [ImagicTheCat/vRP#156]
Hi Imagic,

It's not an issu but a simple question..

Have you  a plan to add a simple paycheck for cops and emergency ?

Thank's in advance for your reply.

**Comment by ImagicTheCat** [comment]
Use the FiveM topic for this kind of things.
It 's not planned, but easy to do. It's better to earn money by your actions than by just spending time. If you ask me, you shouldn't play as a cop to earn money (it's a public service, not a lucrative work).
