### ISSUE TITLE
despawnGarageVehicle not working as expected

### ISSUE THREAD

**Issue by remcotroost** [ImagicTheCat/vRP#157]
I've found an issue with storing the vehicle back in a garage. The notification that the vehicle is stored is initiated, but the vehicle does not despawn.

I have found the bug fix.

in client/basic_garage.lua line 51 add:
`Citizen.InvokeNative(0xAD738C3085FE7E11, vehicle[3], true, true)`

This is due to the following Native Reference [https://runtime.fivem.net/doc/reference.html#_0xEA386986E786A54F](https://runtime.fivem.net/doc/reference.html#_0xEA386986E786A54F)

The despawnGarageVehicle function will now look like the following:

```
function tvRP.despawnGarageVehicle(vtype,max_range)
  local vehicle = vehicles[vtype]
  if vehicle then
    local x,y,z = table.unpack(GetEntityCoords(vehicle[3],true))
    local px,py,pz = tvRP.getPosition()

    if GetDistanceBetweenCoords(x,y,z,px,py,pz,true) < max_range then -- check distance with the vehicule
      -- remove vehicle
      Citizen.InvokeNative(0xAD738C3085FE7E11, vehicle[3], true, true)
      Citizen.InvokeNative(0xEA386986E786A54F, Citizen.PointerValueIntInitialized(vehicle[3]))
      vehicles[vtype] = nil
      tvRP.notify("Vehicle stored.")
    else
      tvRP.notify("Too far away from the vehicle.")
    end
  end
end
```

This may also be needed in other functions where vehicle despawns are done

**Comment by ImagicTheCat** [comment]
Hi,
I saw this problem only with a specific distance with the vehicle, so I reduced the distance, but if this fix it, it's nice. Can you explain what is the added native ?

**Comment by remcotroost** [comment]
Yes, I thought it was the specific distance too so I was playing around with your function but without any positive results.

The added native is `SET_ENTITY_AS_MISSION_ENTITY` and is described in `DELETE_VEHICLE` as a must set before deleting a vehicle. My guess is that setting the vehicle as a mission entity when spawning the vehicle may also fix the issue. That might actually be a better solution as then the vehicle will never despawn randomly.

```
// 0xAD738C3085FE7E11 0x5D1F9E0F
void SET_ENTITY_AS_MISSION_ENTITY(Entity entity, BOOL p1, BOOL p2);
Makes the specified entity (ped, vehicle or object) persistent. Persistent entities will not automatically be removed by the engine.
```

```
// 0xEA386986E786A54F 0x9803AF60
void DELETE_VEHICLE(Vehicle* vehicle);
Deletes a vehicle.
The vehicle must be a mission entity to delete, so call this before deleting: SET_ENTITY_AS_MISSION_ENTITY(vehicle, true, true);
```

**Comment by ImagicTheCat** [comment]
The bug was about cop vehicles or other utilities ? Can you try (or I will soon) to set the vehicle as mission vehicle when spawning it instead, and check if you can put someone in the cop vehicle (as a cop).

**Comment by remcotroost** [comment]
Any vehicles. I may have done something else myself that triggered this behavior, but I think regardless that adding this Native somewhere is a better approach. I will try setting the native when spawning a vehicle and put someone inside a cop vehicle when I get the chance. Right now I'm developing a server on my own.

**Comment by ImagicTheCat** [comment]
Okay, I added the native, but I don't know yet if it will solve your issue. I have reworked the put in vehicle so the issue is obsolete.
