### ISSUE TITLE
Vehicles

### ISSUE THREAD

**Issue by fapiche** [ImagicTheCat/vRP#158]
Salut et désolé si c'est déjà en place mais comptes tu ajouter des variables paramétrables sur les véhicules tel que de la santé et des armures de base par exemple pour implanter le métier de dépanneur et rendre chaque véhicule unique genre un gros 4*4 plus solide qu'une petite caisse par exemple?

**Comment by ImagicTheCat** [comment]
Please use english. Also be more specific in your issue title like "[Feature] Vehicle health and armor".
Since there is nothing about fuel (already exists and nicely done), at this point, no attributes are planned for vehicles.
