### ISSUE TITLE
driving while in coma

### ISSUE THREAD

**Issue by HIsShadowONE** [ImagicTheCat/vRP#159]
if you enter coma due to hunger or thirst ,or sudden death etc, while in a vehicle you are still able to drive until you exit the vehicle or revive.

**Comment by Bandit33800** [comment]
Hello, base when you ask for something, it's politeness
(Hello, hello, good night, etc ...)
If you want to get answers

**Comment by HIsShadowONE** [comment]
i am reporting a bug with his script to help make it better not greeting a friend at a party. im not here to suck people off to get fixes .
im here to help improve a script/mod and ive helped plenty of people in the discord for this mod without requiring any hey hello bud and goodnight i love you statements.

**Comment by ScottWuk** [comment]
Your definitely not gonna get a response now lol

**Comment by T3rg0s** [comment]
Try to use this function:

> function tvRP.ejectVehicleTest()
>   local ped = GetPlayerPed(-1)
>   if IsPedSittingInAnyVehicle(ped) then
>     ClearPedTasksImmediately(ped)
>     plyPos = GetEntityCoords(ped,  true)
>     local xnew = plyPos.x+2
>     local ynew = plyPos.y+2
>     SetEntityCoords(ped, xnew, ynew, plyPos.z)
>   end
> end

**Comment by ImagicTheCat** [comment]
This is not a forum, please keep issues clean and concise.

**Comment by ImagicTheCat** [comment]
Fixed.
