### ISSUE TITLE
Transformers/harvesters ground markers are invisible

### ISSUE THREAD

**Issue by VlivesRaw** [ImagicTheCat/vRP#160]
In item_transformer.cfg there is an option to change color (r=0,g=125,b=255, -- color), but the ground marker do not appear to be visible. Even with default config, water_tree harvester is invisible.

**Comment by Bandit33800** [comment]
Hello, base when you ask for something, it's politeness
(Hello, hello, good night, etc ...)
If you want to get answers

**Comment by VlivesRaw** [comment]
@Bandit33800 I consider GitHub to be a developer chat - the shorter the better, cut straight to the point. You know, it saves a lot of time when you do not need to not read through a wall of text of "politeness".

**Comment by Bandit33800** [comment]
I think especially that when one is a minimum educated one uses the rules of politeness
And if you would be a minimun developer you will not ask a question on this subject
Also easy
Read the description of the GitHub

**Comment by ImagicTheCat** [comment]
Item transformers doesn't have markers, the color is for the menu.
