### ISSUE TITLE
Call system

### ISSUE THREAD

**Issue by jakepavek** [ImagicTheCat/vRP#166]
The call system is a bit buggy where it doesn't let you select the call. I think it should be like the admin ticket where it says someone has answered it. I run a full server and t won't let them answer the call or even deny it most times 

_Sent from my Samsung SM-G920V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ImagicTheCat** [comment]
Always add details to issue ->
* what is working
* what is not working
* does the f5/f6 works ?

**Comment by jakepavek** [comment]
Notifications are working. Responding to them is buggy, either f5 and f6 don't work or it doesn't set coords or alert the caller.

_Sent from my Samsung SM-G920V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ImagicTheCat** [comment]
Please add more details when you have time to test it, this is not enough. Do the notification disappear when you press F5/F6, etc...

**Comment by jakepavek** [comment]
When they press f5 they don't get the call everytime

_Sent from my Samsung SM-G920V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jakepavek** [comment]
That's all I can really say tbh

_Sent from my Samsung SM-G920V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ImagicTheCat** [comment]
The call is only the gps position, only one can take it, what is displaying for the others ? "Already taken" ?

**Comment by ImagicTheCat** [comment]
Also, if you have only on error in your console, the issue is irrelevant.

**Comment by jakepavek** [comment]
Nope not console error and no it doesng say it was taken if someone already took it. It hides the notification but doesn't accept call or alert you its been taken


_Sent from my Samsung SM-G920V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ImagicTheCat** [comment]
You need to enable debug mode and save the output when the problem happen, so we can understand the problem.

**Comment by jakepavek** [comment]
Where is output it is enabled 

_Sent from my Samsung SM-G920V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jakepavek** [comment]
Call just bugged again I think it's when two people put a call in at same time

_Sent from my Samsung SM-G920V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jakepavek** [comment]
this issue only happens when someone is in a vehicle. I have narrowed down.

**Comment by jakepavek** [comment]
Magic the bug happens only when in vehicle if you get out you can accept it

_Sent from my Samsung SM-G920V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ImagicTheCat** [comment]
I don't get it, you "can" accept it ? You couldn't before ? Don't assume how the framework works, give details instead.

**Comment by jakepavek** [comment]
It won't let you interact with call until you get out of your vehicle

_Sent from my Samsung SM-G920V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jakepavek** [comment]
Understand?


_Sent from my Samsung SM-G920V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ImagicTheCat** [comment]
You assume again, do you mean, accepting the request, denying the request, receiving the gps position, receiving the notification (for the receiver, not the caller) ?

**Comment by jakepavek** [comment]
Receiver gets notification while in vehicle but can't press f5 or f6. Once receiver steps out of vehicle then they can press f5 or f6

_Sent from my Samsung SM-G920V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ImagicTheCat** [comment]
Okay, so nothing to do with server side stuff or call/service. It's about the request system. I have already taken call inside vehicle and ask I.D. to people while in vehicle, so it's not generalized. If all your players have the problem, something is wrong with your vRP version/configuration, or an addon is conflicting with vRP (disabling some controls while in vehicle). If only some of your players have the issue, then you need to compare their inputs configuration.

**Comment by jakepavek** [comment]
All services have the issue, test with a lot of people.

_Sent from my Samsung SM-G920V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jakepavek** [comment]
Tested with fresh download

_Sent from my Samsung SM-G920V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jakepavek** [comment]
Sometimes it works and sometimes it doesn't. Its just buggy with vehicle

_Sent from my Samsung SM-G920V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ImagicTheCat** [comment]
Maybe it's when you are pressing other keys ?

**Comment by jakepavek** [comment]
No when I get out of the vehicle I can accept or deny when I'm in I can interact with notification at all. Idk I can recreate the problem with you.

_Sent from my Samsung SM-G920V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ImagicTheCat** [comment]
Try to reproduce the bug on the test server.

**Comment by jakepavek** [comment]
Is it OK if I fill the server?

**Comment by ImagicTheCat** [comment]
It's here for testing, everyone can join.

**Comment by jakepavek** [comment]
ok so it seems that it just doesn't work with emergency vehicles. ai cars work.
