### ISSUE TITLE
Steam auth

### ISSUE THREAD

**Issue by jakepavek** [ImagicTheCat/vRP#167]
I don't think steam auth works with vRP in fivem's cit config file

http://imgur.com/a/Zldlf

_Sent from my Samsung SM-G920V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ImagicTheCat** [comment]
This is not related to vRP, how vRP could be able to disable the steam auth ? Maybe the FiveM get player name doesn't work for some players.

**Comment by jakepavek** [comment]
Idk all the other frameworks it worked. I'll tinker with it

_Sent from my Samsung SM-G920V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ImagicTheCat** [comment]
Did you try to teleport to them ? To see if they are ghost players ?

**Comment by jakepavek** [comment]
No let me try that

_Sent from my Samsung SM-G920V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
