### ISSUE TITLE
Mandatory set name?

### ISSUE THREAD

**Issue by jakepavek** [ImagicTheCat/vRP#168]
So you don't have a server that looks like this

http://imgur.com/a/Zldlf

_Sent from my Samsung SM-G920V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Geronimin** [comment]
i am this error

**Comment by CruelAlpha** [comment]
Yeah it would be great if you can make it so its mandotary to set a name!

**Comment by ImagicTheCat** [comment]
The steam name shouldn't matter in fact, only the id do.

**Comment by jakepavek** [comment]
I'm talking about so you don't have a lobby full of john smiths

_Sent from my Samsung SM-G920V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ImagicTheCat** [comment]
Oh, if that the thing that is bothering you, I always dreamed about creating a random name generator, brace yourselves.

**Comment by jakepavek** [comment]
Lol yes something like that

_Sent from my Samsung SM-G920V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ImagicTheCat** [comment]
Well, I could be more creative, but RP names are important.

**Comment by jakepavek** [comment]
I say you just force them to do it
