### ISSUE TITLE
Health dropping when not hungry and thirsty

### ISSUE THREAD

**Issue by jakepavek** [ImagicTheCat/vRP#169]
I had a full server today and everyone started dying from thirst or hunger even if they were drinking and eating 

was like shooting up then going back down then shooting back up again then you would die the whole prosess would take a couple of mins

_Sent from my Samsung SM-G920V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ImagicTheCat** [comment]
How that even possible ?

**Comment by CruelAlpha** [comment]
I've never encounted that, server is running strong for 2 days 👍

**Comment by jakepavek** [comment]
Screenshot

https://prnt.sc/fgqdsb

_Sent from my Samsung SM-G920V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ImagicTheCat** [comment]
There was a display issue, is health really dropping by thirst ?

**Comment by ImagicTheCat** [comment]
Any news ?

**Comment by jakepavek** [comment]
Still doing it after about a day the server being up
