### ISSUE TITLE
Idea: Phone!

### ISSUE THREAD

**Issue by Zuqaa** [ImagicTheCat/vRP#17]
I have a idea why not add a phone (comme sur FailyV) in the main menu)
And one thing pls :'( change the touch for open the main menu ... Car quand on monte vers le haut ou que l'ont veut voir la liste de joueurs le menu s'ouvre

**Comment by Zuqaa** [comment]
Pour le menu tu devrais mettre la touche F4

**Comment by Zuqaa** [comment]
Ensuite dans le tel tu met une option pour appeler/envoyer message evidemment il faudras avoir le numéro du mec qu'il t'auras donner au préalable et le numéro on pourrais le créer en meme temps que la carte d'identité au City Hall

**Comment by 3rg00** [comment]
Please, stop harassing him with your ideas... I think he already planned to do it, just let him time, he's actually doing and amazing job.

**Comment by Zuqaa** [comment]
:( i just suggest a good idea

I can posted my last idea ?? The Robberies :)

**Comment by ImagicTheCat** [comment]
* First, please use English, even roughly, use something like google translate.
* The phone is planned, I forgot to add it to the TODO list. 
* Keys for the phone menu are up to you (see the phone configuration of your game).

@3rg00: Thank you for your concern, there is a lot to do and I will take my time for each module.

**Comment by SnaiCrys** [comment]
Maybe we'll make our own Discord for such suggestions and general discussions...

**Comment by xchopin** [comment]
I think you don't understand the github community, if you have ideas just send a Pull Request.
