### ISSUE TITLE
[Request]Whitelist Cops?

### ISSUE THREAD

**Issue by CruelAlpha** [ImagicTheCat/vRP#170]
Hey Imagic! Love this VRP framework very much! i just have one request, which is if you can make it so that police is white listed. Maybe through the sql/config text file.
I know you are very busy haha! Let me know what you think!
Thanks!

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/pull/163

**Comment by CruelAlpha** [comment]
@ImagicTheCat Hi, Im quite new to lua coding, could you tell me where / how i set the permission? For example how would i make it so only players that are "Admin" can use the job police?
Appreciate your help very much!
-Cruel

**Comment by ImagicTheCat** [comment]
I'm sorry, but the issue section is not for help, I made myself clear about this everywhere now.
