### ISSUE TITLE
Maybe add animation to item transformers

### ISSUE THREAD

**Issue by jakepavek** [ImagicTheCat/vRP#171]
A seq of animations would be cool for item transformers

_Sent from my Samsung SM-G920V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ImagicTheCat** [comment]
Planned, just not writen on the todo list, will probably come with the job mission system.

**Comment by ImagicTheCat** [comment]
You can now use the item transformers callbacks for this.
