### ISSUE TITLE
Problem with start with Ubuntu 16

### ISSUE THREAD

**Issue by zek0** [ImagicTheCat/vRP#173]
Ubuntu 16, Mono 4.8, also try with clean instalation from master, same error.

![5988d303e9e94e33b664013e246c16e7](https://user-images.githubusercontent.com/6064653/26881002-9b5454fa-4baf-11e7-8fb5-25df6d65e899.png)

On windows 10 all work ok. 

Anyway thanks for great framework.

**Comment by remcotroost** [comment]
this is not an issue with the framework, this is an issue with your MySQL configuration. Either you have the old MySQL dll (the essential one) or you are not connecting to your mysql database correctly. Please close

**Comment by CruelAlpha** [comment]
I can confirm everything works on ubuntu

**Comment by SnaiCrys** [comment]
Ubuntu 16, Mono 4.8, all OK
