### ISSUE TITLE
Weapon save problem

### ISSUE THREAD

**Issue by SnaiCrys** [ImagicTheCat/vRP#175]
Weapon don't save after 0081d72c1e1f1f0efaa74a34de4578dc8d5b0845

**Comment by jakepavek** [comment]
Saves for me

_Sent from my Samsung SM-G920V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ImagicTheCat** [comment]
The joy of networked things and the intersection of events, fixed.
