### ISSUE TITLE
Cloakroom issue

### ISSUE THREAD

**Issue by jakepavek** [ImagicTheCat/vRP#176]
D's at you have 2 ped models

Ems paramedic_01
Police cop ped

If I dress ems, then dress as police it saves ems so when I undress at police I go back to ems if I undress at ems it stays ems. 

_Sent from my Samsung SM-G920V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jakepavek** [comment]
any word on this?

**Comment by HIsShadowONE** [comment]
ive noticed a LOT of servers are having problems with the ped systems currently it might be due to the updates in fivem causing conflicts with old scripts that use peds ( just a thought not sure) i havent checked to confirm

**Comment by ImagicTheCat** [comment]
Should be fixed, model and modelhash should work properly to dress and undress.
