### ISSUE TITLE
feature request : ability to add more PC's for police use

### ISSUE THREAD

**Issue by HIsShadowONE** [ImagicTheCat/vRP#177]
requesting addition cfg.pc locations so we can manually add coords to other pc desks at all relevant pd stations
coords for pd desks :
NW paleto sheriff - PC desk coords: -449.206726074219,6012.44482421875,31.7163906097412
LSPD PC desk downstairs vespucci coords: 459.775634765625,-989.494445800781,24.9148540496826
lspd vespucci upstairs office pc desk coords: 447.904266357422,-973.373596191406,30.6895904541016
lspd vesp upstairs main desk pc coords: 441.741271972656,-978.551513671875,30.6896057128906
OLD DEFAULT PC at Ncentral sheriff pd coords: 1853.21, 3689.51, 34.2671

**Comment by CruelAlpha** [comment]
It's quite easy to add more PC's, A request you should make is police computers inside a car.

**Comment by ImagicTheCat** [comment]
I will not add PC to car, the goal of a RP server is to have interactions, so you need to use your radio system to ask an agent at the PC some information.

**Comment by HIsShadowONE** [comment]
@CruelAlpha i wish it was easy i tried adding more pcs to the cfg.pc and found out from ImagicTheCat that it doesnt work that way (like adding more atms for example) and i would have to recreate the entire function of the pc for each one renaming it pc1 pc2 etc which is a lot of custom coding , if you know an easy way please share it rather then saying its easy and leaving it at that, were here to help each other to share code and make the framework more robust not mock those who cant figure things out as easily as others.

@ImagicTheCat as for pc in the car this would be proper RP cops do have access to the same system in cars as is at PD's - some of the functions like close business's etc but criminal records and things of this nature. but i do agree having it pc in station only encourages good interaction but would always require someone to be at the PD which limits their RP if they are just alone at PD waiting to access PC for other players.

**Comment by cammygames** [comment]
@HIsShadowONE https://hastebin.com/qezojoxumu.lua

**Comment by HIsShadowONE** [comment]
sorry just noticed the response to this , thanks a lot for trying to help but i have no idea how to use this lol , after replacing the local function with this ive tried inputting more pc coords to the police.lua in resources and get errors and vrp breaks. 
im pretty new to lua so without a put this here do this this way kinda instructions im just doing guess work till i find solutions that work then i know how and what i can do and where.
but thanks again for trying to help , any more info you could give on how to implement this would be greatly appreciated :D

**Comment by cammygames** [comment]
So my cfg.pc looks like this https://hastebin.com/qibexaxaqa.lua apart from that it should work.

**Comment by HIsShadowONE** [comment]
maybe its just me but that link is a blank page lol

**Comment by ENDrain** [comment]
[This patch](https://github.com/ImagicTheCat/vRP/compare/master...ENDrain:patch-2) should work.

**Comment by HIsShadowONE** [comment]
@cammygames im guna guess you havent tested this as it gives errors and is basicly what i said i tried in my original post and does not work but thank you for trying , if it works for you im curious how ...

@ENDrain this looks promising but again without an example shown of inputting extra pc's, this is guess work where your changes dictate putting the additional pc cords, (for me) through a process of trial and error as a lua noob. thank you for any additional help you can give.

**Comment by HIsShadowONE** [comment]
@ENDrain i think ive got it working thanks (after a couple of tries :) now i have to test if ive broken anything else with my implementation of this lol 
again thank you very much will report back if i find this has cause conflict elsewhere

**Comment by ENDrain** [comment]
The patch I gave link to, it contains a 'vrp/cfg/police.lua' file.  You should add new PCs coordinates like this:

cfg.pc = {
  {1853.21, 3689.51, 34.2671}, -- add comma after every coords BUT the last 
  {your_pc_x, your_pc_y, your_pc_z}
}

**Comment by HIsShadowONE** [comment]
thanks for giving example for others to use this is what i did and it worked for me , but i did need to edit the code you gave me since it was a bit diff from the updated files in vrp (just needed an extra end as i stated above and its located on diff lines possibly due to other additions i have made in the file or updates imagic has done with new commits)

**Comment by ImagicTheCat** [comment]
Added.
