### ISSUE TITLE
Menu Up Key Wrong Bindings

### ISSUE THREAD

**Issue by CruelAlpha** [ImagicTheCat/vRP#181]
Hello,
When you open up the menu with (UP key)
and use the menu, and if you want to go up an entry in the menu, it goes back and eventually closses the menu. Could you add in a hotfix for that? its quite annoying when you are trying to use the skin shop and the menu keeps popping up when you press the up key.
Thanks

**Comment by remcotroost** [comment]
The reason for this is that the menu uses the keybinding to open the phone. Bind that key in your GTA settings to something else (like L-Alt) and you won't have this issue.

**Comment by Aleweadan** [comment]
A disable function of key 27  when menu is open can be integrated let's see if Imagic want and have time for this.

**Comment by CruelAlpha** [comment]
Fixed!

**Comment by ImagicTheCat** [comment]
@Aleweadan I can't in fact, because nothing distinguish the main menu from other menus.

**Comment by Aleweadan** [comment]
Ah ok I did not see that like that. Sorry for having said anything then
