### ISSUE TITLE
Ability for police to escort players

### ISSUE THREAD

**Issue by SerpicoKG** [ImagicTheCat/vRP#182]
Having the ability to escort non compliant players.

**Comment by jakepavek** [comment]
I've done this, looks great on their screen but on the draggers it desyncs

**Comment by ImagicTheCat** [comment]
@CruelAlpha vRP will never be chat command based.

**Comment by jakepavek** [comment]
I added a drag option in menu. If you want I'll send u it, but like I said
for dragger it desyncs but the one being dragged looks good

**Comment by HIsShadowONE** [comment]
can you share your changes id like to see it in action and see if the desync is replicable then magic can decide if he wants to use it or do it on his own , thanks :D

**Comment by VortexRP** [comment]
Any update on this?
Love to get an escort script.

**Comment by ImagicTheCat** [comment]
An experimental drag feature is available in vrpex.
