### ISSUE TITLE
[Feature] vehicles inventory

### ISSUE THREAD

**Issue by T3rg0s** [ImagicTheCat/vRP#183]
Hello @ImagicTheCat, is it possible to put directly in the nearest owned vehicle's inventory harvested items? It's hard to implement if it doesn't exists? 
Thanks in advance

**Comment by ImagicTheCat** [comment]
I'm simulating things right now about harvest, gang weed operations, etc... It's not only hard to do, it's also not very interesting. Repeating the chest "put/get" can be a boring process, but it is exactly how it is working in real life, you need to carry things to your trunk. This is labor, I will not make the process of earning money easy. But maybe in a distant future, expansive machines to automate the process could exists.

**Comment by T3rg0s** [comment]
Okay, thanks for informations :). Good idea to choose expansives machines to automate the process.
