### ISSUE TITLE
Jobs stop working after sometime

### ISSUE THREAD

**Issue by jakepavek** [ImagicTheCat/vRP#184]
after time on the server jobs will stop working, it'll just say the action but won't give you anything and doesn't return empty.

**Comment by ImagicTheCat** [comment]
Errors in console ?

**Comment by jakepavek** [comment]
no errors that I see. just it works when I restart the server then after about a couple hours or so they stop working.

**Comment by ImagicTheCat** [comment]
possible duplicate https://github.com/ImagicTheCat/vRP/issues/121

**Comment by jakepavek** [comment]
yes could be, i'm sorry.
