### ISSUE TITLE
[Glitch] Ai Police after Actual Police?

### ISSUE THREAD

**Issue by CruelAlpha** [ImagicTheCat/vRP#186]
Hi,
Near the Police Precinct, if an rp police player shoots a citizen, the actual AI near the precinct starts shooting at the police. Is that supposed to happen?
Thanks

**Comment by ImagicTheCat** [comment]
Did you setCop() the players when in the group ?

**Comment by CruelAlpha** [comment]
This is what the groups for police looks like, i did edit it a bit. Let me know if this is wrong,
`  ["police"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onjoin = function(player) vRPclient.notify(player,{"Welcome to the Force Officer!"}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.notify(player,{"You are currently an officer on duty!"}) end,
      onleave = function(player) vRPclient.notify(player,{"Thanks for your Service!"}) end,
      onleave = function(player) vRPclient.setCop(player,{false}) end
    },`

**Comment by ImagicTheCat** [comment]
You define the same functions twice... I don't even know how you have no errors. The issue is not a help section, so I will close the issue. Knowledge of Lua is important to configure vRP.

**Comment by CruelAlpha** [comment]
I fixed it, anyone who is encountering something similar to this, instead of having multiple functions, make it all in one function for example: onjoin = function(player) vRPclient.setCop(player,{true}) vRPclient.notify(player,{"Welcome to the Force Officer!"}) end
