### ISSUE TITLE
vehicle menu doesn't work

### ISSUE THREAD

**Issue by jakepavek** [ImagicTheCat/vRP#187]
I get a error in getnearestowned vehicle client side.

**Comment by ImagicTheCat** [comment]
Useless bug report, please read the readme issues guidelines before submitting.

**Comment by jakepavek** [comment]
No its not, its cause you changed the getnearestowned vehicle.

**Comment by ImagicTheCat** [comment]
Commit ?

**Comment by jakepavek** [comment]
Put in vehicle

**Comment by ImagicTheCat** [comment]
Listen... You didn't even post the error, don't expect anything.

**Comment by jakepavek** [comment]
I fixed it myself was just letting you know. But OK.

**Comment by ImagicTheCat** [comment]
What is the solution ?

**Comment by jakepavek** [comment]
I just used getnearestvehicle rather then GetNearestOwnedVehicle

**Comment by ImagicTheCat** [comment]
I really don't know how you can have so much impossible issues... You didn't answered to the others issues when I asked you more data, and I'm really not the office of complaints, so please take your time to understand what you are doing, add details, or just stop submitting issues. The goal is to make vRP better, not to have a mess with some tape on it.

**Comment by NeFShARk** [comment]
@jakepavek 

I don't think that you are using the lasted version that tried to fix this issue as of commit [575d15b](https://github.com/ImagicTheCat/vRP/commit/575d15b001e3b3b9bed08fbc8945207f388b3e9f)

See - https://github.com/ImagicTheCat/vRP/blob/575d15b001e3b3b9bed08fbc8945207f388b3e9f/vrp/modules/police.lua#L176 and https://github.com/ImagicTheCat/vRP/blob/575d15b001e3b3b9bed08fbc8945207f388b3e9f/vrp/modules/police.lua#L205
