### ISSUE TITLE
Deleted weapon has my reconnection

### ISSUE THREAD

**Issue by Bandit33800** [ImagicTheCat/vRP#188]
hi,
If I buy a weapon and disconnect from the server
I lose my arms to reconnection
Each except for certain model that remains (exemple : pistol 50)

**Comment by ImagicTheCat** [comment]
It depends, not all weapons are registered, but most of them are. Your problem is probably that weapons/health/customization are only saved every 30 seconds right now.

**Comment by Bandit33800** [comment]
Ok thank you for the answer I will check the list of registered weapon
