### ISSUE TITLE
PROBLEM: Error message in console after Items Update

### ISSUE THREAD

**Issue by Zuqaa** [ImagicTheCat/vRP#19]
The message: http://prntscr.com/f4rxv0

**Comment by Zuqaa** [comment]
I just have translate the business.lua and the news items in basic_items...

**Comment by 3rg00** [comment]
You missed to replace anything. try to translate only the textinfo (shown ingame), for exemple: you can translate "Milk", not "milk".

**Comment by Zuqaa** [comment]
Hmmm ok yes my fault ^^ You can close the thread ? ^^

**Comment by ImagicTheCat** [comment]
Don't translate, and modify only the files in the cfg folder. 
If you modify the core files, you will not be able to update your vRP version without loosing all the modifications, leading to a mess. The cfg directory is the only one you should backup before updating vRP, and then fix some of the potential differences.

Translations will be provided soon by the lang module.

**Comment by Zuqaa** [comment]
Ok! If you not French i'm ok for translate the file lang.. :)
