### ISSUE TITLE
Feature request: Identity card

### ISSUE THREAD

**Issue by Aleweadan** [ImagicTheCat/vRP#190]
Hi, for a better RP can we make sure that the player can present his identity card with emote and the police officer would have a popup with the ID card. Because the for the blows it is as if the policeman serves in the pocket of the player.

**Comment by ImagicTheCat** [comment]
What is the problem with the actual way ?

**Comment by CruelAlpha** [comment]
@ImagicTheCat He wants an animation when you present the ID card, not sure if you have time to do that lol

**Comment by Aleweadan** [comment]
Closed.
