### ISSUE TITLE
Housing

### ISSUE THREAD

**Issue by jakepavek** [ImagicTheCat/vRP#193]
When trying to buzz someones house sometimes it puts you in the house by yourself and not with them.

**Comment by CruelAlpha** [comment]
This can't be right unless you edited something, i tested the housing system and it does fully work

**Comment by jakepavek** [comment]
Didn't edit anything try to get multiple people in your house not just one

**Comment by CruelAlpha** [comment]
I tried 4 people, that seemed to work. Does it bug out with more people?

**Comment by CruelAlpha** [comment]
yeah of coarse

**Comment by ImagicTheCat** [comment]
News ?
