### ISSUE TITLE
[Idea] Simple buzz sound when someone asks to get inside your house

### ISSUE THREAD

**Issue by TioSleepy** [ImagicTheCat/vRP#194]

**Comment by ImagicTheCat** [comment]
Do you know is there are a native buzz sound in gta ?

**Comment by TioSleepy** [comment]
I believe so, i heard it somewhere in online .

**Comment by HIsShadowONE** [comment]
theres an action sound script already for fivem that plays custom noises when actions/emotes etc occur

**Comment by ImagicTheCat** [comment]
If it comes to that, I could build a sound module using the tunnel system, but if there is a native sound, please search for it, you can use the admin menu to play custom sounds listed here https://wiki.gtanet.work/index.php?title=FrontEndSoundlist , until that moment, the only sound will be the sound of the notification.
