### ISSUE TITLE
Some car names don't load in garage

### ISSUE THREAD

**Issue by SergioGZ** [ImagicTheCat/vRP#195]
Hi. I've been replacing a lot of vehicles and adding them to garage.lua
Some names don't load in the garage.
[Pic](https://i.gyazo.com/feef924ac4d8de11764ca272beb018f8.png)

"XLS" should be "Jeep Cherokee"
"Furore GT" should be "Nissan 370Z"
[Pic](https://i.gyazo.com/aac946b750523f2cab904f1a51d666d4.png)

I think the problem could be cause they are dlc vehicles.
Sorry for my english I hope you understand me. My best regards

**Comment by SergioGZ** [comment]
I tried using the vehicles.meta of "mpexecutive" for xls. Still not working.

**Comment by jakepavek** [comment]
I'll help u bro, say it in discord cause we get in trouble for asking on
here lol

**Comment by SergioGZ** [comment]
Nah thank you dude but I think this could be an issue. DLC cars can't be named in garage. (I'm not sure tho).

**Comment by jakepavek** [comment]
They can be, this is a "help" post you'll see when it gets closed

**Comment by ImagicTheCat** [comment]
@jakepavek Exactly, this is not an issue related to the code of vRP, there is no way what you are talking about is possible, it's only a configuration problem, probably a duplication of keys. Use the FiveM topic for this kind of things.

**Comment by SergioGZ** [comment]
Alrigh I'll check that
