### ISSUE TITLE
[Feature Request] Handcuffed / Arrested People Cant Get out of Cars

### ISSUE THREAD

**Issue by CruelAlpha** [ImagicTheCat/vRP#196]
Hey,
I'm wondering in a later build, if you can add the ability to make arrested people not be able to get out of a car when they have been put in?
Let me know.
Thanks

**Comment by jakepavek** [comment]
Just disable the control and make a unseat function

**Comment by CruelAlpha** [comment]
@jakepavek Not experienced enough to do so, feel free to add a contribution if you want to help 👍

**Comment by ImagicTheCat** [comment]
Done.
