### ISSUE TITLE
How to Set Permission In Job Selector?

### ISSUE THREAD

**Issue by CruelAlpha** [ImagicTheCat/vRP#197]
Hi, i was wondering if you could let me know what format to set the permissions in for using 'Job Selector'
The docs don't explain which format it's required in, this is what i think:
  ["Job Selector"] = {
    _config = {x = -268.363739013672, y = -957.255126953125, z = 31.22313880920410, blipid = 351, blipcolor = 47, permission = 'admin'},
If this is wrong, let me know what format it's ment to be 👍

**Comment by SergioGZ** [comment]
If you want a job just for admin why don't you use the tool @Add group?

**Comment by ImagicTheCat** [comment]
The issue section is not a help section, please use the forum topic.

**Comment by jakepavek** [comment]
Make a help request seems people get their answers even if its not from
you. A lot of people need help that you don't provide. Let them ask
questions its brand new.

**Comment by ImagicTheCat** [comment]
The forum is here for this reason, this is the vRP project page, anything not related directly to the code of vRP is a lot of noise. I will not argue with people about that, it's easy to talk, not so easy to do things.

**Comment by CruelAlpha** [comment]
Thanks @sergio
