### ISSUE TITLE
[Idea] Show player names over head, only after they showed you their ID

### ISSUE THREAD

**Issue by TioSleepy** [ImagicTheCat/vRP#199]
I mean its like if you already know the person by the face, you would remmember their name .

**Comment by HIsShadowONE** [comment]
i kinda like that idea ... also an option for admins / superadmin to see all player names without requiring id (in case you need to identify someone to ban who hasnt showed you id)

**Comment by Armagryzor** [comment]
Answer here... is that i use on my server : https://forum.fivem.net/t/release-changed-player-name-tags-distance-names/19204/3

**Comment by HIsShadowONE** [comment]
that is neither exactly what were talking about or an answer to a feature request for this framework, but thanks.

**Comment by ImagicTheCat** [comment]
"I mean its like if you already know the person by the face, you would remmember their name ." 
So you can just remember their names, right ? I'm not interested in adding display for names, automating too many things is the best way to break RP interactions. After more testing, some admin tools may come up, but nothing related to RP.

**Comment by TioSleepy** [comment]
@ImagicTheCat  So you can just remember their names, right ? not if theres 10 persons using the same skin / aka police or jobs with models
