### ISSUE TITLE
Problem at the launch

### ISSUE THREAD

**Issue by Bookishi** [ImagicTheCat/vRP#2]
![2017-05-01 21_31_05-164 132 69 253 - connexion bureau a distance](https://cloud.githubusercontent.com/assets/27645538/25591603/855a1d4a-2eb5-11e7-875a-3875d99d1ba3.png)

**Comment by 3rg00** [comment]
Try to delete tables from your db vrp and launch again, tables will be correctly created.

**Comment by ImagicTheCat** [comment]
Tables are create with "if not exists", I think it's a conflict with another MySql.Data.dll version loaded.

**Comment by cjeje84** [comment]
Hello and thank you for gamemode but I have the same error

**Comment by ImagicTheCat** [comment]
Do you have another resource with a mysql system ?

**Comment by cjeje84** [comment]
Thanks

**Comment by ImagicTheCat** [comment]
Solved I think ? Would be great to have everyone loading the same .dll in the clr namespace.

**Comment by cjeje84** [comment]
Yes resolved I remove all other resource
