### ISSUE TITLE
Weird error

### ISSUE THREAD

**Issue by Disquse** [ImagicTheCat/vRP#200]
Hey, just downloaded your gamemode. After few minutes of game server throw an error. I'm doesn't change something in sources, just downloaded latest GitHub zip. Database is on my PC, MySQL 5.7
![image](https://user-images.githubusercontent.com/10367215/26999259-d5da73da-4d9d-11e7-9546-018a4f444f7c.png)
Any ideas how I can fix it? After this error server just doesn't work. Every action = error ("Error executing event handler for event ...") . Sorry for my english :)

**Comment by Disquse** [comment]
Huh, looks like I fixed this error by moving my database to VDS. 
Also I have another problem. When I open menu by pressing "UP" I can move selector down, but can't move up, menu re-opening when I press "Up". How can I fix it? Maybe re-bind menu to other button?

**Comment by ImagicTheCat** [comment]
The issue section is not a help section, read the issues guidelines.
