### ISSUE TITLE
[IDEA] Prison timer

### ISSUE THREAD

**Issue by TioSleepy** [ImagicTheCat/vRP#205]
Make so cops can set how much time people stay in jail, also make them come back to jail if they force quit the server before the time .

**Comment by HIsShadowONE** [comment]
Yes please ! also a timer display for the player in jail so they know when they will be released.

**Comment by HIsShadowONE** [comment]
also auto release from prison/jails when time has been served like how most servers do it would be greatly appreciated!

**Comment by TioSleepy** [comment]
@ImagicTheCat planned or nah ?

**Comment by VortexRP** [comment]
Bump. 
+1

**Comment by ImagicTheCat** [comment]
You don't need to up a feature or an issue, it's not like a forum.

**Comment by WingedHussarr** [comment]
This is needed for RP server TBH. And also it's useful to make the state prison useful so you can put people in there and so theres also something that prevents peopel from just walking out of there.

**Comment by ImagicTheCat** [comment]
After a lot of thinking, I disapprove this feature. Nothing stop people from disconnecting as soon as they are caught by the police, before even receiving a fine, so this is not a solution. Also, by experience on other games with automated prisons, this push people to abuse or lose the RP goal of the prison feature. It's not about a real hard coded punishment, but a way to have some RP interactions, so it's better to have the police officers putting AND getting out of prison players when they think it is enough. It's the police responsibility to take care of the prisoners.

If you disagree with this, it should not be so difficult to create a vRP extension doing what you want, using the jail API functions.
