### ISSUE TITLE
Losing superadmin rank on join

### ISSUE THREAD

**Issue by ImagicTheCat** [ImagicTheCat/vRP#206]

**Comment by VortexRP** [comment]
I get this too sometimes but it's because of it not capturing your steam id and using your IP as an identifier. 

That's my theory though.

**Comment by ImagicTheCat** [comment]
Of course, if you have another id, the issue is an identification problem, but in this case, it's the same identification, with the rank being lost.

**Comment by ImagicTheCat** [comment]
Should be fixed.
