### ISSUE TITLE
Help with Tunnel.lua

### ISSUE THREAD

**Issue by Oskaria** [ImagicTheCat/vRP#207]
Hi!)
I'm trying to add a driving school to the server, to get a driver's lice and worken everything, except - adding a license to the player.
I decided to make licenses through groups, created it in cfg/groups.lua and it turned out to make a license check through a query in MySQL, but I can not add a group to the user.

Can you give an example of using Tunnel.lua in external scripts to add a group to the user? This example will allow me to understand how everything works, and this will make me happy))

**Comment by ImagicTheCat** [comment]
Use the FiveM topic to get help, issues are not for help but bug reports.
