### ISSUE TITLE
[Feature] Emergency Liverys

### ISSUE THREAD

**Issue by zek0** [ImagicTheCat/vRP#210]
It will be great to add SetVehicleExtra for emergency vehicles.

Thanks for you...

**Comment by ImagicTheCat** [comment]
Are you talking about customization ?

**Comment by zek0** [comment]
Nope. Example: Maverick helicopter "polmav" has 2 liverys police and emergency, and if i spawn now the livery spawned random. Will be great about second parameter ex: polmav,2 or something.

Thank you.

**Comment by ImagicTheCat** [comment]
To me it's a customization thing, no idea right now except re-spawning it many times until you have what you want.

**Comment by ImagicTheCat** [comment]
Livery customization is now supported by the vehicle state, but you need to use something else to modify it.
