### ISSUE TITLE
Handcuff bugs

### ISSUE THREAD

**Issue by zek0** [ImagicTheCat/vRP#211]
If you handcuffed you may:
- Sit in car and drive, but dont able to exit from car
- If you arested with weapon and handcuffed you may shoot without problem
- pills may ressurect from coma

Thank you...

**Comment by ImagicTheCat** [comment]
You can't drive, unless your are handcuffed while driving. Will fix the weapon issue.
Pills shouldn't be accessed while in coma, the menu is disabled, but feel free to modify the pill item to check the coma -> doc.
