### ISSUE TITLE
[feature] Mecanic can open cars / Lock unlock cars

### ISSUE THREAD

**Issue by TioSleepy** [ImagicTheCat/vRP#212]
Make so mecanics / repairman can unlock any car with the blowtorch .
Also add so you can lock/unlock your car .

**Comment by HIsShadowONE** [comment]
theres a lockpick item on other servers that would serve this purpose better then a blowtorch

**Comment by ImagicTheCat** [comment]
No lockpick planned, but can be a nice feature to steal cars.
