### ISSUE TITLE
[Feature Request] Prevent Military and helicopter spawns

### ISSUE THREAD

**Issue by VortexRP** [ImagicTheCat/vRP#213]
It would be amazing to have an option to prevent military and helicopter spawns built in.

**Comment by HIsShadowONE** [comment]
this is very non essential (doubt itl get high priority unless its very simple to do) but would be awesome for rp , could also add it to the clubs that dont have default music and someone could rp as the DJ.

**Comment by HIsShadowONE** [comment]
yea this is needed i know i saw on another server that they just have a block on them to get in but they still spawn

**Comment by VortexRP** [comment]
I've looked into that solution myself and all it does is check if you're in it and delete if used.

**Comment by HIsShadowONE** [comment]
no ive seen a server that if you try to get in a text pops up on the screen that you cant do that and thats it. they are there always but never enterable.

**Comment by ImagicTheCat** [comment]
Not planned, vRP doesn't aim to implement everything (it's not a collection of script), but only what is required for the RP. I don't think flying things are too much invasive.
