### ISSUE TITLE
[Feature] Home radios

### ISSUE THREAD

**Issue by TioSleepy** [ImagicTheCat/vRP#214]
Make a radio that plays songs from the defaut gtav radios on houses (Like background music for houses)

**Comment by HIsShadowONE** [comment]
this is very non essential (doubt itl get high priority unless its very simple to do) but would be awesome for rp , could also add it to the clubs that dont have default music and someone could rp as the DJ.

**Comment by ImagicTheCat** [comment]
Well, not exactly as requested, but it's done. https://github.com/ImagicTheCat/vRP/commit/0bc6a0f28ce87068e5c142dd1ddd497a5529f569
