### ISSUE TITLE
Feature request price for gas

### ISSUE THREAD

**Issue by jakepavek** [ImagicTheCat/vRP#215]
Price for frfuel. It was done in Essential I'm just not use to your framework and money you could prolly do this in a jiffy

_Sent from my Samsung SM-G920V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ImagicTheCat** [comment]
vRP will not adapt itself to other scripts, other scripts must expose a way to use the vRP functions (using events for money things, or anything).

**Comment by jakepavek** [comment]
Their is they have server events you can call. Fueladded then u use your
code to make it take money

**Comment by ImagicTheCat** [comment]
Then do it, create a vrp_mod resource listening to those events and using the vRP API. Again this is not a help section.

**Comment by jakepavek** [comment]
Honesty fuck you, tango down your test server.

**Comment by T3rg0s** [comment]
Honestly, fuck yourself, jakepavek -> Zuuqa / Lorenzo

**Comment by ImagicTheCat** [comment]
Please do not respond @T3rg0s, or you will be banned too (by me or github).
I don't care if people can't understand simple rules, they just have nothing to do on GitHub in the first place.

**Comment by T3rg0s** [comment]
Yep @ImagicTheCat , its corrected ;).
