### ISSUE TITLE
feature request: robberies

### ISSUE THREAD

**Issue by HIsShadowONE** [ImagicTheCat/vRP#218]
desperately need things for criminals to do , so people can RP as criminals and cops have something to do beyond traffic and incidents , ability to rob banks , jewelry store and other possible locations stores etc (allow customization for what places can be robbed , how long it takes , money taken in , gives functions to using dirty money and laundering through businesses)

**Comment by chubbynugly** [comment]
I second this.

**Comment by CruelAlpha** [comment]
This feature would be quite good too!

**Comment by Dimmies** [comment]
+1

**Comment by T3rg0s** [comment]
Maybe you can do it yourself as an additional module. It's not really hard to do it. 

_Sent from my HUAWEI EVA-L09 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ImagicTheCat** [comment]
You can do a simple robbery using item transformers and use in the step callback vRP.applyWantedLevel to make them wanted while "harvesting" the money. If you want something advanced, a new resource using the vRP API should be created, a robbery system is too specific to be implemented in the core of vRP.
