### ISSUE TITLE
Scalable hunger/thirst GUI

### ISSUE THREAD

**Issue by TioSleepy** [ImagicTheCat/vRP#222]
Title

If you change resolutions the Gui for hunger/thirst goes to weird places .

**Comment by VortexRP** [comment]
Yeah this can be an issue for anyone who isnt using a 1080p monitor.  It shows up off to the right.

**Comment by HIsShadowONE** [comment]
larger then 1080p and it cuts into the map too had some testers tell me this today , i think the best place would be to anchor it below where the life/armour bars are as they are anchored to the bottom of the map which is the same for everyone

**Comment by ImagicTheCat** [comment]
cfg/gui.lua until a better solution is found.

**Comment by TioSleepy** [comment]
@ImagicTheCat  take a look in the hunger/thirst mod in fivem forums, the gui is scalable. Maybe you can check their code for advisal
