### ISSUE TITLE
[Future] Add body armor

### ISSUE THREAD

**Issue by zek0** [ImagicTheCat/vRP#225]
It is possible in future add body armor? it will be great for police

Thanks for you...

**Comment by HIsShadowONE** [comment]
i was hoping for this also , perhaps with a loadout selector like how cloakrooms work , theres a room for getting guns in the lspd that could have a marker for police to acquire a loadout with armour

**Comment by VortexRP** [comment]
Support. AddArmor and RemoveArmor sounds great for cloak and for shops.

**Comment by Bandit33800** [comment]
Hello,
Here are the natives for

static void ADD_ARMOUR_TO_PED(Ped PedHandle, int Amount) { invoke<Void>(0xF686B26E, PedHandle, Amount); } // 0xF686B26E

static int GET_PED_ARMOUR(Ped PedHandle) { return invoke<int>(0x2CE311A7, PedHandle); } // 0x2CE311A7

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/commit/edebc355729cb7e3d9d3394cf1aef60f5dd48c79
