### ISSUE TITLE
Add Identity Info to License Item

### ISSUE THREAD

**Issue by Dimmies** [ImagicTheCat/vRP#227]
I've created an License item which is given to a player who completes a drivers test.

I was wondering if there is any way to add the identity information (Name, Home etc) to the License Item Description so when the Item is given to a cop they can view the information at will?

I'd love some help on figuring this out, thanks!

Heres what I'm using to create the item:
`items["license"] = {"Drivers License","You must have this in order to drive legally!",{},0.5}`

**Comment by ImagicTheCat** [comment]
Wait for the parametric item feature.
