### ISSUE TITLE
[Feature Req] Vehicle check and animation on transformers

### ISSUE THREAD

**Issue by VortexRP** [ImagicTheCat/vRP#229]
I would love to see a vehicle check to make sure they are not in the vehicle when using transformers.
I would also love to see an animation for somewhat of immersion when using this feature.

**Comment by ImagicTheCat** [comment]
Duplicate https://github.com/ImagicTheCat/vRP/issues/171 , the problem with checks and animations is that people needs some freedom while harvesting or processing, because it can be very long. They need to play emotes, discuss, etc... So it's something I am thinking about.

**Comment by VortexRP** [comment]
I'm no professional but could you bind it to a button like E and press it again to cancel the process and animation?

**Comment by ImagicTheCat** [comment]
You can now use the item transformers callback to play animations. No custom checks planned for now.
