### ISSUE TITLE
GUI Menu onback ? 

### ISSUE THREAD

**Issue by ARL64** [ImagicTheCat/vRP#231]
Impossible to add more than 1 submenu to a menu and have a proper back to the last menu with onclose because when open a submenu in a menu onclose is called and then if you want to open a submenu it the menu you specified in the onclose function. Don't know if what I said is very clear. If so I'll explain in an other way.

**Comment by ImagicTheCat** [comment]
Yes, the menu system is not perfect, you should not abuse of nested menus.
