### ISSUE TITLE
feature request: multiple character support

### ISSUE THREAD

**Issue by HIsShadowONE** [ImagicTheCat/vRP#233]
many people like to play with multiple characters to have different avenues of roleplay ( i myself want to be a cop and a criminal on my server, roleplay wise using the same character would be impossible) and require two diff separate characters, requesting the ability to store more then one character and swap between them on login, to allow players to experience all aspects of the server and not betray an established character.
thank you in advance as always !

**Comment by VortexRP** [comment]
Can you not just change identities?

**Comment by HIsShadowONE** [comment]
no. that is not an ooc way of changing your character that is an IC way of changing your name , you would loose your old character and it defeats the purpose of what im asking for here.

**Comment by T3rg0s** [comment]
https://github.com/ImagicTheCat/vRP/issues/39

_Sent from my HUAWEI EVA-L09 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
