### ISSUE TITLE
[idea] Garage esx

### ISSUE THREAD

**Issue by cedricalpatch** [ImagicTheCat/vRP#234]
Hello Imagic

You think is possible you add one resouce like mission resource with esx_garage?

[https://www.mediafire.com/?f8uuie5obx7pf2s](url)

Thanks
Cedric RPF Studio

**Comment by ImagicTheCat** [comment]
I don't understand.

**Comment by cedricalpatch** [comment]
Do you think its possible to add the possibility to use garage from another gamemode like esx_garage , its really interesting to have a place to get save modifications off the vehicle
?

**Comment by ImagicTheCat** [comment]
I have no idea, try.
