### ISSUE TITLE
MySQL:getResults ?! How to ?

### ISSUE THREAD

**Issue by RyUkApples** [ImagicTheCat/vRP#235]
Hi what is the equivalent of MySQL:getResults in your version of MySQL.lua ?

**Comment by ImagicTheCat** [comment]
This is not a help section, use the forum topic.

**Comment by RyUkApples** [comment]
Its just a question not a help request O_o i make a addon (pet shop) for the community FiveM...

**Comment by RyUkApples** [comment]
But its good now i found the code.. tsss

**Comment by ImagicTheCat** [comment]
Issues are for issues and features, I will not allow something else here.
In the same time, help/discussions should be done on a forum so that everyone with the same problem will be able to have the solution by using the research tool. If you can't respect that, you will be banned from the issues.
