### ISSUE TITLE
 How to configure gui to a specific screen resolution?

### ISSUE THREAD

**Issue by JosGoLon** [ImagicTheCat/vRP#236]
How to configure gui to a specific screen resolution?

**Comment by ENDrain** [comment]
Which parts of gui do you need to configure specifically?

**Comment by VortexRP** [comment]
I imagine he meant the survival GUI as it's unaligned from the map if it isn't in 1920x1024

**Comment by VortexRP** [comment]
1080*

**Comment by tabarra** [comment]
Could putting the hunger/thirst bars in the bottom right of the screen alongside the roles be a possible solution for the problem?  
In this case it might require a redesign of the roles as well.  
  
Let me know what you guys think and I can probably try something here.  
(also related to #222)

**Comment by ImagicTheCat** [comment]
If the solution about https://github.com/ImagicTheCat/vRP/issues/557 is not enough, now the anchor can be changed (ex: `botright`).

**Comment by ImagicTheCat** [comment]
Kind of deprecated, survivals display can be re-implemented by extensions.
