### ISSUE TITLE
Players crash/timeout (stream-hydrogen-virginia) after weird host election

### ISSUE THREAD

**Issue by NoxOverFlow** [ImagicTheCat/vRP#239]
When my server is open, at any time with any number of players connected, it can happen that an "host election" (wtf) is started, clients apparently ping each other and an ID among those is selected to be the host. And after that, 4/5 players always freeze for a moment and crash seconds after, returning an error called "stream-hydrogen-virginia" (wtf^2).

I have tried anything, from disabling SteamAuth to disabling the mods stream folder.

I will send the log file with debug on to ImagicTheCat and those who are interested by private message.

**Comment by VortexRP** [comment]
Interested. I had a lot of these issues but since switching hosts and upgrading to the latest windows server OS I haven't had an issue. For sure send me that log and I'll look at it.

**Comment by Armagryzor** [comment]
Me too,  yesterday I had the same problem Just after install the last update. With 5 or 24 players a lot of players time out with same crash ..virginie stream etc etc.. I M with Windows server 2012 and a stronger hardware

**Comment by ImagicTheCat** [comment]
It's probably unrelated to vRP but try to enable the vehicle migration.

**Comment by NoxOverFlow** [comment]
Vehicle migration enabled, still happens.

Host election, then a bunch of random people crash.

**Comment by NoxOverFlow** [comment]
Vehicle migration enabled, still happens.

Host election, then a bunch of random people crash.

**Comment by NoxOverFlow** [comment]
Please, I need to resolve this bug as quickly as possible, there are people that want to play on my server without crashing...

**Comment by CruelAlpha** [comment]
doubt this has anything to do with vrp, im running latest build fine atm

**Comment by NoxOverFlow** [comment]
Alright. Trying to change server OS right now.

**Comment by CruelAlpha** [comment]
@NoxOverFlow What os are you running? Im using ubuntu

**Comment by NoxOverFlow** [comment]
Ubuntu 16.04, after some time the server is online a bunch of people keep crashing with the same error (stream-hydrogen-virginia) after the host election happens and is apparently won by somebody.
I didn't try running the server on Debian, since I am currently installing mono 4.8 on it.

**Comment by VortexRP** [comment]
I think the host voting is just associated with people timing out from the server. I don't think its directly related to your issue. Even I get that when someone times out on my server.

**Comment by NoxOverFlow** [comment]
Ok, found what the problem is, gonna open another issue.

**Comment by ImagicTheCat** [comment]
@Armagryzor rollback to previous versions to see if it's a vRP issue or a not related one.

**Comment by Armagryzor** [comment]
Hi ImagicTheCat,  I will let you know this week-end when Ïm will be back

**Comment by ImagicTheCat** [comment]
Any news ?

**Comment by Armagryzor** [comment]
With old version. . No problem. .but with the last version I have a lot of players time out

**Comment by JosGoLon** [comment]
https://ibb.co/c2x9V5 - 1
https://ibb.co/dMtKDQ - 2
https://ibb.co/gcm6tQ - 3
https://ibb.co/bxqo7k - 4
Maybe it will help you, everything crashes after the update
