### ISSUE TITLE
[Feature Request] Personal Yachts 

### ISSUE THREAD

**Issue by CruelAlpha** [ImagicTheCat/vRP#241]
Hello!
I was wondering if it was at all possible to implement personal yachts? This would be a great and unique feature to Vrp if it was possible, i'd imagine alot of work to go into this.
Thanks,

**Comment by ImagicTheCat** [comment]
What do you mean ?

**Comment by Dokman** [comment]
Buy a yacht like the O****

**Comment by CruelAlpha** [comment]
For example, in  gta online you can purchase your own yacht (ship/cruise) and set that as your home, would be great if we could implement something like this

**Comment by ImagicTheCat** [comment]
Some people used the home system for that I think, by creating a new slot type.
