### ISSUE TITLE
Issues PlayerConnecting 

### ISSUE THREAD

**Issue by RyUkApples** [ImagicTheCat/vRP#242]
I have an error (that I did not have before) here is the screen: http://prntscr.com/fm1qeq and has the line 346:             if type(data) == "table" then vRP.user_tables[user_id] = data end
and at the line 128: local id = q_create_user:last_insert_id()

**Comment by VortexRP** [comment]
Does your SQL user have all access?

**Comment by RyUkApples** [comment]
yes

**Comment by RyUkApples** [comment]
Resolved.

**Comment by ImagicTheCat** [comment]
Solution ?

**Comment by RyUkApples** [comment]
I dont know how explain this in english its so complex x)

En faite ma BDD que j'avais qui marchais pas venait de mon ancien serveur donc je devais l'importer et a l'importation une case appelé "Ne pas utiliser AUTO-INCREMENT pour la valeur ZERO" je l'ai alors décoché car elle enlever les key PRIMARY et les valeur a zero elle les transformer en NULL donc je l'ai décoché et ça fonctionnait.. Donc j'me disais si tu pourrais mettre ce message dans le readme pour dire au gens qui importe le sql de ne pas cocher la case ^^
