### ISSUE TITLE
Reduce queries to database (Frame tick warning)

### ISSUE THREAD

**Issue by NoxOverFlow** [ImagicTheCat/vRP#243]
People in my server keep crashing because of the fact that, as I saw in debug mode, vRP keeps spamming the MySQL DB with queries, something like 10 in a second! 

I have put "save interval" to 180 seconds but it didn't change anything! 

How can I reduce queries impact?

**Comment by ImagicTheCat** [comment]
Debug mode will tell you the time for save datatable, start to give that. The other instantaneous queries are probably related to money and business, please list some of the "spammed" queries here.
