### ISSUE TITLE
[Feature] Get Personal Vehicle

### ISSUE THREAD

**Issue by RyUkApples** [ImagicTheCat/vRP#245]
Its possible to make a command vRP.GetPersonalVehicle ^^ ?

**Comment by VortexRP** [comment]
You could add the garage to the main menu if you wanted to. :p

**Comment by RyUkApples** [comment]
No u dont understand... Get personal vehicle is for a action TaskEnterVehicle(ped, vehicle, 0, 0, 0)
And for "vehicle" the vRP.GetPersonalVehicle is needed .. u understand ?

**Comment by RyUkApples** [comment]
same as vRP.GetBankMoney or GetMoney..

**Comment by ImagicTheCat** [comment]
Now you have access to the vehicle handle, look at how the vehicles are managed in `client/basic_garage.lua`. Not documented.
