### ISSUE TITLE
[Problem] "Wanted" in my car

### ISSUE THREAD

**Issue by SnaiCrys** [ImagicTheCat/vRP#247]
I locked my vehicle, walked away from it (about 500 meters) and returned. When I try to sit in the car after these actions I catch stars.

**Comment by ImagicTheCat** [comment]
Have you tried to open the trunk, and it wasn't working ? If yes, try to disable vehicle migration.

**Comment by SnaiCrys** [comment]
I tested with cfg.vehicle_migration = false and cfg.vehicle_migration = true.
Player1 spawned his vehicle from garage. Player2 took vehicle and drove away. After 900+ meters vehicle lost its owner and Player1 could spawn another vehicle.

**Comment by ImagicTheCat** [comment]
So the migration is still happening... no idea how to handle this.

**Comment by ImagicTheCat** [comment]
Obsolete.
