### ISSUE TITLE
[Feature] More Options in SkinShop

### ISSUE THREAD

**Issue by RyUkApples** [ImagicTheCat/vRP#250]
Add option for bag (it is a problem for my players.. he have a bag with the cloakrooms but i dont can remove the bag in skinshop) and others. I have an other idea.. Remake entierely the Skinshop and make a skinshop similar to GTA ONLINE

**Comment by ImagicTheCat** [comment]
Skinshops are configurables and can use any Ped part or Ped prop, if you know the index. Bags are probably on a specific index, so add it.

**Comment by RyUkApples** [comment]
Ok thx ^^ U have a link for the list of index ? :)

**Comment by ImagicTheCat** [comment]
Just use lambda menu, indexes should match for ped parts, not for props. For props, add them, and look at your customization using the admin function to know the index.
