### ISSUE TITLE
[ISSUE] Infinite Loading + now wont load at all

### ISSUE THREAD

**Issue by schoolboyqx** [ImagicTheCat/vRP#251]
Fresh server, vrp in resources, - vrp added to citmap, config set to database couchDB database, first it was infinite loading now it wont load at all.

**Comment by RyUkApples** [comment]
See the other issue... Its a problem with ur default gamemode. ex : (fivem, fivem_skater_map)

**Comment by UtraTM** [comment]
which map we should take to test?

i cannot press anything in the beginning menus where i can create an identity. 

also Arrow up showes me the scoreboard instead of the phone

**Comment by VortexRP** [comment]
because it doesn't use couchdb. it uses mysql.

**Comment by ImagicTheCat** [comment]
No support is allowed in the issues, only bug reports and feature suggestions. Use the forum topic to get help.
