### ISSUE TITLE
vRP:playerJoinGroup  O_o

### ISSUE THREAD

**Issue by RyUkApples** [ImagicTheCat/vRP#252]
Screen : http://prntscr.com/fnulp0

Where are register the event vRP:playerJoinGroup (see the screenshot)

**Comment by ImagicTheCat** [comment]
???

**Comment by RyUkApples** [comment]
See the screenshot.. In the readme u have add a event vRP:playerJoinGroup but this event is not registered with RegisterServerEvent etc..

**Comment by ImagicTheCat** [comment]
Register is only for net events.
