### ISSUE TITLE
Feature Request:  Phone binds

### ISSUE THREAD

**Issue by MissBehavin** [ImagicTheCat/vRP#258]
Please make a keybind config option for the "menu" other than up arrow.  It conflicts with navigating the menu.  It would be nice if I could set a different key such as "E" and have it be on keydown and close when key is released.  Is this possible?

**Comment by Drakma** [comment]
Remap your controls in the game.  You are looking for the Phone key.

**Comment by Bandit33800** [comment]
Hi,
If I have a good memory
vrp/cfg/client.lua

**Comment by Arma** [comment]
Hey K ;) as Bandit said above in that file change "open = {3,27} -- INPUT_PHONE, open general menu" to "open = {3,38} -- INPUT_PHONE, open general menu"

**Comment by ImagicTheCat** [comment]
This is not an help section, use the FiveM topic.
