### ISSUE TITLE
error proxy call vrp:getinventoryitemdefinitions not found

### ISSUE THREAD

**Issue by HIsShadowONE** [ImagicTheCat/vRP#261]
![vrp getinventorydefinitions error](https://user-images.githubusercontent.com/7647982/27535082-852291b2-5a26-11e7-9bd0-eb3067310b22.png)
 got this after updating to new version

**Comment by Arma** [comment]
We are all getting that atm... I think its just one line somewhere that has not been changed to the new function.

**Comment by ImagicTheCat** [comment]
Not an issue, you should not update vRP when not required unless you know what you are doing.
