### ISSUE TITLE
[Features] Skinshop advanced (barber/Eyes/makup)

### ISSUE THREAD

**Issue by T3rg0s** [ImagicTheCat/vRP#265]
For to use index about beardcut/eyes, we need  to use SetPedHeadOverlay native (currently not implemented in the skinshop).
Is it possible to implement it?

For beard:
- SetPedHeadOverlay - index 1
- SetPedHeadOverlayColor - index 1

For EyeColor:
- SetPedHeadOverlay - index 2
- SetPedHeadOverlayColor - index 2

For Makeup:
- SetPedHeadOverlay - index 4
- SetPedHeadOverlayColor - index 4

For LipStick:
- SetPedHeadOverlay - index 8

There is also native "SetPedFaceFeature"

Thanks a lot :)

**Comment by Aleweadan** [comment]
SetPedHeadBlendData is needed to do that take a look at https://github.com/Sighmir/vrp_barbershop. ImagicTheCat can you add barbershop please ?

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/commit/e5e9749f055b57081ec97ff645673086ed53b450

**Comment by Aleweadan** [comment]
Awesome thanks!
