### ISSUE TITLE
[Feature] Robberies

### ISSUE THREAD

**Issue by WingedHussarr** [ImagicTheCat/vRP#266]
I feel this is essential in RP especially when it comes to criminals. Add a function that can be edited via cfg where we can add locations that can be robbed if a user is within that small area. I feel this would work similar to a item transformer however I feel it needs more work such as a announcement to every player to notify of the robberies (maybe a possible twitter feature? XD). It should have a countdown to when the money is obtained or an item (Like people can rob a store for money and like a lab for materials such as uranium idk). I feel like there should be a red marker that the user needs to step on and select on the menu if they want to rob the store and they then need to stay within the area until the time counts down to 0.

**Comment by ImagicTheCat** [comment]
This should be a vRP extension, not in the core of vRP, it's too specific.
