### ISSUE TITLE
[Feature] Per recipe permissions

### ISSUE THREAD

**Issue by TioSleepy** [ImagicTheCat/vRP#267]
Like a restaurant transformer could have 5 recipes for normal people, but 10 for people with the "chef" permission .

Ive permissions (aptitude) on recipes but only the first permission applies to all recipes .

**Comment by ImagicTheCat** [comment]
Permissions are not per recipes for now, only per transformer.

**Comment by TioSleepy** [comment]
Thats what im suggesting, did you understand my example ?

**Comment by ImagicTheCat** [comment]
Was just rectifying because you assumed that the list of permissions has anything to do with the recipes.

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/commit/536052eb0f942c66df82d758026af9d1380a0192
