### ISSUE TITLE
[ISSUE] Skinshops not working now anymore

### ISSUE THREAD

**Issue by UtraTM** [ImagicTheCat/vRP#268]
Hello,

skinshops throws exeptions now. Can you please fix it?
Thank you :)

**Comment by ImagicTheCat** [comment]
At least, add the exceptions.

**Comment by UtraTM** [comment]
http://prntscr.com/fow3oj

**Comment by SnaiCrys** [comment]
I have no such problem.

**Comment by VortexRP** [comment]
.

**Comment by UtraTM** [comment]
i installed all fresh and cant choose something on the store without getting execptions
