### ISSUE TITLE
police ask id permisson nested menu changes

### ISSUE THREAD

**Issue by HIsShadowONE** [ImagicTheCat/vRP#271]
the new way you have nested the police menu now provides all players with a police menu option to use the ask id function which is confusing for some players wondering why they are not police but have a police option in their menu with that single option , is there a way to clone this in a commit to have it its own option for anyone not a police job. thanks

**Comment by VortexRP** [comment]
police.askid not work? Remove from user group and add to the police group?

**Comment by HIsShadowONE** [comment]
the option works fine the point is every player now has a police option in the menu to use the ask id function since it was not cloned to be used by civilians , it is confusing for players who are not police to have a police option to ask for id

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/commit/3d0e9b8d26b8aacee7e27193fff6787bb4bf4441
