### ISSUE TITLE
[Features] Player stock own shop

### ISSUE THREAD

**Issue by zek0** [ImagicTheCat/vRP#273]
It will be great if player may stock own shop. 
Example: player have end product "wine" , player have point of stock own shop with this product and other players may buy products from player shop.

Thank you.

**Comment by Bandit33800** [comment]
Hi

Has you mounted your idea with a little imagination nothing to complicate

**Comment by ImagicTheCat** [comment]
Not interesting for the core of vRP, it adds little RP interactions.
