### ISSUE TITLE
[bug]Using emotes in car.

### ISSUE THREAD

**Issue by VortexRP** [ImagicTheCat/vRP#274]
Using some emotes in a vehicle clips you through the street thus pushing you through and because of that it indefinitely tries to teleport you back above the floor.

Maybe add a vehicle check. If they're in a vehicle disable emote section. 
I would happily do this but my lua knowledge is limited.

**Comment by SnaiCrys** [comment]
`  local pedTemp = GetPlayerPed(-1)
  if not IsPedSittingInAnyVehicle(pedTemp) then`
in client/base.lua tvRP.playAnim

**Comment by Aleweadan** [comment]
Don't work for me with the FXServer version.

**Comment by ImagicTheCat** [comment]
This is now possible in the vrpex branch: https://github.com/ImagicTheCat/vRP/tree/vrpex#special-function-permission
