### ISSUE TITLE
[Bug] give and throw weapon

### ISSUE THREAD

**Issue by Bandit33800** [ImagicTheCat/vRP#276]
hi,

The option to equip the weapon is good
I noticed
Giving or throwing(do not work)
We do not see the amount of restraint displayed next to the maximum = 0
As if the inventory is empty not weapon
You can see them in inventory weapons

error message : Invalid value

**Comment by ImagicTheCat** [comment]
Still happening ?

**Comment by hartturmch** [comment]
when i equip a weapon it desapears
