### ISSUE TITLE
No more time out please !!!!

### ISSUE THREAD

**Issue by Armagryzor** [ImagicTheCat/vRP#278]
Hi Imagic , Hi all

It is no longer possible to use VRP if we have still the problem of time out !! ... I haven't addons on my serveur , i have a stronger dedicated server  etc etc .. 
I made a new server with essentiel and no problem but with vrp is a nightmare :(
Please check the problem imagic , your work is awesome , But it only works half
Please prioritize this problem before making any other updates that will not be useful if this problem persists!!!!

**Comment by JosGoLon** [comment]
+++

**Comment by ImagicTheCat** [comment]
Crying is not the way to solve issues, you should analyse and collect enough data to understand what is causing the timeout, as we have done for the join timeout issue, which is now solved. Try to compare your setup with servers without the issue, or compare the clients setup with others without the issue.

**Comment by VortexRP** [comment]
I have not had an issue with timeouts at all. If you could give some valuable information so I can help you find the reason for this that would be great. I'm interested so I can help make my own server stable as well.

**Comment by Armagryzor** [comment]
Vortex, you have'nt issue? i'm will be happy to connect on your server to see if you say right! Please trade the name of server please.

Imagic , i don't know how can i help you , you're welcome on my server to test , i can give you all acces with anydesk or temviewer of my dedicated server  if you want to see what is the problem of time out .

Vortex , Also , i'm not alone , i'm not the first to have the same problem

**Comment by VortexRP** [comment]
I think you're getting a little emotional lol. I've been on my server for 2 hours at a time testing everything from garages to interiors and yet to have this issue. Find the pattern. What are you doing when it times out? How long until these problems arise? Information like that goes a long way in reproducing the problems so they can get fixed.

**Comment by Armagryzor** [comment]
Vortex please ..simple question , simple answer...

Can you give me the name of your server to test if you haven't problem.. I did a search on the server browser with vortex , but nothing... thank's to sahre the name of your server ..

**Comment by CruelAlpha** [comment]
My server runs fine... I even have custom cars, and only rarely does it cause timeouts, almost once a week. Which is fine since fivem is new
