### ISSUE TITLE
[Feature] Buyable 'Groups'

### ISSUE THREAD

**Issue by WingedHussarr** [ImagicTheCat/vRP#279]
Add a function that will allow players to purchase a group meaning they are assigned that group (and is saved if they leave). This could be useful for users to create things such as a basic driving license or phone purchasing that will allow users to use the phone if they buy the group with the phone permission.

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP#grouppermission
It doesn't make any sense to buy groups, you should use the API for that.
