### ISSUE TITLE
Suggestions: Add effect when u drink a Vodka

### ISSUE THREAD

**Issue by Zuqaa** [ImagicTheCat/vRP#28]
I have a idea, why u not add a effect when u drink a Bottle of Vodka then a effect is executed and u are drunken

**Comment by Zuqaa** [comment]
I have found this:   ```lua
 if (!Function.Call<bool>(Hash.HAS_ANIM_SET_LOADED, "move_m@drunk@verydrunk"))
   {
       Function.Call(Hash.REQUEST_ANIM_SET, "move_m@drunk@verydrunk");
   }
       Function.Call(Hash.SET_PED_MOVEMENT_CLIPSET, ped.Handle, "move_m@drunk@verydrunk", 0x3E800000);
```

**Comment by Zuqaa** [comment]
Effect: And for the effect i think it is in Ambiant at this link: https://www.gtamodding.com/wiki/List_of_particle_effects

**Comment by 3rg00** [comment]
You can do it yourself, check examples for eat/drink in basic_items.lua.

**Comment by ImagicTheCat** [comment]
Interesting, I will look into this later to build a particle API, if possible.

**Comment by Zuqaa** [comment]
```
-- Anim Drunk
local function play_drunk(player)
  local seq = {
    {"move_m@drunk@verydrunk","intro_bottle",1},
    {"move_m@drunk@verydrunk","loop_bottle",1},
    {"move_m@drunk@verydrunk","outro_bottle",1}
  }

  vRPclient.playAnim(player,{true,seq,false})
  SET_PED_MOVEMENT_CLIPSET, ped.Handle, "move_m@drunk@verydrunk", 0x3E800000
 end
```

**Comment by Zuqaa** [comment]
I have a problem it does not work

**Comment by Zuqaa** [comment]
Hmm, the problem is the set ped movement, You can create a api for this native ^^ ?

**Comment by ImagicTheCat** [comment]
Do you know the default clipset ? Or a way to remove it ?

**Comment by Zuqaa** [comment]
I have found this: http://gtaforums.com/topic/821273-set-ped-movement-clipset/

But i dont know what is the default clipset :(

**Comment by Zuqaa** [comment]
and the native is RESET_PED_MOVEMENT_CLIPSET

**Comment by ImagicTheCat** [comment]
I think some of the move_m@ and move_f@ here could work http://docs.ragepluginhook.net/html/62951c37-a440-478c-b389-c471230ddfc5.htm , I will add a function.

**Comment by Zuqaa** [comment]
Ok ;)

**Comment by Zuqaa** [comment]
U add this in the next Update, if yes then i close the thread :p
