### ISSUE TITLE
Possible to disable survival completely for certain groups like admins?

### ISSUE THREAD

**Issue by timnboys** [ImagicTheCat/vRP#280]
Is it Possible to disable survival completely for certain groups like admins?
I cannot find any way looking in the code myself so that is why I am asking.

**Comment by ImagicTheCat** [comment]
Not possible right now, but will probably add a god permission (stopping the thirst/hunger increases, not disabling the survival module).

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/commit/b34487d9bf1dbd7a1d3a64311a4215c9ee36de57
