### ISSUE TITLE
[Feature] Some of my suggestions

### ISSUE THREAD

**Issue by BobbyLinny** [ImagicTheCat/vRP#281]
These are some of my suggestions which I believe would make this better. You are doing a great job with this and we all love you for making this. :)

1. A bank balance gui similar to the wallet gui so users can easily view their balance and actually know a bank exists

2. Item transformes having multiple permanent locations (Would allow for crafting in player houses)

3. Improved garages, right now you can only pull out one vehicle at a time from one garage. Make it so when you take out a vehicle you can't get another one of the SAME car however can get out another car

4. Following from above, make dealerships and garages seperate and allow for multiple garages where you can take out any car you own.

5. Improved jail system with timer (Make state prison useable)

6. Police drag

7. Car damage system similar to SOE so a hard direct hit disabled the engine (Could work with the repair kit)

**Comment by ImagicTheCat** [comment]
Please create individual features issues and check before that they doesn't exists yet, if they are related, add your point of view to them.
