### ISSUE TITLE
[Feature] Bank Balance Gui

### ISSUE THREAD

**Issue by BobbyLinny** [ImagicTheCat/vRP#282]
Display a gui similar to the money gui that displays the player's bank account balance

**Comment by benjatw** [comment]
You can make that your own.

I did it.

https://puu.sh/wJZNg/1a10413f89.png

**Comment by BobbyLinny** [comment]
Are you able to share how you did that, I have no idea how to edit guis and stuff like that

**Comment by benjatw** [comment]
Sorry i havent responded.
you have to edit
cfg/money.lua
module/money.lua
and
cfg/lang/en.lua

to be able to get it

**Comment by Disquse** [comment]
You can watch how it works there https://github.com/ENDrain/vRP-plusplus

**Comment by BobbyLinny** [comment]
Yep I figured it out

**Comment by ImagicTheCat** [comment]
vRP 2 has now money events to create custom HUD.
