### ISSUE TITLE
[Feature] Improved Garages

### ISSUE THREAD

**Issue by BobbyLinny** [ImagicTheCat/vRP#284]
right now you can only pull out one vehicle at a time from one garage. Make it so when you take out a vehicle you can't get another one of the SAME car however can get out another car. 

In addition to that make garages and car dealerships seperate since it makes no sense to have them together.

**Comment by HIsShadowONE** [comment]
theres a reason why , if you take out more vehicles the game doesnt remember that you own previous ones and it causes conflicts , that being said this is still entirely possible if you just change the vtype of cars in the _config line in garages.lua (would require a lot of work to do it this way if you want each car to be diff)

**Comment by BobbyLinny** [comment]
It can been done on other servers and also works on the essentialmode and I see no point in adding a massive amount of garages for seperate vehicles types.

**Comment by BobbyLinny** [comment]
And the dealership can probably be done by not allowing you to get out vehicles (I am no coder but I think that's not hard?)

**Comment by HIsShadowONE** [comment]
i didnt say there was logic behind making many vehicle types i was saying how youd have to do it in this framework, also comparing this to es mode makes no sense as they are two diff frameworks that are coded diff and thats why this has its limitations... ( i think most people dont like the garage system in vrp as its one of the main things that doesnt make much sense to most people) but i understand why magic has done it this way despite not agreeing with it personally for my taste. we dont always have to agree but understanding why and being able to discuss it and not take it personally is how a community grows.

Now as far as es mode letting you take out multiple cars yes you can but you should know as many do from playing on that that it does have its own set of issues by enabling this behavior, the game simply does not remember after a certain point which cars you own/ have access to and it does cause conflicts ive played on it and seen this.

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/commit/1f557b307a7873a580a6ba97124e8eb4630ccaab
