### ISSUE TITLE
[Question] Static menus

### ISSUE THREAD

**Issue by QuasarDev20** [ImagicTheCat/vRP#286]
I want to see any examples of adding a static menu choices please.
How to add my choices?

list of static menu types (map of name => {.title,.blipid,.blipcolor,.permission (optional)})
-- static menus are menu with choices defined by vRP.addStaticMenuChoices(name, choices)
cfg.static_menu_types = {
  ["missions"] = { -- example of a mission menu that can be filled by other resources
    title = "Missions",
    blipid = 205, 
    blipcolor = 5
  }
}

**Comment by ImagicTheCat** [comment]
This is not a help section, look for the forum topic or the discord for this kind of things.
