### ISSUE TITLE
[Feature] Driver License / DMV Drivers Test (Police CMDS aswell)

### ISSUE THREAD

**Issue by benjatw** [ImagicTheCat/vRP#287]
Buy Driver License / DMV Drivers Test

Police:
Check for driver license
Check for license plate on vehicles to see if they registered or not registered(NPC Vehicles / Stolen), and who they belong to.

**Comment by ImagicTheCat** [comment]
It's already possible.

**Comment by benjatw** [comment]
So it is already possible to check driver license and license plate?

**Comment by ImagicTheCat** [comment]
No idea what is the DMV Drivers test, but you can just create a driver license item (police can check items) and plates are already bound to the user, it's the registration number. Again, it's not an help section, you should use the forum topic or the discord.
