### ISSUE TITLE
[Emotes] Not able to bind tasks with animations from cfg 

### ISSUE THREAD

**Issue by Phyma** [ImagicTheCat/vRP#289]
Hello!

So I noticed that  you can bind a task and a animation by first running the task (to get a prop out, like a notepad) and then run animations that bind with the notepad. Character doesn't drop the notepad, just points at it or write on it etc.

Would it be possible to change the way tvRP.playAnim loops through the seq to allow for task and animations.

Like just a while loop on everything and check if the thing in the loop is a task or not, so this could work:
`{false, {{task="WORLD_HUMAN_CLIPBOARD"},"missheistdockssetup1clipboard@base","base",1}}, false}`

Thoughts?

**Comment by ImagicTheCat** [comment]
Too much complicated, playAnim can't be so generic, I don't think it would even work properly.

**Comment by Phyma** [comment]
Can't be or wont be? I'll see if i make it work.
