### ISSUE TITLE
Adding a job associated with vrp

### ISSUE THREAD

**Issue by Bandit33800** [ImagicTheCat/vRP#29]
Hello, count you added jobs ?
Or else how can we associate a job with the system of money of vrp

**Comment by ImagicTheCat** [comment]
You can create a resource that use the vRP API (as described in the proxy/tunnel sections) for complexe jobs. 
vRP will only provide a group/permission system with some callbacks, with maybe later a group selector (so you can use it for jobs).

If you want to use the money api, you just need the user_id from the source (vRP.getUserId), then you can use vRP.giveMoney and vRP.tryPayment.

**Comment by Bandit33800** [comment]
OK thanks for your answer

**Comment by Zuqaa** [comment]
Bandit if you have the response have your question.. You can close the issues ^^ ?

**Comment by Bandit33800** [comment]
OK no worries ;)
