### ISSUE TITLE
[FXserver] Menu open latency

### ISSUE THREAD

**Issue by SnaiCrys** [ImagicTheCat/vRP#290]
Opening main menu has big latency 2s-4s.

**Comment by ImagicTheCat** [comment]
Check if there are errors, if not, that explains to me why people had instancing issues. Check your MySQL server configuration, search for optimization parameters.

**Comment by karonte84** [comment]
Hi ImagicTheCag, I'm experiencing the same trouble with the fx version without any errors. 
What optimization parameters are you talking about?

**Comment by ImagicTheCat** [comment]
Still ?

**Comment by karonte84** [comment]
Not for me actually

**Comment by ImagicTheCat** [comment]
It depends only on how much time the menu is generated, so the bottleneck will mostly be SQL queries.

**Comment by SnaiCrys** [comment]
ImagicTheCat, We discussed this problem with you in a discord, it was associated with errors in other modules.
