### ISSUE TITLE
[FXServer] Fix for Gunshop

### ISSUE THREAD

**Issue by benjatw** [ImagicTheCat/vRP#292]
local total = math.ceil(parseFloat(price_ammo)*parseFloat(amount))

to

local total = math.ceil((price_ammo)*(amount))

Fixed it^^

Issue: When attempting to buy a gun it returned error in console which was:

Error running system event handling function for resource vrp: citizen:/scripting/lua/scheduler.lua:39: Failed to execute thread: modules/basic_gunshop.lua:35: attempt to call a nil value (global 'parseFloat')
stack traceback:
modules/basic_gunshop.lua:35: in local 'prompt'
modules/gui.lua:197: in local 'f'
[string "..."]:100: in upvalue 'handler'
citizen:/scripting/lua/scheduler.lua:124: in function <citizen:/scripting/lua/scheduler.lua:123>
stack traceback:
[C]: in function 'error'
citizen:/scripting/lua/scheduler.lua:39: in field 'CreateThreadNow'
citizen:/scripting/lua/scheduler.lua:123: in function <citizen:/scripting/lua/scheduler.lua:92>

**Comment by Phyma** [comment]
Why not do a pull request?

**Comment by ImagicTheCat** [comment]
Fixed.
