### ISSUE TITLE
[FXServer] basic_atm and gui.lua errors

### ISSUE THREAD

**Issue by benjatw** [ImagicTheCat/vRP#293]
this one:
Error running system event handling function for resource vrp: citizen:/scripting/lua/scheduler.lua:39: Failed to execute thread: modules/basic_atm.lua:47: attempt to compare number with nil
stack traceback:
modules/basic_atm.lua:47: in local 'prompt'
modules/gui.lua:197: in local 'f'
[string "..."]:100: in upvalue 'handler'
citizen:/scripting/lua/scheduler.lua:124: in function <citizen:/scripting/lua/scheduler.lua:123>
stack traceback:
[C]: in function 'error'
citizen:/scripting/lua/scheduler.lua:39: in field 'CreateThreadNow'
citizen:/scripting/lua/scheduler.lua:123: in function <citizen:/scripting/lua/scheduler.lua:92>

and this one:

Error running system event handling function for resource vrp: citizen:/scripting/lua/scheduler.lua:39: Failed to execute thread: modules/basic_atm.lua:24: attempt to compare number with nil
stack traceback:
modules/basic_atm.lua:24: in local 'prompt'
modules/gui.lua:197: in local 'f'
[string "..."]:100: in upvalue 'handler'
citizen:/scripting/lua/scheduler.lua:124: in function <citizen:/scripting/lua/scheduler.lua:123>
stack traceback:
[C]: in function 'error'
citizen:/scripting/lua/scheduler.lua:39: in field 'CreateThreadNow'
citizen:/scripting/lua/scheduler.lua:123: in function <citizen:/scripting/lua/scheduler.lua:92>

**Comment by ImagicTheCat** [comment]
Should be fixed.
