### ISSUE TITLE
[FX Server} After Startup item_transformer.lua ERROR

### ISSUE THREAD

**Issue by Healshot** [ImagicTheCat/vRP#295]
Error running system event handling function for resource vrp: citizen:/scriptin
g/lua/scheduler.lua:39: Failed to execute thread: modules/item_transformer.lua:1
44: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
        [C]: in function 'pairs'
        modules/item_transformer.lua:144: in field 'setItemTransformer'
        modules/item_transformer.lua:301: in upvalue 'callback'
        lib/utils.lua:43: in upvalue 'finish'
        lib/utils.lua:47: in upvalue 'task'
        base.lua:246: in local 'cb'
        [string "-- begin MySQL module..."]:40: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:124: in function <citizen:/scriptin
g/lua/scheduler.lua:123>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:39: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:123: in function <citizen:/scriptin
g/lua/scheduler.lua:92>

**Comment by ImagicTheCat** [comment]
Seems like a bad configured item transformers, please check everything before submitting issues.
