### ISSUE TITLE
[FXServer Feature Request] Jail & Fines

### ISSUE THREAD

**Issue by benjatw** [ImagicTheCat/vRP#296]
Ability to jail people for x amount of time and automaticly get released after.

Ability to set custom fine amounts, and a accept[F5] / decline[F6] fine feature.

**Comment by ImagicTheCat** [comment]
duplicate https://github.com/ImagicTheCat/vRP/issues/205

You should open one issue per subject. The basic fine system is based on presets and not custom (for less abuses), and rejecting fine is not very useful. Creating your own fine system should be simple with the way to extend menus (soon).
