### ISSUE TITLE
[FXServer] admin.lua and gui.lua error?

### ISSUE THREAD

**Issue by benjatw** [ImagicTheCat/vRP#297]
New bug, i do not know how it happend, but i just checked my server console and this popped up:

Error running system event handling function for resource vrp: citizen:/scripting/lua/scheduler.lua:39: Failed to execute thread: modules/admin.lua:69: attempt to concatenate a nil value (upvalue 'id')
stack traceback:
modules/admin.lua:69: in local 'prompt'
modules/gui.lua:197: in local 'f'
[string "..."]:100: in upvalue 'handler'
citizen:/scripting/lua/scheduler.lua:124: in function <citizen:/scripting/lua/scheduler.lua:123>
stack traceback:
[C]: in function 'error'
citizen:/scripting/lua/scheduler.lua:39: in field 'CreateThreadNow'
citizen:/scripting/lua/scheduler.lua:123: in function <citizen:/scripting/lua/scheduler.lua:92>

**Comment by Seenko** [comment]
That happens when you try to add a user to a group but leaves the User ID empty. Not a game breaking bug, just missing a check for nil values.

**Comment by ImagicTheCat** [comment]
Should be fixed.
