### ISSUE TITLE
[FXServer] Adding items to vehicle chest, nil value where table should exist.

### ISSUE THREAD

**Issue by Seenko** [ImagicTheCat/vRP#298]
Just when I was going about to check what was wrong with chests I came here and checked, you already made a fix for it, kinda worked in my case, don't know if this is unique to me.

When going to add items to the vehicle chest and with the updated inventory.lua file, this error:
`inventory.lua:381: bad argument #1 to 'pairs' (table expected, got nil)`

I suspect something is wrong with _data.inventory_ in the line 487
`local submenu = build_itemlist_menu(lang.inventory.chest.put.title(), data.inventory, cb_put)`

It passes the first verification at line 400 so _data.inventory_ is **not** nil.

I'm going to have a look at it tomorrow to see if I can fix it, but better register an Issue for now.

**Comment by ImagicTheCat** [comment]
It is exactly what I fixed, so I have no idea what is wrong with your scripts. More details needed.

**Comment by Seenko** [comment]
Uhum it's weird, `data.inventory` is not `nil` until it goes through `build_itemlist_menu`, then `items` become nil for some reason.

**Comment by Seenko** [comment]
After doing a git pull 3 more times the issue got fixed. I think git hates me.
