### ISSUE TITLE
Problem HUD doesnt refresh

### ISSUE THREAD

**Issue by Zuqaa** [ImagicTheCat/vRP#30]
I create a HUD for your Framework... When i spawn the first time i have john smith and when i go to create a identity the Hud doesnt refresh and i have already John Smith

My code: 

local htmlEntities = require("resources/vrp/lib/htmlEntities")

```lua
-- name hud
AddEventHandler("vRP:playerSpawned",function()
  local user_id = vRP.getUserId(source)
  if user_id ~= nil then
    local identity = vRP.getUserIdentity(user_id)
  
    vRPclient.setProgressBar(source,{"vRP:Identite","dessusargent","Nom : "..htmlEntities.encode(identity.firstname).." "..htmlEntities.encode(identity.name)..", Age : "..identity.age,0,0,0,100})
  end
end)
```

**Comment by ImagicTheCat** [comment]
You should create your own resource (using the proxy) for those kind of things. 
I will probably add a vRP:identityChanged event, meanwhile you can do a check/update at a specific rate.

**Comment by Zuqaa** [comment]
Good luck ;) Prevent me when you have create this ;)
