### ISSUE TITLE
[FXServer] MySQL lag or something

### ISSUE THREAD

**Issue by karonte84** [ImagicTheCat/vRP#300]
I just tested the new version of vrp using fxserver and everything seems to be good, but when like 10/15 players logged in the server start to be laggy as fuck.
The server where is hosted is not the problem because last week (with the old version of the fivem server and the old version of vRP) worked with 24 player for like 4/5 hours.
So I think that the problem is the new mysql connector + async or something
Did someone has experienced this problem?

**Comment by ImagicTheCat** [comment]
What are you calling lags, you should detail your observations.

**Comment by karonte84** [comment]
Here we go, I asked to some friends to login and have some chill test and this is what I got.

[This is the lag that I observed](https://youtu.be/HrgO66YNBAE)
[MySQL status](http://imgur.com/zFHuvEv)
[Server status](http://imgur.com/jafka8W)
[Some MySQL errors](http://imgur.com/luuoKYW)

I don't know if is a problem of the new FiveM server (Fxserver) or if is a problem with the new mysql-async that you used on the new version of vRP, but I experienced that if a server have more then 10 players after 5/10 minutes the lag comes. A lot of desync and we need like 5/10 seconds to open the vRP menu (as you can see in the video I wrote in chat when I pressed the menu button).
As you can see the server is not a bad server, is a quad core with 8GB of RAM and with a 100mbit network connection.

**Comment by ImagicTheCat** [comment]
This can happen if SQL queries are not responding, so this is bad issue. My way of coding try to ensure that everything still works even if some things have errors, so you should check for exceptions in the console.

**Comment by karonte84** [comment]
This is the only error in the console

`[    274047] [vRP] MySQL end query vRP/userid_byidentifier (35)
[    274109] System.NullReferenceException: Object reference not set to an instance of an object.

[    274109]   at System.Threading.Tasks.TaskScheduler.TryExecuteTask (System.Threading.Tasks.Task task) [0x00000] in <0123fd5b1a1040fe9d70a7e0d4b28acb>:0 

[    274125]   at CitizenFX.Core.CitizenTaskScheduler.InvokeTryExecuteTask (System.Threading.Tasks.Task task) [0x00000] in <b3642c6ba1504116b31d83a71003b504>:0 

[    274125]   at CitizenFX.Core.CitizenTaskScheduler.Tick () [0x00029] in <b3642c6ba1504116b31d83a71003b504>:0 

[    274141]   at CitizenFX.Core.InternalManager.TriggerEvent (System.String eventName, System.Byte[] argsSerialized, System.String sourceString) [0x00108] in <b3642c6ba1504116b31d83a71003b504>:0 `

**Comment by karonte84** [comment]
I founded this error too

[   1745375] Error resuming coroutine: lib/utils.lua:43: attempt to call a nil value (upvalue 'callback')
[   1745391] stack traceback:
[   1745391] 	lib/utils.lua:43: in upvalue 'finish'
[   1745391] 	lib/utils.lua:48: in function <lib/utils.lua:48>

**Comment by Sighmir** [comment]
The delay got resolved for me after making all my changes into their own resources, I think it had to do with nested queries. Maybe? I don't really know, just posting to let you know that maybe trying a fresh version of vrp and a fresh server and slowly make your changes in, might solve the issue or help you find the cause.
