### ISSUE TITLE
[FXServer] After relog again my console spams same error

### ISSUE THREAD

**Issue by MaZyGer** [ImagicTheCat/vRP#301]
Hello if a player joins for first time everything is ok. But after rejoin console gets spam with error and also he do not load his stuff like money, inventory. Everything stop working.

We use linux debian, mariadb, latest FXServer

> System.NullReferenceException: Object reference not set to an instance of an object
>   at System.Threading.Tasks.TaskScheduler.TryExecuteTask (System.Threading.Tasks.Task task) [0x00000] in <d7e663f2f7cd4ab6929018ec5233f09d>:0
>   at CitizenFX.Core.CitizenTaskScheduler.InvokeTryExecuteTask (System.Threading.Tasks.Task task) [0x00000] in /src/code/client/clrcore/CitizenTaskScheduler.cs:130
>   at CitizenFX.Core.CitizenTaskScheduler.Tick () [0x00029] in /src/code/client/clrcore/CitizenTaskScheduler.cs:107
>   at CitizenFX.Core.InternalManager.TriggerEvent (System.String eventName, System.Byte[] argsSerialized, System.String sourceString) [0x000ff] in /src/code/client/clrcore/InternalManager.cs:210

> Error during Tick: System.NullReferenceException: Object reference not set to an instance of an object
>   at System.Threading.Tasks.TaskScheduler.TryExecuteTask (System.Threading.Tasks.Task task) [0x00000] in <d7e663f2f7cd4ab6929018ec5233f09d>:0
>   at CitizenFX.Core.CitizenTaskScheduler.InvokeTryExecuteTask (System.Threading.Tasks.Task task) [0x00000] in /src/code/client/clrcore/CitizenTaskScheduler.cs:130
>   at CitizenFX.Core.CitizenTaskScheduler.Tick () [0x00029] in /src/code/client/clrcore/CitizenTaskScheduler.cs:107
>   at CitizenFX.Core.InternalManager.Tick () [0x00076] in /src/code/client/clrcore/InternalManager.cs:174

EDIT: I think this comes not from the vrp?

**Comment by ImagicTheCat** [comment]
The FXServer version of vRP is not stable, so only time will let us know what is working or not on the long term.

**Comment by cedricalpatch** [comment]
I have same problem or just related @ImagicTheCat but I think is come from host when change of player's?
I see in my consol lot of error when the host change of player's... 
May be is begging of solution?

**Comment by ImagicTheCat** [comment]
Any improvement ?
