### ISSUE TITLE
 [Feature] Permissions on emotes

### ISSUE THREAD

**Issue by Aleweadan** [ImagicTheCat/vRP#302]
Please it would be helpfull to put group permissions on the use of emotes for example a taxi driver can not play the emotes of the repair or policeman...

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/commit/201f5ecd5b36f7d4ba4e7864ebb5ad50155c312c

**Comment by Aleweadan** [comment]
Thank you !
