### ISSUE TITLE
[Feature] Hide HUD when menu paused

### ISSUE THREAD

**Issue by Aleweadan** [ImagicTheCat/vRP#303]
Hi, can you add a function  `local isPaused =`  to hide HUD when menu paused like this `https://github.com/indilo53/fivem-es_extended/commit/96272567f01b4c02cc0dd568b0d896a844ff8af1` please ?

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/commit/91511dd8410491e1c66eb82f0cb8ca630cfb306b

**Comment by Aleweadan** [comment]
Love this Thank you !!!!
