### ISSUE TITLE
[FXServer] VRP Mission issue?

### ISSUE THREAD

**Issue by benjatw** [ImagicTheCat/vRP#304]
Error running system event handling function for resource vrp: citizen:/scripting/lua/scheduler.lua:39: Failed to execute thread: modules/mission.lua:42: bad argument #1 to 'unpack' (table expected, got nil)
stack traceback:
[C]: in function 'table.unpack'
modules/mission.lua:42: in field 'nextMissionStep'
modules/mission.lua:25: in local 'f'
[string "-- Proxy interface system, used to add/call f..."]:39: in upvalue 'handler'
citizen:/scripting/lua/scheduler.lua:124: in function <citizen:/scripting/lua/scheduler.lua:123>
stack traceback:
[C]: in function 'error'
citizen:/scripting/lua/scheduler.lua:39: in field 'CreateThreadNow'
citizen:/scripting/lua/scheduler.lua:123: in function <citizen:/scripting/lua/scheduler.lua:92>

**Comment by ImagicTheCat** [comment]
This was related to vRP basic mission, should now be fixed.
