### ISSUE TITLE
[FXServer] Error

### ISSUE THREAD

**Issue by benjatw** [ImagicTheCat/vRP#305]
Error running system event handling function for resource vrp: citizen:/scripting/lua/scheduler.lua:39: Failed to execute thread: [string "-- Proxy interface system, used to add/call f..."]:39: bad argument #1 to 'unpack' (table expected, got number)
stack traceback:
[C]: in function 'table.unpack'
[string "-- Proxy interface system, used to add/call f..."]:39: in upvalue 'handler'
citizen:/scripting/lua/scheduler.lua:124: in function <citizen:/scripting/lua/scheduler.lua:123>
stack traceback:
[C]: in function 'error'
citizen:/scripting/lua/scheduler.lua:39: in field 'CreateThreadNow'
citizen:/scripting/lua/scheduler.lua:123: in function <citizen:/scripting/lua/scheduler.lua:92>

**Comment by ImagicTheCat** [comment]
Bad usage of proxy, not related to vRP, unless many have the same issue.

**Comment by bilbodog** [comment]
Hi there, I get this error as well. I can use some of the vRP commands through the proxy and tunnel, but some commands I can't use. For example. I can use the following as tested for now:
local Tunnel = module("vrp", "lib/Tunnel")
vRPclient = Tunnel.getInterface("vRP","bilbodog")
local Proxy = module("vrp", "lib/Proxy")
vRP = Proxy.getInterface("vRP")

vRPclient.varyHealth
vRPclient.notify
vRP.setHunger
vRP.setThirst
vRP.tryFullPayment
vRP.getUserId
vRP.getUserSource

But for some reason I cannot use these:
vRP.getPlayerEndpoint
vRP.hasPermission

**Comment by xView60** [comment]
no fix?
