### ISSUE TITLE
vrp identification error

### ISSUE THREAD

**Issue by viseniv** [ImagicTheCat/vRP#306]
This afternoon i was playing ok on my server, but now it gives me this error and i can't connect. Other players can connect and play

**Comment by ImagicTheCat** [comment]
This is not an help section, use the forum topic or the discord to get help. Identification error means that no user has been found or created, for X reasons.

**Comment by karonte84** [comment]
Actually a lot of players in my server can't login with this error but if I restart everything they will connect to the server. So I think is an issue of vRP with the new server of something
