### ISSUE TITLE
cannot access permissioned garages

### ISSUE THREAD

**Issue by HIsShadowONE** [ImagicTheCat/vRP#308]
nothing happens when i step into a permissioned garages circle anymore (i do not use ls customs saves for mods or anything else files are default from fx server files(newest comits))

**Comment by Healshot** [comment]
i have noticed the permission system no longer works for garages, gunshops, markets or item transformers

**Comment by Seenko** [comment]
You guys have broken something, they are working fine.

**Comment by HIsShadowONE** [comment]
i am using default files unchanged and newest commits .... as i specified above

**Comment by ImagicTheCat** [comment]
Probably a configuration issue.
