### ISSUE TITLE
Translation on gun/ammo

### ISSUE THREAD

**Issue by ImagicTheCat** [ImagicTheCat/vRP#309]
Could use lang system for wammo/wbody parametric item names (cf https://github.com/ImagicTheCat/vRP-basic-mission/issues/7)

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/commit/dbfa5044afbdd5a136e2e220b2abc03c7f9b9fe0

**Comment by Aleweadan** [comment]
Thank you for hard work :)
