### ISSUE TITLE
[FX] vrp_MySQL loading issues?

### ISSUE THREAD

**Issue by QuasarDev20** [ImagicTheCat/vRP#310]
`  421] Started resource rconlog
[      1029] Loaded mysql.net, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null into ScriptDomain_1599241040
[      1092] Exception loading assembly I18N: System.IO.FileNotFoundException: Unable to find the specified file.
 
[      1092] 
 
[      1092] 
 
[      1092] Server stack trace: 
 
[      1092]   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR (System.Int32 errorCode) [0x0000a] in <0123fd5b1a1040fe9d70a7e0d4b28acb>:0 
 
[      1092]   at (wrapper cominterop) CitizenFX.Core.IScriptHost:OpenHostFile (string)
 
[      1092]   at (wrapper cominterop-invoke) CitizenFX.Core.IScriptHost:OpenHostFile (string)
 
[      1092]   at CitizenFX.Core.MonoScriptRuntime+WrapScriptHost.OpenHostFile (System.String fileName) [0x00000] in C:\gl\builds\4ff63adb\0\cfx\fivem\code\client\clrcore\MonoScriptRuntime.cs:254 
 
[      1092]   at (wrapper remoting-invoke-with-check) CitizenFX.Core.MonoScriptRuntime+WrapScriptHost:OpenHostFile (string)
 
[      1092]   at (wrapper xdomain-dispatch) CitizenFX.Core.MonoScriptRuntime+WrapScriptHost:OpenHostFile (object,byte[]&,byte[]&,string)
 
[      1092] 
 
[      1092] Exception rethrown at [0]: 
 
[      1092]   at (wrapper xdomain-invoke) CitizenFX.Core.MonoScriptRuntime+WrapScriptHost:OpenHostFile (string)
 
[      1092]   at CitizenFX.Core.InternalManager.LoadAssembly (System.String name) [0x00000] in C:\gl\builds\4ff63adb\0\cfx\fivem\code\client\clrcore\InternalManager.cs:115 
[      1107] Instantiated instance of script vRP.MySQL.
[      1123] Started resource vrp_mysql
[      1232] Loaded MySqlConnector, Version=0.19.5.0, Culture=neutral, PublicKeyToken=null into ScriptDomain_1599241040
[      1341] Loaded System.Threading.Tasks.Extensions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 into ScriptDomain_1599241040
[      1497] Loaded System.Buffers, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 into ScriptDomain_1599241040
[      1497] [vRP] launch version 1498403827
[      1544] [vRP] init base tables
[      1653] Started resource vrp
[      1669] Started resource vrp_basic_mission `

Everytime i start my server this happens. I tryed different versions and host configs (linux/windows) and its still the same.

**Comment by ImagicTheCat** [comment]
Not related to vRP, probably a locked dll.
