### ISSUE TITLE
Saving not working properly

### ISSUE THREAD

**Issue by WingedHussarr** [ImagicTheCat/vRP#312]
Sometimes when you leave the server i doesn't save your data properly so you spawn in another position and with no money.

**Comment by Sheeperg** [comment]
Was steam launched before entering the server?

**Comment by Seenko** [comment]
I believe that happened to me once, but only to me a while ago, have no idea what might have caused it but maybe it was the older FXServer builds dying on me. This problem may occur with more frequence if your database is not in the same local network?

**Comment by JakeRyan1** [comment]
Yes i get the same issue...

**Comment by ImagicTheCat** [comment]
Deprecated issue (vRP 2).
