### ISSUE TITLE
Menu not working

### ISSUE THREAD

**Issue by WingedHussarr** [ImagicTheCat/vRP#313]
The menu bugs out randomly, the menu randomly appears and enter does not work in menus such as the garage one. This is the error in the console.

http://prntscr.com/g4p4y4

**Comment by ImagicTheCat** [comment]
You missed to add the exception print in the screenshot, so it's useless.

**Comment by SnaiCrys** [comment]
Problem is related to nil values in promt in admin menu, it was fixed.
