### ISSUE TITLE
Money lose

### ISSUE THREAD

**Issue by divians** [ImagicTheCat/vRP#316]
People do not get money when they go to the server! How to solve this problem?

**Comment by ImagicTheCat** [comment]
I'm sure you understand that there are no "money loss feature" in vRP right, and if the bug was about the money, it would be solved now. There are multiple scenarios that can cause this issue (possible duplicate https://github.com/ImagicTheCat/vRP/issues/312), mostly related to MySQL async (vrp_mysql). Submitting issues without giving maximum information about your setup, your number of players, or anything else even if you think that is not helpful, will not solve anything.

Also, duplicating your message in every place possible (github, discord, FiveM forum) is the best way to make people ignore you. Bug reports are on github ONLY, since the very beginning.

**Comment by divians** [comment]
http://prntscr.com/g7ve91

I have 30 people on the server, one of them in the database when entering the game balance of money on the bank 0
Always in the console there are errors, I do not know what they are connected with.


[   7208203] Error running system event handling function for resource vrp: citizen:/scripting/lua/scheduler.lua:39: Failed to execute thread: modules/mission.lua:42: bad argument #1 to 'unpack' (table expected, got nil)
[   7208203] stack traceback:
[   7208203] 	[C]: in function 'table.unpack'
[   7208203] 	modules/mission.lua:42: in field 'nextMissionStep'
[   7208203] 	modules/mission.lua:25: in local 'f'
[   7208203] 	[string "-- Proxy interface system, used to add/call f..."]:39: in upvalue 'handler'
[   7208203] 	citizen:/scripting/lua/scheduler.lua:124: in function <citizen:/scripting/lua/scheduler.lua:123>
[   7208203] stack traceback:
[   7208203] 	[C]: in function 'error'
[   7208203] 	citizen:/scripting/lua/scheduler.lua:39: in field 'CreateThreadNow'
[   7208203] 	citizen:/scripting/lua/scheduler.lua:123: in function <citizen:/scripting/lua/scheduler.lua:92>

Can I throw off the whole file with my log files??

**Comment by ImagicTheCat** [comment]
If you have different errors in the log file, copying them is helpful, the entire log files can contains IP and other things, which is not good to put publicly.

**Comment by BobbyLinny** [comment]
ACL is known to be causing such issues, if you have that in your server then that's probably the cause

**Comment by SnaiCrys** [comment]
Player lost money after the client crash, there were 25 people on the server. Try to reproduce error and record the logs.

**Comment by divians** [comment]
You need to change the mysql system, it obviously can not cope with the load of players ... 30 people on my server always, I think it's time to move to ES

**Comment by SnaiCrys** [comment]
```
-- save money on leave
AddEventHandler("vRP:playerLeave",function(user_id,source)
  -- (wallet,bank)
  local tmp = vRP.getUserTmpTable(user_id)
  if tmp then
    MySQL.query("vRP/set_money", {user_id = user_id, wallet = tmp.wallet or 0, bank = tmp.bank or 0})
  end
end)
```
I think problem with tmp.wallet/bank when the client сrush

**Comment by divians** [comment]
You changed something in the code? You do not have such a problem anymore?

**Comment by SnaiCrys** [comment]
https://github.com/ImagicTheCat/vRP/commit/a8ba7f80b3a302860e9a936f132800798258f6f7

**Comment by SnaiCrys** [comment]
fixed, can be closed
