### ISSUE TITLE
Does not work list of players

### ISSUE THREAD

**Issue by divians** [ImagicTheCat/vRP#317]
http://prntscr.com/g7x1c3

When there are 30 people on the server, the list of players for the administrator does not work, you press the user's list of players, it does not open, and in the console appears this error

**Comment by JakeRyan1** [comment]
Im having the same issue no edited files except base cfg this is a big problem when people are failing or rdming please fix soon!!!!

**Comment by ImagicTheCat** [comment]
News ?
