### ISSUE TITLE
The display of SMS is too short

### ISSUE THREAD

**Issue by Zuqaa** [ImagicTheCat/vRP#32]
When i receive a SMS, he is displayed only 1 second

**Comment by izio38** [comment]
So change it

**Comment by Zuqaa** [comment]
izio dont comment if it for say this.. it's not a problem for me it's a advice so @ImagicTheCat changes that

Sincerly, Lorenzo [Contributor of vRP]

**Comment by ImagicTheCat** [comment]
The notification is only a preview, since the message will be truncated by gta, the full SMS is in the SMS History at any time for any duration. I will see but it's not a priority.

**Comment by Zuqaa** [comment]
Yes it's true, i have miss the history sry xD

I close this ^^

Good Luck anyway dude
