### ISSUE TITLE
error survival.lua scheduler.lua

### ISSUE THREAD

**Issue by funzik** [ImagicTheCat/vRP#320]
Bonjour,

J'ai une erreur qui se produit, savez vous pourquoi ?

Merci d'avance pour votre boulot !

[   2722844] Error running system event handling function for resource vrp: citizen:/scripting/lua/scheduler.lua:39: Failed to execute thread: modules/survival.lua:169: attempt to index a nil value (local 'data')
[   2722844] stack traceback:
[   2722860] 	modules/survival.lua:169: in upvalue 'handler'
[   2722860] 	citizen:/scripting/lua/scheduler.lua:124: in function <citizen:/scripting/lua/scheduler.lua:123>
[   2722860] stack traceback:
[   2722860] 	[C]: in function 'error'
[   2722875] 	citizen:/scripting/lua/scheduler.lua:39: in field 'CreateThreadNow'
[   2722875] 	citizen:/scripting/lua/scheduler.lua:123: in function <citizen:/scripting/lua/scheduler.lua:92>
[   2722875] 	[C]: in function 'coroutine.resume'
[   2722875] 	citizen:/scripting/lua/scheduler.lua:73: in function <citizen:/scripting/lua/scheduler.lua:59>

**Comment by ImagicTheCat** [comment]
Possibly related to https://github.com/ImagicTheCat/vRP/issues/405

**Comment by ImagicTheCat** [comment]
Probably irrelevant for vRP 2.
