### ISSUE TITLE
Spawn from Home/Apartment

### ISSUE THREAD

**Issue by mrCPUgeek** [ImagicTheCat/vRP#328]
If I buy and apartment/home.  I can go to that apartment and from that apartment with no problems.  However, if I disconnect from the game while in the apartment/home, when I reconnect, I am in that apartment, but I don't have the locations to transport out of the apartment/home.

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP#homes

**Comment by mrCPUgeek** [comment]
I understand it is experimental.  What I experienced and reported wasn't actually mentioned in your wiki so I just thought I'd let you know.  Basicly, if you disconnect inside the apartment, your character is "locked" in that apartment until you go into the user_data table and manually change their location.  

Again, just letting you know.   I understand it is still experimental.  Thanks.

**Comment by ImagicTheCat** [comment]
It's not a bug, vRP doesn't remember if you were in an apartment, but will still save the player location for the next connection. Homes will be improved someday, and will handle this kind of issues.
