### ISSUE TITLE
[Issue] Error on every player connection

### ISSUE THREAD

**Issue by ARL64** [ImagicTheCat/vRP#335]
![lang](https://user-images.githubusercontent.com/837109/29934027-f69c734e-8e79-11e7-8978-04598ae873c1.PNG)

Can't figure why it throws that error. I think I've done the update well, this is not an error since the commit of today but since more than two weeks when I started update from cfx to fx.

**Comment by Aleweadan** [comment]
I have this but it's solved. I have Apply bad value to the hunger and thirst on a custom item food maybe you have similar problem
