### ISSUE TITLE
[Feature] Add permissions on blips

### ISSUE THREAD

**Issue by Aleweadan** [ImagicTheCat/vRP#337]
Please could you make permissions on map blips for example show blips only for a specific jobs and don't have map full of blips. Thank you.

**Comment by ImagicTheCat** [comment]
Not possible, blips can't have permissions. The only way is to do the perm check before adding the blips, but permissions are dynamics (group add/rm, special perms) where blips are not so dynamics. It would require to listen to every permissions changes and update ALL blips accordingly, in all case a rewrite of lot of the vRP code is necessary for this feature and performances will be impacted. So, it's not planned right now.

**Comment by Aleweadan** [comment]
Ok, there is a simple way to do that maybe on item transformer we can show blip if have permissions ?
