### ISSUE TITLE
VRP can't be loaded (after fix for identification error) (SOLVED)

### ISSUE THREAD

**Issue by danini1705** [ImagicTheCat/vRP#340]
![aaa](https://user-images.githubusercontent.com/19955147/30003008-b58b6e92-90b7-11e7-84e8-c62793a33ecf.PNG)
![a](https://user-images.githubusercontent.com/19955147/30003010-b769f26a-90b7-11e7-8f61-b7daec1c8186.PNG)

**Comment by ImagicTheCat** [comment]
If you can reproduce the issue with a fresh install, I will look into it. But again, lot of issues are about people messing up the config files because they don't know how Lua works. This is not an help section.

**Comment by danini1705** [comment]
![bbb](https://user-images.githubusercontent.com/19955147/30003495-25ff3dec-90be-11e7-90cc-3c84464aeb02.PNG)
![b](https://user-images.githubusercontent.com/19955147/30003496-294002a2-90be-11e7-9413-77a00122c15d.PNG)
![bb](https://user-images.githubusercontent.com/19955147/30003497-296154f2-90be-11e7-9796-c952b0dcf11c.PNG)

**Comment by Aleweadan** [comment]
Did you configure mysql connection correctly in cfg / base.lua ?

**Comment by mistersnoob** [comment]
hi, make sure you have configured your mysql accesses correctly in cfg/base.lua and if you are using a remote mysql server, make sure your mysql server accepts remote connections.

I had the same problem as you and it was my mysql server that refused the connection.

**Comment by danini1705** [comment]
Idk how I do that
