### ISSUE TITLE
[FEATURE] Bank Transfer + Jail + Custom Tickets

### ISSUE THREAD

**Issue by benjatw** [ImagicTheCat/vRP#343]
I merged this request to one.

Bank Transfer, from the ATM's to transfer money to people.

Jail - Jailing people for x amount of time and sending them to the big prison in the middle of the map.

Custom tickets - Like the buy menu, just where you can put in Reason, what they are getting at ticket for and the x amount of money it has to cost, make it more dynamic.

Thanks!

Appreciate all your hard work!

**Comment by ImagicTheCat** [comment]
Each features should have their own post, if they aren't related. Also check that those features are not already proposed (if they differ a little, add your own idea in the post).
