### ISSUE TITLE
Money and salary reset 

### ISSUE THREAD

**Issue by mordredtheknight** [ImagicTheCat/vRP#344]
Hi, we have a problem using VRP with FX SERVER.

Many of our ppl, after some login, have all their bank money and salary reset and we don't know why.
The error in the console is always the same and sometimes weapons disappears too.

The error we got is this:

Error running system event handling function for resource vrp: citizen:/scripting/lua/scheduler.lua:39: Failed to execute thread: base.lua:385: attempt to concatenate a nil value (local ‘ep’)
stack traceback:
base.lua:385: in upvalue 'callback’
lib/utils.lua:43: in upvalue 'finish’
lib/utils.lua:47: in upvalue 'task’
base.lua:201: in local ‘cb’
[string “-- begin MySQL module…”]:40: in upvalue 'handler’
citizen:/scripting/lua/scheduler.lua:124: in function citizen:/scripting/lua/scheduler.lua:123
stack traceback:
[C]: in function 'error’
citizen:/scripting/lua/scheduler.lua:39: in field 'CreateThreadNow’
citizen:/scripting/lua/scheduler.lua:123: in function citizen:/scripting/lua/scheduler.lua:92

Can you pls help us solve this problem?

**Comment by ImagicTheCat** [comment]
Should be fixed by previous commits.
