### ISSUE TITLE
[Feature] Item_transformers.lua (Aptitude Permission system?)

### ISSUE THREAD

**Issue by benjatw** [ImagicTheCat/vRP#345]
A permission system for aptitudes,

example.

So that you have example. 
Hacking.
one spot where it requires zero skill level,
but being able to restrict another item_transformer for a player to have a certain level.

Hacking spot 1:
level 0
Pay out........

Hacking spot 2 "Expert":
level 10 hacking restricted
Pay out........

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP#special-aptitude-permission
