### ISSUE TITLE
[Not Major Issue] Removing from group.

### ISSUE THREAD

**Issue by benjatw** [ImagicTheCat/vRP#346]
Error running system event handling function for resource vrp: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: modules/group.lua:117: attempt to index a nil value (local 'groupdef')
stack traceback:
        modules/group.lua:117: in field 'removeUserGroup'
        modules/admin.lua:113: in local 'prompt'
        modules/gui.lua:197: in local 'f'
        [string "..."]:100: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>

- Not because this does anything, than telling that i left the remove user from group blank or a wrong id / group. 

But is it possible to remove it from console so it doesnt pop up as an error?

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/commit/a80869d82b67961b830389e2ad3a510caaf00f84
