### ISSUE TITLE
[BUG] Unknown Client

### ISSUE THREAD

**Issue by benjatw** [ImagicTheCat/vRP#351]
Getting unknown client, and not whitelist / user_id

Plain vrp + vrp_mysql installation with no customizations nor other scripts.

**Comment by SPJESTER** [comment]
seems to be a ipv6 issue, disabling this in your network card config seems to fix it

**Comment by ImagicTheCat** [comment]
probably related https://github.com/ImagicTheCat/vRP/issues/336
