### ISSUE TITLE
Configuring VRP

### ISSUE THREAD

**Issue by Cryton2017** [ImagicTheCat/vRP#355]
I am having trouble understanding the configuration instructions. Do I need to add both the vrp and vrrp_mysql folder to the resources or just vrp and reference them both in the server config?

When I run the server, there are a lot of errors saying that tables dont exist. Is there something else I need to download for do I need to write code to create them?

Thanks in advnace
Chris

**Comment by Sighmir** [comment]
You should have vrp and vrp_mysql enabled and configure your database information on vRP/cfg/base.lua.
The database must be created before vRP connects to it, it automatically creates the table but not the database.

**Comment by Cryton2017** [comment]
How do I create the database before starting the server?

**Comment by Sighmir** [comment]
I recommend you look some YouTube videos or research a bit about how to set up a database, look for tutorials about MySQL... There's different methods to create a database depending on the environment you have, so it would be hard to tell you how to do it without knowing anything about your MySQL server or which manager you use to interact with it. That is not really related to vRP, setting up a database is required to run almost any server for any game.

**Comment by Cryton2017** [comment]
So if I was to set up XAMP with PHPMyAdmin and create the database there, would I need my server to be in htdocs or will vrp search a database somewhere with the specified name?

**Comment by Sighmir** [comment]
There's no need to have Apache for a FiveM server, just the MySQL database,
htdocs is part of Apache, which is a WebServer in itself to host websites.

Any resource on a FiveM server will connect to your DB using a MySQL.dll
which will find the DB by the address:port, username, password and database
name.
The fx-server and the database don't need to be on the same computer,
although having it in different computers could cause problems if
connection was interrupted between server and database.
