### ISSUE TITLE
vRPex: playerDropped event doesn't call for "vRP:playerLeave"

### ISSUE THREAD

**Issue by Sighmir** [ImagicTheCat/vRP#356]
Hey Imagic, great work!
I encountered this issue with the vRPex branch, the event playerDropped seem to be having problems with the vRPclient.removePlayer(-1, source) function because if I have that function uncommented the event fails to run and hangs there. I tested it by commenting the event out and adding prints like so:
```lua

AddEventHandler("playerDropped",function(reason)
  local source = source
  print(source)
  Debug.pbegin("playerDropped")

  -- remove player from connected clients
  -- vRPclient.removePlayer(-1, source)

  local user_id = vRP.getUserId(source)
  print(user_id)
  if user_id then
    TriggerEvent("vRP:playerLeave", user_id, source)

    -- save user data table
    vRP.setUData(user_id,"vRP:datatable",json.encode(vRP.getUserDataTable(user_id)))

    print("[vRP] "..vRP.getPlayerEndpoint(source).." disconnected (user_id = "..user_id..")")
    vRP.users[vRP.rusers[user_id]] = nil
    vRP.rusers[user_id] = nil
    vRP.user_tables[user_id] = nil
    vRP.user_tmp_tables[user_id] = nil
    vRP.user_sources[user_id] = nil
  end
  Debug.pend()
end)
```
With the function un-commented the event hangs there. With it commented it runs the whole event.
I will look for a solution, if I find it, I will make a pull request.

**Comment by ImagicTheCat** [comment]
It could be fixed if we had a reliable FiveM disconnect event, for now playerDropped is not always called so I can't really add a disconnect handler to remove the waiting Tunnel requests to fix this issue. If you find one, or if you can check if they fixed it, it will be good.

**Comment by ImagicTheCat** [comment]
What about https://github.com/ImagicTheCat/vRP/commit/90dcea1ba46475a1c02493bd8fe18503931fb507 ?

**Comment by Sighmir** [comment]
Just tested the new update, apparently now the event goes through and call the vRP:playerLeave and prints the message with the correct user_id, the only weird thing is the IP on the message is always 0.0.0.0 but I think that has to do with source being lost before the vRP.getPlayerEndpoint is called.

This update fixed other issues with my scripts that were related to Tunnel calls and the event playerDropped not going through, thank you very much for working on it.

**Comment by Sighmir** [comment]
Creating a variable endpoint and calling it before the vRPclient tunnel call proved to solve the issue with IPs 0.0.0.0, my event is like this: 
```lua
AddEventHandler("playerDropped",function(reason)
  local source = source
  Debug.pbegin("playerDropped")
  
  local endpoint = vRP.getPlayerEndpoint(source)
  -- remove player from connected clients
  vRPclient.removePlayer(-1, source)

  local user_id = vRP.getUserId(source)

  if user_id then
    TriggerEvent("vRP:playerLeave", user_id, source)

    -- save user data table
    vRP.setUData(user_id,"vRP:datatable",json.encode(vRP.getUserDataTable(user_id)))

    print("[vRP] "..endpoint.." disconnected (user_id = "..user_id..")")
    vRP.users[vRP.rusers[user_id]] = nil
    vRP.rusers[user_id] = nil
    vRP.user_tables[user_id] = nil
    vRP.user_tmp_tables[user_id] = nil
    vRP.user_sources[user_id] = nil
  end
  Debug.pend()
end)
```

**Comment by ImagicTheCat** [comment]
Thanks for the feedback, added the display fix.
