### ISSUE TITLE
Convert EssentialMode Command to vRP command !

### ISSUE THREAD

**Issue by Zuqaa** [ImagicTheCat/vRP#36]
Hi i have create a systeme of jobs on EssentialMode but i search to convert the command to the vRP command ? @ImagicTheCat If you want check the job it is dispo on my github page

**Comment by cedricalpatch** [comment]
Hello,

I have allready install one old version of essentialmode for command and all work fine if you whant ;)
Juste the problem is for job the momney go in essential table and I have test to send money in the bank account Vrp but not found solution!?

**Comment by Zuqaa** [comment]
The command for my job is the money.. For have the money at the end its ok but for supp money doesnt work

**Comment by 3rg00** [comment]
Guys, he planned to develop jobs part, it's listed on the Todo.
It's more efficient to wait the release that it should by totally integrated with the vRP framework, instead of "copy/paste" another module scripted for Essentialmode :(.

**Comment by Zuqaa** [comment]
it's not a copy/paste it's my script dude :) i'm the author of the script.. Search my script on FiveM you will not find

**Comment by 3rg00** [comment]
I mean you want that Imagic copy/paste module script for ES into vRP...
You know what is the concept of framework ? Have you ever tried to understand how this framework works and the way of Imagic develop it ? So I don't want to speak instead of @ImagicTheCat, but in my opinion you should wait and see what he will release...

**Comment by Zuqaa** [comment]
Ok, i just want help :( sry..

Good Luck...

**Comment by 3rg00** [comment]
I think for to really help a lot is to bring littles, but essentially improvement (ex: betters markers for City Hall, corrections for garages markers, etc...) 👍 .
For the "core" concept, we need to let Imagic works and publish when he want to.

**Comment by Zuqaa** [comment]
Ok ^^
