### ISSUE TITLE
[vRPex] Needs fix

### ISSUE THREAD

**Issue by benjatw** [ImagicTheCat/vRP#360]
vRPex has a stability issue when there is more than 5+ people on the server

What issues occur?
Menu's for item_transformers, lscustoms, garage, etc. stops working.
Server is throwing out a lot more vRP ping timeouts, i guess because it can't handle the stress
Menu is very slow on opening when phone key is pressed etc.

Thanks in advance for doing a great job!

**Comment by Anark-Link** [comment]
Truth, I'm having the same problems, also the withelist unknow client problem.

**Comment by ImagicTheCat** [comment]
Obsolete.
