### ISSUE TITLE
IPV6 support??

### ISSUE THREAD

**Issue by SPJESTER** [ImagicTheCat/vRP#361]
Everyone with a ipv6 address just shows 0.0.0.0 in the database and remains as a unknown player?

**Comment by ImagicTheCat** [comment]
Since most people don't use git to configure their vRP version, they don't get the updates so they don't even know about this https://github.com/ImagicTheCat/vRP/blob/fxserver/vrp/cfg/base.lua#L24 . IP identification should not be a thing IMHO.
