### ISSUE TITLE
adding visible markser

### ISSUE THREAD

**Issue by Cryton2017** [ImagicTheCat/vRP#362]
I am trying to add visible markers.  I found this in the code and in the tutorials:

{x,y,z,sx,sy,sz,r,g,b,a,visible_distance}

I get that x,y,z are for the the location of the marker, r,g,b is for the colour of the marker, visible distance is for the distance at which a user can see the marker but I dont get what, sx,sy,sz and a is for. Any help would be great.

Thanks in advance.

**Comment by ImagicTheCat** [comment]
They are the scale factors of the marker (it's a 3d object), a is alpha btw. Not really an issue/feature, use the FiveM forum topic to get help.
