### ISSUE TITLE
[vRPex] Problems currently known in vrpex

### ISSUE THREAD

**Issue by Anark-Link** [ImagicTheCat/vRP#364]
Currently after the pro vrpex migration, the code got cleaner and the best, except that vrpex started to generate problems that did not occur in vrpfx, I will try to report all possible problems related to Vrpex. the problems that are occurring are:

1. Problem with the "Unknow Client" message withelist when the withelist is Enabled, the Client enters the server, and never receives the kick message with the ID to the withelist. always appearing to msg "Unknow Client". Thus not giving the possibility of using the witheliste.     **---adjusted**

2. Problem of server instability when going from 4 to 6 players online.      **---adjusted**

3. The server kicks the client by Ping High every 20 mins sometimes longer, never being able to stay long online without taking a kick.         **---adjusted**

4. Sometimes the server "timed out after 10 seconds" sometimes "Server connection timed out after 15 seconds." knocking everyone onlines, and then back quickly.          **---adjusted**

5. Delay immense when opening the Interaction Menu. vrpfx the delay is 0, instantly opens the menu without the delay occurring in vRPex.      **---Not yet corrected**

6. Bug Glitche reported by Players: Bug of the farmes: enter the place of the farmes and exit quickly by clicking "Enter" several times, bugando and you can farmer without being there in the place.   **---Not yet corrected**

7. car tracking in the police department, this bug is ten of the master version, I believe no one has reported it yet, I may be wrong. At the time of tracking the vehicle with the identity number of the player, it never traces, 10x trying to track a vehicle, always the error in the tracking. I do not know if this is a bug in itself or is something of a possibility of crawling, But I tried to track the vehicle several times and always without success.          **---Not yet corrected, This problem comes in ten of the master version**

**## Out all the problems listed, Thanks in advance for doing a great job!**

**Comment by ImagicTheCat** [comment]
What about 5 now ?

**Comment by ImagicTheCat** [comment]
Not up to date, prefer an issue for a specific problem instead of an issue for multiple problems.
