### ISSUE TITLE
[vRPex] Radio

### ISSUE THREAD

**Issue by SnaiCrys** [ImagicTheCat/vRP#368]
If you quickly switch radio stations, you may receive an error that stops playback.
![clip2net_180115084538](https://user-images.githubusercontent.com/4284827/34928825-3727fb5a-f9d1-11e7-95a5-29f937fa6a16.png)

**Comment by ImagicTheCat** [comment]
Probably an issue with the version of CEF used by FiveM, some issues reported about the play() function of HTML5Audio with streams in some versions, no idea if there is a fix possible, I leave the issue open if someone find something.

**Comment by SnaiCrys** [comment]
Fixed after cef update
