### ISSUE TITLE
Hide HUD/gui when button is clicked.

### ISSUE THREAD

**Issue by DyJaLo** [ImagicTheCat/vRP#369]
I've made a news crew script that brings out a camera and puts you in first person (done through the cellphone camera script), but I've done it outside of the vrp files. Right now my issue is hiding the HUD of vrp (money and hunger/thirst.)

I've seen the vRP.isPaused(), but I'm not able to get it to work. I'm sure I have the proxy or tunnel stuff all wrong, but I'm terrible with that type of stuff and have tried a ton of stuff lol. 

Wondering if anyone could provide some help on getting the hud to hide after a button is clicked? 

Thanks

**Comment by ImagicTheCat** [comment]
This is a feature request, there is no API to hide the GUI.

**Comment by ImagicTheCat** [comment]
Not a very good solution, but better than nothing. https://github.com/ImagicTheCat/vRP/commit/8dc977304da1f684a48178c53dec6a2f5f28355e
