### ISSUE TITLE
Set a clothes at die

### ISSUE THREAD

**Issue by Zuqaa** [ImagicTheCat/vRP#37]
I liked set the white silk robe when the player die

**Comment by Aleweadan** [comment]
Good idea but the player must respawn at the hospital for a good rp.

**Comment by Zuqaa** [comment]
Yes i have the code for this ^^

**Comment by ImagicTheCat** [comment]
You can do it by listening to the spawn event (or die if it works), and use vRP.setCustomization to set the ped parts to what you want.

**Comment by Zuqaa** [comment]
Yes i know but what i want a list with clothes.. I dont have find the white robe on the Net :(
