### ISSUE TITLE
MYSQLCONNECT ERROR

### ISSUE THREAD

**Issue by SirNikk** [ImagicTheCat/vRP#370]
Hello, recently I changed my server from Windows to Debian 8 system and with that I cant start correctly the server, I will drag bellow the log and errors.
https://prnt.sc/i3s51l
https://prnt.sc/i3s53k

AND this is what appears on game https://prnt.sc/i3yusk
Can u help me pls? I dont have changes the files vrp_mysql and dont know if have to.

**Comment by ImagicTheCat** [comment]
Try to use something else than vrp_mysql (vrpex).
