### ISSUE TITLE
Vehicle ownership loss

### ISSUE THREAD

**Issue by jskov9850** [ImagicTheCat/vRP#371]
Is it possible to change the distance for vehicle ownership? Sometimes when players go a bit away from their vehicle, it's not theirs anymore

**Comment by ImagicTheCat** [comment]
It's a known problem, difficult to solve in a robust way, but I have some ideas. I don't have much time to give to vRP, but I would like to solve this one when I can.

**Comment by DemmyDemon** [comment]
Suggestion:  Use a Decorator: https://runtime.fivem.net/doc/reference.html#_n_DECORATOR

**Comment by ImagicTheCat** [comment]
Are they shared/synced between players ?

**Comment by DemmyDemon** [comment]
Yeah, that's the whole idea.
They won't sync if you don't "own" the entity, so you can't set decorators
on a car someone else is driving, or someone else's player ped, but setting
a decorator on your vehicle migrates with it when someone else becomes the
"owner" (network-wise) of the entity.

I use this to sync fuel, for example.


Kind regards,
    Fredrik Vold
    Evil Overlord at webkonsept.com

**Comment by ImagicTheCat** [comment]
This is amazing, will implement something ASAP.

**Comment by ImagicTheCat** [comment]
Not yet tested for vehicle loss: https://github.com/ImagicTheCat/vRP/commit/1f557b307a7873a580a6ba97124e8eb4630ccaab
