### ISSUE TITLE
[PROGRAMMING ISSUE] Move something to another menu

### ISSUE THREAD

**Issue by jskov9850** [ImagicTheCat/vRP#372]
I'm trying to move the "search cpr register" that's in the PC from the PD but I want to copy it and paste it so that it is also in the menu (vRP)

I did the following:

Pasted *this* in modules/police.lua

          if vRP.hasPermission(user_id,"police.putinveh") then
            menu[lang.police.pc.searchreg.title()] = choice_searchreg
          end

and added this to "menu = {" in en.lua in languages

      searchreg = {
        title = "Søg i CPR register",
        description = "Slå et CPR nummer op.",
        prompt = "Skriv det CPR-NUMMER du ønsker at slå op.."
      },

**Comment by ImagicTheCat** [comment]
Issues are not for help...
