### ISSUE TITLE
Error running system event handling function for resource vrp

### ISSUE THREAD

**Issue by chaixshot** [ImagicTheCat/vRP#373]
> Error running system event handling function for resource vrp: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: lib/utils.lua:43: attempt to call a nil value (upvalue 'callback')
> stack traceback:
>         lib/utils.lua:43: in upvalue 'finish'
>         lib/utils.lua:47: in upvalue 'task'
>         modules/home.lua:306: in upvalue 'callback'
>         lib/utils.lua:43: in upvalue 'finish'
>         lib/utils.lua:47: in upvalue 'task'
>         modules/home.lua:57: in local 'cb'
>         [string "-- begin MySQL module..."]:45: in upvalue 'handler'
>         citizen:/scripting/lua/scheduler.lua:175: in function <citizen:/scripting/lua/scheduler.lua:174>
> stack traceback:
>         [C]: in function 'error'
>         citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
>         citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:138>

When accept `vRP.request(hplayer, lang.home.intercom.request({who}), 30, function(hplayer,ok)`
in modules/home.lua

**Comment by DaviReisVieira** [comment]
@ImagicTheCat  Me too! Can you help?

**Comment by ImagicTheCat** [comment]
Deprecated stuff, soon vrpex will be merged into fxserver.
