### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by XxTopKillerzZ** [ImagicTheCat/vRP#377]
Where ia the database stored/how can i acces it?

Does it create some admin panel?

**Comment by DunkoUK** [comment]
If you've set up a database surely you know how to access it? What database are you using?

**Comment by HarryCatraz** [comment]
When the server runs it should make a database. You need to go to \FXServer\resources\vrp\cfg\base.lua and edit the file to suit your database. For example my database is running on my server so my file looks like:


local cfg = {}

-- mysql credentials
cfg.db = {
  host = "127.0.0.1", -- database ip (default is local)
  database = "vrpfx",   -- name of database
  user = "root",    --  database username
  password = ""   -- password of your database
}

cfg.save_interval = 30 -- seconds
cfg.whitelist = false -- enable/disable whitelist
cfg.ignore_ip_identifier = true -- This will allow multiple same IP connections (for families etc)

-- delay the tunnel at loading (for weak connections)
cfg.load_duration = 5 -- seconds, player duration in loading mode at the first spawn
cfg.load_delay = 0 -- milliseconds, delay the tunnel communication when in loading mode
cfg.global_delay = 0 -- milliseconds, delay the tunnel communication when not in loading mode

cfg.ping_timeout = 5 -- number of minutes after a client should be kicked if not sending pings

cfg.lang = "en" -- en / fr / it / ger / pt / ru / lith / dan / ar / pl / es / swe / fin (English/Français/Italiano/Deutsche/Português/Pусский/Lietuvių/Dansk/العربية/Polskie/Español/Svenska/Suomalainen)
cfg.debug = false


return cfg

Before you run your server make sure you have HeidiSQL installed and running along with Xampp. Then in HeidiSQL  right click the left hand panel and then Create New>Database. Call this the same as the on in base.lua. Then run the server and you should be good to go!

https://www.heidisql.com/
https://www.apachefriends.org/index.html

**Comment by ImagicTheCat** [comment]
This is not an help section, please use the FiveM forum topic.
