### ISSUE TITLE
Remove vehicle already owned check

### ISSUE THREAD

**Issue by HarryCatraz** [ImagicTheCat/vRP#378]
When a player purchases a vehicle it puts it in their stored vehicles. Then the player cant buy the same vehicle again unless they sell the other one. If there a way to remove this to let players have an infinite amount of the same vehicle.

Thanks
Catraz

**Comment by HarryCatraz** [comment]
Bump

**Comment by ImagicTheCat** [comment]
Don't bump issues unless you solved it.

**Comment by ImagicTheCat** [comment]
The basic garage is not designed for this, vehicles are stored per type, I think you need to create your own garage.
