### ISSUE TITLE
[vRPex] Skinshop delay

### ISSUE THREAD

**Issue by SnaiCrys** [ImagicTheCat/vRP#381]
Long delay (~8s) of opening skinshop menu because vRPclient.getDrawableTextures

**Comment by ImagicTheCat** [comment]
vRPex has a better way to write Tunnel/Proxy calls, but it requires more thinking to avoid this kind of behavior (calls are waiting the result/execution by default). 
Should decrease latency: https://github.com/ImagicTheCat/vRP/commit/b0218861daf7fcadba2c66b8fb119e54a870f582
