### ISSUE TITLE
[BUG] Freeze player

### ISSUE THREAD

**Issue by luisflorido** [ImagicTheCat/vRP#382]
Hi, when some players join in server, they just stay frozen in spawn and cannot do anything (no errors on client log and server log), they are invisible and locked, i think is something released to identity because anything they do with requires identity say a error, this is fixed when i reboot server but affect others people after.

**Comment by ImagicTheCat** [comment]
Solved ?

**Comment by luisflorido** [comment]
Yes, there is was a conflict between join player event
