### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by DaviReisVieira** [ImagicTheCat/vRP#384]
Error running system event handling function for resource vrp: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: lib/utils.lua:43: attempt to call a nil value (upvalue 'callback')
stack traceback:
        lib/utils.lua:43: in upvalue 'finish'
        lib/utils.lua:47: in upvalue 'task'
        modules/home.lua:295: in upvalue 'callback'
        lib/utils.lua:43: in upvalue 'finish'
        lib/utils.lua:47: in upvalue 'task'
        modules/home.lua:57: in local 'cb'
        [string "-- begin MySQL module..."]:45: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:175: in function citizen:/scripting/lua/scheduler.lua:174
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:174: in function citizen:/scripting/lua/scheduler.lua:138

**Comment by ImagicTheCat** [comment]
Deprecated stuff, vrpex will soon be merged in fxserver.
