### ISSUE TITLE
citizen error

### ISSUE THREAD

**Issue by DaviReisVieira** [ImagicTheCat/vRP#385]
Error running call reference function for resource vrp_basic_mission: citizen:/scripting/lua/scheduler.lua:351: server.lua:198: attempt to index a nil value (local 'identity')
stack traceback:
        server.lua:198: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:337: in function <citizen:/scripting/lua/scheduler.lua:336>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:336: in function <citizen:/scripting/lua/scheduler.lua:335>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:351: in function <citizen:/scripting/lua/scheduler.lua:322>
Error resuming coroutine: citizen:/scripting/lua/MessagePack.lua:830: missing bytes
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow'
        citizen:/scripting/lua/MessagePack.lua:465: in field 'any'
        citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack'
        citizen:/scripting/lua/scheduler.lua:563: in upvalue 'callback'
        lib/utils.lua:43: in upvalue 'finish'
        lib/utils.lua:48: in function <lib/utils.lua:48>
Error running call reference function for resource vrp_basic_mission: citizen:/scripting/lua/scheduler.lua:351: server.lua:198: attempt to index a nil value (local 'identity')
stack traceback:
        server.lua:198: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:337: in function <citizen:/scripting/lua/scheduler.lua:336>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:336: in function <citizen:/scripting/lua/scheduler.lua:335>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:351: in function <citizen:/scripting/lua/scheduler.lua:322>
Error resuming coroutine: citizen:/scripting/lua/MessagePack.lua:830: missing bytes
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow'
        citizen:/scripting/lua/MessagePack.lua:465: in field 'any'
        citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack'
        citizen:/scripting/lua/scheduler.lua:563: in upvalue 'callback'
        lib/utils.lua:43: in upvalue 'finish'
        lib/utils.lua:48: in function <lib/utils.lua:48>
Matheus Muller: /twitter alguém pra me ajudar por favor?
Connecting: Pato
[vRP] Pato (191.189.21.4) rejected: identification error
Error running call reference function for resource vrp_basic_mission: citizen:/scripting/lua/scheduler.lua:351: server.lua:198: attempt to index a nil value (local 'identity')
stack traceback:
        server.lua:198: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:337: in function <citizen:/scripting/lua/scheduler.lua:336>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:336: in function <citizen:/scripting/lua/scheduler.lua:335>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:351: in function <citizen:/scripting/lua/scheduler.lua:322>
Error resuming coroutine: citizen:/scripting/lua/MessagePack.lua:830: missing bytes
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow'
        citizen:/scripting/lua/MessagePack.lua:465: in field 'any'
        citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack'
        citizen:/scripting/lua/scheduler.lua:563: in upvalue 'callback'
        lib/utils.lua:43: in upvalue 'finish'
        lib/utils.lua:48: in function <lib/utils.lua:48>
Connecting: FireFoOXxX
[vRP] FireFoOXxX (179.110.167.232) rejected: identification error
Sending heartbeat to live-internal.fivem.net:30110
Error running call reference function for resource vrp_basic_mission: citizen:/scripting/lua/scheduler.lua:351: server.lua:198: attempt to index a nil value (local 'identity')
stack traceback:
        server.lua:198: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:337: in function <citizen:/scripting/lua/scheduler.lua:336>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:336: in function <citizen:/scripting/lua/scheduler.lua:335>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:351: in function <citizen:/scripting/lua/scheduler.lua:322>
Error resuming coroutine: citizen:/scripting/lua/MessagePack.lua:830: missing bytes
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow'
        citizen:/scripting/lua/MessagePack.lua:465: in field 'any'
        citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack'
        citizen:/scripting/lua/scheduler.lua:563: in upvalue 'callback'
        lib/utils.lua:43: in upvalue 'finish'
        lib/utils.lua:48: in function <lib/utils.lua:48>

**Comment by ImagicTheCat** [comment]
Probably related to vRP basic mission.

**Comment by SuperTSGAMES** [comment]
is giving me this error


Initializing Mono
Initializing Mono completed
Hello!
Resolved live-internal.fivem.net:30110 to 62.210.162.18:30110
Found new resource fivem in F:/server\Vrpex-Server/resources//fivem
Found new resource fivem-awesome1501 in F:/server\Vrpex-Server/resources//fivem-awesome1501
Found new resource fivem-map-hipster in F:/server\Vrpex-Server/resources//fivem-map-hipster
Found new resource fivem-map-skater in F:/server\Vrpex-Server/resources//fivem-map-skater
Found new resource runcode in F:/server\Vrpex-Server/resources//runcode
Found new resource vrp in F:/server\Vrpex-Server/resources//vrp
Found new resource vrp_mysql in F:/server\Vrpex-Server/resources//vrp_mysql
Found new resource race in F:/server\Vrpex-Server/resources//[gamemodes]/race
Found new resource race-test in F:/server\Vrpex-Server/resources//[gamemodes]/race-test
Found new resource channelfeed in F:/server\Vrpex-Server/resources//[gameplay]/channelfeed
Found new resource irc in F:/server\Vrpex-Server/resources//[gameplay]/irc
Found new resource obituary in F:/server\Vrpex-Server/resources//[gameplay]/obituary
Found new resource obituary-deaths in F:/server\Vrpex-Server/resources//[gameplay]/obituary-deaths
Found new resource playernames in F:/server\Vrpex-Server/resources//[gameplay]/playernames
Found new resource mapmanager in F:/server\Vrpex-Server/resources//[managers]/mapmanager
Found new resource baseevents in F:/server\Vrpex-Server/resources//[system]/baseevents
Found new resource chat in F:/server\Vrpex-Server/resources//[system]/chat
Found new resource hardcap in F:/server\Vrpex-Server/resources//[system]/hardcap
Found new resource rconlog in F:/server\Vrpex-Server/resources//[system]/rconlog
Found new resource scoreboard in F:/server\Vrpex-Server/resources//[system]/scoreboard
Found new resource sessionmanager in F:/server\Vrpex-Server/resources//[system]/sessionmanager
Found new resource spawnmanager in F:/server\Vrpex-Server/resources//[system]/spawnmanager
Found new resource betaguns in F:/server\Vrpex-Server/resources//[test]/betaguns
Found new resource gameInit in F:/server\Vrpex-Server/resources//[test]/gameInit
Found new resource keks in F:/server\Vrpex-Server/resources//[test]/keks
Started resource sessionmanager
Started resource mapmanager
Started resource chat
Started resource spawnmanager
Started resource fivem
Started gametype Freeroam
Started resource hardcap
Started resource rconlog
Started resource scoreboard
Started resource playernames
[vRP] init base tables
Started resource vrp
Loaded mysql.net, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null into ScriptDomain_1287221062
Exception loading assembly I18N: System.IO.FileNotFoundException: Unable to find the specified file.


Server stack trace:
  at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR (System.Int32 errorCode) [0x0000a] in <0123fd5b1a1040fe9d70a7e0d4b28acb>:0
  at (wrapper cominterop) CitizenFX.Core.IScriptHost:OpenHostFile (string)
  at (wrapper cominterop-invoke) CitizenFX.Core.IScriptHost:OpenHostFile (string)
  at CitizenFX.Core.MonoScriptRuntime+WrapScriptHost.OpenHostFile (System.String fileName) [0x00000] in C:\gl\builds\4ff63adb\0\cfx\fivem\code\client\clrcore\MonoScriptRuntime.cs:254
  at (wrapper remoting-invoke-with-check) CitizenFX.Core.MonoScriptRuntime+WrapScriptHost:OpenHostFile (string)
  at (wrapper xdomain-dispatch) CitizenFX.Core.MonoScriptRuntime+WrapScriptHost:OpenHostFile (object,byte[]&,byte[]&,string)

Exception rethrown at [0]:
  at (wrapper xdomain-invoke) CitizenFX.Core.MonoScriptRuntime+WrapScriptHost:OpenHostFile (string)
  at CitizenFX.Core.InternalManager.LoadAssembly (System.String name) [0x00000] in C:\gl\builds\4ff63adb\0\cfx\fivem\code\client\clrcore\InternalManager.cs:112
[vRP/C#] Load MySQL app.
Instantiated instance of script vRP.MySQL.
Started resource vrp_mysql
Authenticating server license key...
Server license key authentication succeeded. Welcome!
cfx> Sending heartbeat to live-internal.fivem.net:30110
[vRP] DB driver "vrp_mysql" not initialized yet (42 prepares cached, 6 queries cached).
Started resource fivem-map-hipster
Started map fivem-map-hipster
Error running call reference function for resource vrp_mysql: citizen:/scripting/lua/scheduler.lua:351: citizen:/scripting/lua/scheduler.lua:655: No such export createConnection in resource vrp_mysql
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:655: in metamethod '__index'
        init.lua:46: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:337: in function <citizen:/scripting/lua/scheduler.lua:336>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:336: in function <citizen:/scripting/lua/scheduler.lua:335>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:351: in function <citizen:/scripting/lua/scheduler.lua:322>
        [C]: in function 'coroutine.resume'
        citizen:/scripting/lua/scheduler.lua:115: in function <citizen:/scripting/lua/scheduler.lua:100>
Error running system event handling function for resource vrp: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: citizen:/scripting/lua/MessagePack.lua:830: missing bytes
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow'
        citizen:/scripting/lua/MessagePack.lua:465: in field 'any'
        citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack'
        citizen:/scripting/lua/scheduler.lua:563: in local 'on_init'
        base.lua:54: in local 'f'
        [string "vrp/lib/Proxy.lua"]:72: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:175: in function <citizen:/scripting/lua/scheduler.lua:174>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:138>
[
hitch warning: frame time of 4087 milliseconds
[vRP] DB driver "vrp_mysql" not initialized yet (42 prepares cached, 7 queries cached).
[vRP] DB driver "vrp_mysql" not initialized yet (42 prepares cached, 7 queries cached).
[vRP] DB driver "vrp_mysql" not initialized yet (42 prepares cached, 7 queries cached).
[vRP] DB driver "vrp_mysql" not initialized yet (42 prepares cached, 7 queries cached).
[vRP] DB driver "vrp_mysql" not initialized yet (42 prepares cached, 7 queries cached).
[vRP] DB driver "vrp_mysql" not initialized yet (42 prepares cached, 7 queries cached).
[vRP] DB driver "vrp_mysql" not initialized yet (42 prepares cached, 7 queries cached).
[vRP] DB driver "vrp_mysql" not initialized yet (42 prepares cached, 7 queries cached).
[vRP] DB driver "vrp_mysql" not initialized yet (42 prepares cached, 7 queries cached).
[vRP] DB driver "vrp_mysql" not initialized yet (42 prepares cached, 7 queries cached).
