### ISSUE TITLE
Unknown client

### ISSUE THREAD

**Issue by luisflorido** [ImagicTheCat/vRP#386]
When i try to use whitelist, and some players try to join server maybe he get this error, i've searching for a solution but i have not found nothing and not many posts about it.

**Comment by luisflorido** [comment]
Added Wait and resolved it

**Comment by ImagicTheCat** [comment]
Wait ?

**Comment by luisflorido** [comment]
Just add Citizen.Wait(1000) or whatever time you want before deferrals.done when kick from not whitelisted or banned and with magic this works

**Comment by ImagicTheCat** [comment]
Well, I don't like this kind of fixes, but it will do the job.
