### ISSUE TITLE
Item_Transformers bug

### ISSUE THREAD

**Issue by blinkfl** [ImagicTheCat/vRP#387]
I'm my server I'm using the newest master fx version and when players get all the items from a item_transformers, often happen that the amount of item stay at empty and I can only solve this by restarting my server. So I don't want to set a high number in the amount because I want to have more controll of the balance in my server, I want to know if there's a solution for this problem without having to restart the server every time that this happens

**Comment by ImagicTheCat** [comment]
Is that a bug or did you just missed the "units_per_minute" property ?

**Comment by blinkfl** [comment]
It is a bug because I know some other servers that the owners are having the same issues with this version of the vrp, but in any case I'm sending one config of a item for u to be sure that I didn't missed the units_per_minute 

`{
    name="Pescar", -- menu name
    permissions = {"mission.delivery.fish"}, -- you can add permissions
    r=0,g=125,b=255, -- color
    max_units=100,
    units_per_minute=2,
    x=743.19586181641,y=3895.3967285156,z=30.5, 
    radius=3, height=1.5, -- area
    recipes = {
      ["Pescar Bagre"] = { -- action name
        description="Tentando pescar Bagre", -- action description
        in_money=0, -- money taken per unit
        out_money=0, -- money earned per unit
        reagents={}, -- items taken per unit
        products={ -- items given per unit
          ["catfish"] = 1
        }
      },
      ["Pescar Robalo"] = { -- action name
        description="Tentando pescar Robalo", -- action description
        in_money=0, -- money taken per unit
        out_money=0, -- money earned per unit
        reagents={}, -- items taken per unit
        products={ -- items given per unit
          ["bass"] = 1
        }
      }
    }
  },`

**Comment by fsje** [comment]
I can confirm this, and are experiencing the same issue. :-)

**Comment by Santagain** [comment]
same issue here

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/blob/fxserver/vrp/modules/item_transformer.lua#L234 is doing the refill, so check if you have errors in your console when the refill stops.

**Comment by fsje** [comment]
`182 enter slot other_flat 1 
Error running system event handling function for resource vrp: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: modules/item_transformer.lua:141: attempt to concatenate a nil value (field 'b') 
stack traceback: 
modules/item_transformer.lua:141: in field 'setItemTransformer' 
modules/home_components.lua:229: in field '?' 
modules/home.lua:262: in upvalue 'callback' 
lib/utils.lua:43: in upvalue 'finish' 
lib/utils.lua:47: in upvalue 'task' 
modules/home.lua:37: in local 'cb' 
[string "-- begin MySQL module..."]:45: in upvalue 'handler' 
citizen:/scripting/lua/scheduler.lua:175: in function <citizen:/scripting/lua/scheduler.lua:174> 
stack traceback: 
[C]: in function 'error' 
citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow' 
citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:138> 
182 leave slot other_flat 1 
free slot other_flat 1 `

I am currently getting this. 
Another error popped up the other day, but haven't got it this time. I'll try to see if I can provocate it to show later.

**Comment by blinkfl** [comment]
The only error that I saw in my log sometimes is this one

> [ 369312391] Error running system event handling function for resource vrp: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: lib/utils.lua:43: attempt to call a nil value (upvalue 'callback')
> [ 369312391] stack traceback:
> [ 369312391] 	lib/utils.lua:43: in upvalue 'finish'
> [ 369312391] 	lib/utils.lua:47: in upvalue 'task'
> [ 369312391] 	modules/home.lua:295: in upvalue 'callback'
> [ 369312391] 	lib/utils.lua:43: in upvalue 'finish'
> [ 369312391] 	lib/utils.lua:47: in upvalue 'task'
> [ 369312391] 	modules/home.lua:57: in local 'cb'
> [ 369312391] 	[string "-- begin MySQL module..."]:45: in upvalue 'handler'
> [ 369312391] 	citizen:/scripting/lua/scheduler.lua:175: in function <citizen:/scripting/lua/scheduler.lua:174>
> [ 369312391] stack traceback:
> [ 369312391] 	[C]: in function 'error'
> [ 369312391] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
> [ 369312391] 	citizen:/scripting/lua/scheduler.lua:174: in function 
> <citizen:/scripting/lua/scheduler.lua:138>

but I don't know if this happens before the empty issue or after, never noticed because when players complain about this it has passed a lot of time
