### ISSUE TITLE
What does this error mean?

### ISSUE THREAD

**Issue by jskov9850** [ImagicTheCat/vRP#389]
Hi,

Is anyone able to tell me what this error means?

https://gyazo.com/a6615fef0aa1ef47854719afc28bc2f2

**Comment by WolfM3ST3R** [comment]
this error has occurred to me and does not disappear until I delete the identities (the identity table).

**Comment by ImagicTheCat** [comment]
duplicate https://github.com/ImagicTheCat/vRP/issues/389#issuecomment-368361696
