### ISSUE TITLE
[vRP/C#] connection vRP not found

### ISSUE THREAD

**Issue by Augusto22xb** [ImagicTheCat/vRP#390]
I'm having these problems: https://puu.sh/zsgBC/531dfa37cf.png
Something is missing ?

I have another machine connected to a database on the same host and everything is ok.

**Comment by Santagain** [comment]
http://www.edivaldobrito.com.br/como-instalar-o-mono-no-ubuntu-debian-e-derivados/

**Comment by Santagain** [comment]
Linux or Windows ?

**Comment by Augusto22xb** [comment]
Linux. I have the full package of mono because my panel for game hosting.

**Comment by ImagicTheCat** [comment]
duplicate https://github.com/ImagicTheCat/vRP/issues/380
