### ISSUE TITLE
Using lua client functions

### ISSUE THREAD

**Issue by Cryton2017** [ImagicTheCat/vRP#391]
I am trying to add the ability to spawn a vehicle through the cloak rooms. I am getting an error when I use the function GetVehicleHash("taxi"). The error is: "attempt to call a nil value (global 'GetHashKey')"

I copied the code I am using from here:
https://wiki.fivem.net/wiki/CreateVehicle

Any ideas on what to do?

**Comment by ImagicTheCat** [comment]
This is not an help forum but he issue section of vRP, please use the FiveM forum.
