### ISSUE TITLE
This error has not been resolved

### ISSUE THREAD

**Issue by WolfM3ST3R** [ImagicTheCat/vRP#393]
This error first appeared on December 26th,and to solve the problem was to delete the entire identity table!:
https://pastebin.com/h6uGjpU9
This error occurs once every 2-3 weeks:
This error occurs especially on large servers that have very many users:5k - 15k users

My friend is not a scripter lua or fivem he is developer java and oracle(database,security),he told me:
problem vrpex
@registration
https://cdn.discordapp.com/attachments/357586157304938498/411894663402749953/unknown.png

Mai caut(ro)=search more(en)
Voi folosi=I will use
Am gasit=I found
I created a log for registration

You are single person can fix this error.
I tried with my friends but I did not do anything!

**Comment by ImagicTheCat** [comment]
I am definitely not the only person that can fix this issue and in fact I'm not the most suited for the task (poor knowledge of C#). This is probably a problem in the MySQL module of communication between Lua and C#, I have no idea what is causing it. So feel free to check the C# code for any mistakes.

I may make the vrp_mysql module optional at some point, with a generic system to bind any custom db connector, so people will have alternatives.

**Comment by SnaiCrys** [comment]
> I noticed vrp and vrpex not works anymore when will appeared 64 slots and more!
What?

**Comment by ImagicTheCat** [comment]
It's important to keep the issue section clean and that each issue is specific to a unique problem, so I will close this one. You can try to solve this problem by using another driver than vrp_mysql like vrp_ghmattimysql (GHMattiMySQL).
