### ISSUE TITLE
[vRPex] MySQL error after server upgrade.

### ISSUE THREAD

**Issue by GTA-Vanyangel** [ImagicTheCat/vRP#394]
Hello Imagic !

Sorry to bother you for this noobish question...
For some reasons, i reinstalled my VPS from OVH from Debian 7 to Debian 9.

I have a MySQL setup working with my forum and my bugtracker, but when i'm trying to start the server, i get the basic MySQL error like everyone that doesn't configure their database correctly in cfg/base.lua.

Here is the error: https://pastebin.com/WpJiNm2Y

I created a php file to test the connection from my  GTA database, it can connect.. I don't know why vRP can't.
No error in error_log of mysql and no connection attempt too.

Then i decided to test if vRP could connect to an external MySQL server, it can and it works fine, but i need it to be local...

So, the issue has to be from my MySQL, but i have no clue what it could be....

**Comment by Santagain** [comment]
this issue is because mono, you installed the mono-devel or mono-complete ?

**Comment by Santagain** [comment]
if you install, is because the version of mono in new repo. i get same error on make an server using the Ubuntu 17(that already comes with the mono in its repository). I was only able to start the server by going back to Ubuntu 16, and manually adding the repositories of mono.

**Comment by ImagicTheCat** [comment]
Probably unrelated to vRP, but if you know the exact issue and the solution, add it here so I can add a note on the README.

**Comment by Santagain** [comment]
Yep, its problem with repo, the solution is above. rollback to an previous system version

**Comment by GTA-Vanyangel** [comment]
The problem has nothing to do with repo: as i said in my post: 

> Then i decided to test if vRP could connect to an external MySQL server, it can and it works fine, but i need it to be local...

If it was because of the mono, it would not work with another database.

Anyway i'm going to use the new DB handling system :)
