### ISSUE TITLE
[VoIP] Volume calculating

### ISSUE THREAD

**Issue by SnaiCrys** [ImagicTheCat/vRP#395]
Moving to a distance of 99 meters (cfg.voip_proximity = 100) the player continues to be heard very quiet. It seems that there is a problem with the formula for calculating the volume (does not reach 0).

**Comment by ImagicTheCat** [comment]
It's not a problem, it's the way it works. I will expose more spatialization effect properties so you can change the distance model.

**Comment by ImagicTheCat** [comment]
dist_model is now available.
