### ISSUE TITLE
radio dont work

### ISSUE THREAD

**Issue by Origintk** [ImagicTheCat/vRP#396]
the police radio system is not working

**Comment by SnaiCrys** [comment]
Have you configured a TURN server?

**Comment by Origintk** [comment]
could you pass me a tutorial to set it up?

**Comment by SnaiCrys** [comment]
https://www.webrtc-experiment.com/docs/TURN-server-installation-guide.html

**Comment by ImagicTheCat** [comment]
Issues are not for help.
