### ISSUE TITLE
Linking resource to vRP (Error)

### ISSUE THREAD

**Issue by Cryton2017** [ImagicTheCat/vRP#397]
Hello

I have already asked on the FiveM forums but I ahve had no response after a day so I thought I would post here. I am trying to convert a resource meant for ELS to vRP. I have changed and updated what needs to be updated in the script but I am just having issues getting the script to connect to vRP. When I add linking for client side, I get this error:

Error loading script sv_delivery.lua in resource vrp_delivery: sv_delivery.lua:4: attempt to index a nil value (global ‘Proxy’)

My code looks like this:

vRP = Proxy.getInterface(“vRP”)

And in resources.lua:

client_scripts {
’@vrp/client/Proxy.lua’
}

When I try to add for server side I get this error:

Error loading script sv_delivery.lua in resource vrp_delivery: sv_delivery.lua:4: attempt to call a nil value (global ‘require’)

The code looks like this:

local Proxy = require(“resources/vRP/lib/Proxy”)
vRP = Proxy.getInterface(“vRP”)

Any ideas?
Thanks in advance

**Comment by Santagain** [comment]
use - local Proxy = module("vrp", "lib/Proxy")

**Comment by Cryton2017** [comment]
I now get this error:

Error loading script sv_delivery.lua in resource vrp_delivery: sv_delivery.lua:2: attempt to call a nil value (global 'module')
stack traceback:
        sv_delivery.lua:2: in main chunk
Failed to load script sv_delivery.lua

My code now looks like:

--Link to vRP
local Proxy = module("vrp", "lib/Proxy")
vRP = Proxy.getInterface("vRP")

**Comment by ImagicTheCat** [comment]
Issues are not for help.
