### ISSUE TITLE
Weaponstype by location

### ISSUE THREAD

**Issue by 3rg00** [ImagicTheCat/vRP#4]
Hello,
Im currently adding all weapons that supposed to be availables ingame, but I want to know if it possible to apply the same system used for garages (differents types of car by locations) to ammunations shop ?`
Thanks in advance :)

**Comment by ImagicTheCat** [comment]
It was something I was thinking about, it's better to have specific elements per shop. It's done. I will probably do the same for the markets, if people use the item API.
