### ISSUE TITLE
problems with vrp connection

### ISSUE THREAD

**Issue by xquito** [ImagicTheCat/vRP#400]
[vRP/C#] connection/command path vRP/get_srvdata not found
[vRP/C#] connection/command path vRP/set_srvdata not found
[vRP/C#] connection/command path vRP/userid_byidentifier not found
Connecting: Vinicius_Chiquito
Sending heartbeat to live-internal.fivem.net:30110
[vRP] Vinicius_Chiquito (127.0.0.1) rejected: identification error
Syncing weather for: Vinicius_Chiquito
[vRP/C#] connection/command path vRP/dmv_search not found
[vRP/C#] connection/command path vRP/ply_get_vehicles not found
[vRP/C#] connection/command path vRP/get_address not found
Sending heartbeat to live-internal.fivem.net:30110
Error resuming coroutine: lib/utils.lua:43: attempt to call a nil value (upvalue 'callback')
stack traceback:
        lib/utils.lua:43: in upvalue 'finish'
        lib/utils.lua:48: in function <lib/utils.lua:48>
[vRP/C#] connection/command path vRP/userid_byidentifier not found

**Comment by xquito** [comment]
http://prntscr.com/iqt7sw

**Comment by ImagicTheCat** [comment]
See database setup.
