### ISSUE TITLE
"SEND_NUI_MESSAGE: resource vrp has no UI frame"

### ISSUE THREAD

**Issue by Phasfeldt** [ImagicTheCat/vRP#403]
After yesterdays update, I've noticed alot of servers have begun throwing alot of errors around the VRP, and the UI frame in it.

The only error showing up on my crashes in my crashlog, is `SEND_NUI_MESSAGE: resource vrp has no UI frame` and constantly keeps the players on the server, with FiveM just freezing randomly.

Have there been noted any fix on this, or is it just a question of time, before it's solved?

**Comment by Santagain** [comment]
Because This: https://github.com/citizenfx/fivem/commit/87798ada15bc188160d058af5295e813f57f1555

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/commit/a58b81b31a323506dcff56109d5a7a676e022411
