### ISSUE TITLE
[vrpex] spawn error

### ISSUE THREAD

**Issue by SnaiCrys** [ImagicTheCat/vRP#405]
![clip2net_180317172315](https://user-images.githubusercontent.com/4284827/37556488-f9686f36-2a07-11e8-81bd-e0c7abda2440.png)
It happens when you come after the crash.
Then character reset

**Comment by ImagicTheCat** [comment]
`modules/survival.lua` has 219 lines, so error messages are wrong or the file is modified.

**Comment by SnaiCrys** [comment]
it's my debug print and comments, sorry

153 line
```
AddEventHandler("vRP:playerJoin",function(user_id,source,name,last_login)
  local data = vRP.getUserDataTable(user_id)
  if data.hunger == nil then
    data.hunger = 0
    data.thirst = 0
  end
end)

```

**Comment by ImagicTheCat** [comment]
You can check the user_id validity and check the value of vRP.getUData(user_id, "vRP:datatable"), also check if there are MySQL errors.

**Comment by SnaiCrys** [comment]
I don't think I can specifically reproduce this error again. I'll add prints for the future.

**Comment by ImagicTheCat** [comment]
There are some reports of money loss, random MySQL errors, etc, so maybe using something else than `vrp_mysql` will solve those issues.

**Comment by SnaiCrys** [comment]
I'll try to use https://github.com/GHMatti/FiveM-MySQL

**Comment by ImagicTheCat** [comment]
You can create a driver, I don't know if this resource supports prepared statements, but stability is be better than performance for now. If you create a repository, I could help you with the interface.

**Comment by SnaiCrys** [comment]
You mean the fork GHMatti''s MySQL? I have zero knowledge in C#

**Comment by ImagicTheCat** [comment]
No C#, it's just a bridge resource that depends on `vrp` and this resource, register a "DB driver" in Lua for vRP and use this resource API. My knowledge (and desire) about C# is poor too, it's why I added this new API to abstract any MySQL resources in vRP.

**Comment by SnaiCrys** [comment]
https://github.com/SnaiCrys/vRP-GHMatti-s-MySQL

**Comment by ImagicTheCat** [comment]
I don't know if it's good to do it this way, I will ask on the topic of the creator.

**Comment by SnaiCrys** [comment]
In any case, we comply with AGPLv3

**Comment by ImagicTheCat** [comment]
If his work is a standalone resource, it could be better to just write the bridge and let people install his resource with our own.

**Comment by SnaiCrys** [comment]
So it would be better in terms of resource support.

**Comment by ImagicTheCat** [comment]
Yes, and no duplication of data.

**Comment by ImagicTheCat** [comment]
I think I will create a global repository with all the potential bridges inside instead, if you don't mind, easier to manage and they are too specific resources related to vRP core features, not really standalone.

**Comment by SnaiCrys** [comment]
ok, i delete mine

**Comment by ImagicTheCat** [comment]
It wasn't so difficult, I think I have GHMattiMySQL working. https://github.com/ImagicTheCat/vRP-db-drivers

**Comment by SnaiCrys** [comment]
With a new database the problem was repeated

tested without https://github.com/ImagicTheCat/vRP/commit/ac679a9b3d6c4817da1ae13bc05bf8ced6806665
```
[vRP] 31.****193 disconnected (user_id = 41)
[vRP] Paradox (0.0.0.0) joined (user_id = 41)
[vRP] Paradox (0.0.0.0) re-joined (user_id = 41)
[vRP] Paradox (31.****.193) re-joined (user_id = 41)
[vRP] Paradox (0.0.0.0) joined (user_id = 41)
[vRP] 31.****.193 disconnected (user_id = 41)
[vRP] Paradox (31.****.193) joined (user_id = 41)
```
Then character reset

**Comment by SnaiCrys** [comment]
I don't know why this this happening, but to keep the loop going, it's better to move the SetTimeout to the beginning.
```
function task_save_datatables()
  SetTimeout(config.save_interval*1000, task_save_datatables)

  TriggerEvent("vRP:save")

  Debug.log("save datatables")
  for k,v in pairs(vRP.user_tables) do
    vRP.setUData(k,"vRP:datatable",json.encode(v)) -- v==null?
  end
end

```

**Comment by SnaiCrys** [comment]
When a lot of players try to connect to a full server, they are stored in a strange way in the DB and die when spawned (because there is no value for hp). Note even that there is no user group
`{inventory":{"item":{"amount":5}},"thirst":0,"groups":[],"hunger":0}`

**Comment by ImagicTheCat** [comment]
Probably irrelevant for vRP 2.
