### ISSUE TITLE
vRP tables not found HELP

### ISSUE THREAD

**Issue by iNOGAMERTAG** [ImagicTheCat/vRP#406]
![30003495-25ff3dec-90be-11e7-90cc-3c84464aeb02](https://user-images.githubusercontent.com/36146324/37560779-2ef11ed4-2a15-11e8-9791-0cd5957faa00.png)
![30003497-296154f2-90be-11e7-9796-c952b0dcf11c](https://user-images.githubusercontent.com/36146324/37560780-2efafc56-2a15-11e8-8be9-5b64134dbb36.png)

**Comment by DunkoUK** [comment]
You need to set your database details in vrp/cfg/base.lua and in the server.cfg mysqlconnectionstring (at the top)

**Comment by ImagicTheCat** [comment]
Issues are not for help.
