### ISSUE TITLE
[vrpex] main menu lag

### ISSUE THREAD

**Issue by SnaiCrys** [ImagicTheCat/vRP#408]
When many players on the server and they open the main menu, sometimes the opening does not work. There are no errors in logs.

**Comment by ImagicTheCat** [comment]
Latency and the menu not opening is different: how much latency do you measure ?

**Comment by SnaiCrys** [comment]
it's not latency. It just does not open for a while and you have to press the button again.

**Comment by ImagicTheCat** [comment]
Be more precise, do they need to spam the button or they need to only press it once ?

**Comment by SnaiCrys** [comment]
press it once

1) A lot of people on the server.
2) Everyone uses the menu (the server recently turned on)
3) The player presses the button but the menu does not open, it presses again, but it still does not open.
4) After 5 seconds the player presses the button again and the menu opens immediately.

**Comment by SnaiCrys** [comment]
I added asynс to the buildmenu and it got a little better.

**Comment by ImagicTheCat** [comment]
If the menu never opens, it's probably an async call never returning. Finding the calls doing that is the hard part.

**Comment by ImagicTheCat** [comment]
Added warnings when an async returner doesn't return before a specific amount of time, it could help to solve this issue. https://github.com/ImagicTheCat/vRP/commit/b00e9cc5f5076c3bb2f9b37d2023b151a42db6d8

**Comment by mickeyunagee** [comment]
I can confirm this behavior on normal vRP.
frame time build up over time, and creates lag/latency on pulling up menu. 
Can even make people disconnect at some point, and spits out vRP task failed.

**Comment by ImagicTheCat** [comment]
Enable debug mode, use latest commits, change the MySQL driver and watch for log of too long async returners.

**Comment by SnaiCrys** [comment]
confirm

**Comment by SnaiCrys** [comment]
Yes, the problem is so serious that nothing can be done on the menu.

**Comment by ImagicTheCat** [comment]
Can't reproduce in local, what version of FiveM do you use ?

**Comment by SnaiCrys** [comment]
latest stable

**Comment by SnaiCrys** [comment]
Problem began after 
https://github.com/citizenfx/fivem/commit/03670c6e7cdcda1cbfb0fb2a7b15dc2e4ebed653
https://github.com/citizenfx/fivem/compare/e772f7e51a97...495c38ee82d2

**Comment by CryptoParts** [comment]
For me the menu does come up but its hidden as sometimes it "calls admin" when the menu is not even showing. I found if you right click first then press your menu key the menu usually comes up first time...

**Comment by ImagicTheCat** [comment]
Probably irrelevant for vRP 2.

**Comment by Chris0377** [comment]
I have a problem when i play pojavlauncher in android samsung 6.0.1.When i already download mc 1.12.2,the mouse is really really laggy.please fux this
