### ISSUE TITLE
Suggestion: Driving Licence and Weapon Licence

### ISSUE THREAD

**Issue by Zuqaa** [ImagicTheCat/vRP#41]
All in the title ^^

**Comment by Aleweadan** [comment]
Here is the ressource i found for driving licence on essentialmode i don't try anymore on vRP.

Lua code

`-- Credit : Ideo

--------------------------------------------------------------------------------------------------------------------
-- fonctions graphiques
--------------------------------------------------------------------------------------------------------------------

Keys = {
	["ESC"] = 322, ["F1"] = 288, ["F2"] = 289, ["F3"] = 170, ["F5"] = 166, ["F6"] = 167, ["F7"] = 168, ["F8"] = 169, ["F9"] = 56, ["F10"] = 57, 
	["~"] = 243, ["1"] = 157, ["2"] = 158, ["3"] = 160, ["4"] = 164, ["5"] = 165, ["6"] = 159, ["7"] = 161, ["8"] = 162, ["9"] = 163, ["-"] = 84, ["="] = 83, ["BACKSPACE"] = 177, 
	["TAB"] = 37, ["Q"] = 44, ["W"] = 32, ["E"] = 38, ["R"] = 45, ["T"] = 245, ["Y"] = 246, ["U"] = 303, ["P"] = 199, ["["] = 39, ["]"] = 40, ["ENTER"] = 18,
	["CAPS"] = 137, ["A"] = 34, ["S"] = 8, ["D"] = 9, ["F"] = 23, ["G"] = 47, ["H"] = 74, ["K"] = 311, ["L"] = 182,
	["LEFTSHIFT"] = 21, ["Z"] = 20, ["X"] = 73, ["C"] = 26, ["V"] = 0, ["B"] = 29, ["N"] = 249, ["M"] = 244, [","] = 82, ["."] = 81,
	["LEFTCTRL"] = 36, ["LEFTALT"] = 19, ["SPACE"] = 22, ["RIGHTCTRL"] = 70, 
	["HOME"] = 213, ["PAGEUP"] = 10, ["PAGEDOWN"] = 11, ["DELETE"] = 178,
	["LEFT"] = 174, ["RIGHT"] = 175, ["TOP"] = 27, ["DOWN"] = 173,
	["NENTER"] = 201, ["N4"] = 108, ["N5"] = 60, ["N6"] = 107, ["N+"] = 96, ["N-"] = 97, ["N7"] = 117, ["N8"] = 61, ["N9"] = 118
}



Menu = {}
Menu.GUI = {}
Menu.buttonCount = 0
Menu.selection = 0
Menu.hidden = true
MenuTitle = "Menu"

function Menu.addButton(name, func,args)

	local yoffset = 0.3
	local xoffset = 0
	local xmin = 0.0
	local xmax = 0.2
	local ymin = 0.05
	local ymax = 0.05
	Menu.GUI[Menu.buttonCount +1] = {}
	Menu.GUI[Menu.buttonCount +1]["name"] = name
	Menu.GUI[Menu.buttonCount+1]["func"] = func
	Menu.GUI[Menu.buttonCount+1]["args"] = args
	Menu.GUI[Menu.buttonCount+1]["active"] = false
	Menu.GUI[Menu.buttonCount+1]["xmin"] = xmin + xoffset
	Menu.GUI[Menu.buttonCount+1]["ymin"] = ymin * (Menu.buttonCount + 0.01) +yoffset
	Menu.GUI[Menu.buttonCount+1]["xmax"] = xmax 
	Menu.GUI[Menu.buttonCount+1]["ymax"] = ymax 
	Menu.buttonCount = Menu.buttonCount+1
end


function Menu.updateSelection() 
	if IsControlJustPressed(1, Keys["DOWN"])  then 
		if(Menu.selection < Menu.buttonCount -1  )then
			Menu.selection = Menu.selection +1
		else
			Menu.selection = 0
		end
	elseif IsControlJustPressed(1, Keys["TOP"]) then
		if(Menu.selection > 0)then
			Menu.selection = Menu.selection -1
		else
			Menu.selection = Menu.buttonCount-1
		end
	elseif IsControlJustPressed(1, Keys["NENTER"])  then
			MenuCallFunction(Menu.GUI[Menu.selection +1]["func"], Menu.GUI[Menu.selection +1]["args"])
	end
	local iterator = 0
	for id, settings in ipairs(Menu.GUI) do
		Menu.GUI[id]["active"] = false
		if(iterator == Menu.selection ) then
			Menu.GUI[iterator +1]["active"] = true
		end
		iterator = iterator +1
	end
end

function Menu.renderGUI()
	if not Menu.hidden then
		Menu.renderButtons()
		Menu.updateSelection()
	end
end

function Menu.renderBox(xMin,xMax,yMin,yMax,color1,color2,color3,color4)
	DrawRect(xMin, yMin,xMax, yMax, color1, color2, color3, color4);
end

function Menu.renderButtons()
	
local yoffset = 0.3
local xoffset = 0

		SetTextFont(0)
		SetTextScale(0.0,0.35)
		SetTextColour(255, 255, 255, 255)
		SetTextCentre(true)
		SetTextDropShadow(0, 0, 0, 0, 0)
		SetTextEdge(0, 0, 0, 0, 0)
		SetTextEntry("STRING") 
		AddTextComponentString(string.upper(MenuTitle))
		DrawText((xoffset + 0.05), (yoffset - 0.05 - 0.0125 ))
		Menu.renderBox(xoffset,0.2,(yoffset - 0.05),0.05,20,30,10,255)
		
		
	for id, settings in pairs(Menu.GUI) do
		local screen_w = 0
		local screen_h = 0
		screen_w, screen_h =  GetScreenResolution(0, 0)
		boxColor = {42,63,17,255}
		
		if(settings["active"]) then
			boxColor = {107,158,44,255}
		end
		SetTextFont(0)
		SetTextScale(0.0,0.35)
		SetTextColour(255, 255, 255, 255)
		SetTextCentre(true)
		SetTextDropShadow(0, 0, 0, 0, 0)
		SetTextEdge(0, 0, 0, 0, 0)
		SetTextEntry("STRING") 
		AddTextComponentString(settings["name"])
		DrawText(settings["xmin"]+ 0.05, (settings["ymin"] - 0.0125 )) 
		Menu.renderBox(settings["xmin"] ,settings["xmax"], settings["ymin"], settings["ymax"],boxColor[1],boxColor[2],boxColor[3],boxColor[4])
	 end     
end


--------------------------------------------------------------------------------------------------------------------

function ClearMenu()
	--Menu = {}
	Menu.GUI = {}
	Menu.buttonCount = 0
	Menu.selection = 0
end

function MenuCallFunction(fnc, arg)
	_G[fnc](arg)
end`

Sql

`CREATE TABLE IF NOT EXISTS `dmv` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `identifier` varchar(45) NOT NULL DEFAULT '',
  `valid` varchar(45) NOT NULL DEFAULT 'no',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;`

**Comment by Aleweadan** [comment]
Here you can find a ressource work on essentialmode for add a driving licence i don't try anymore on vRP
[https://mega.nz/#!49w1HB5A!-tOBPy8u5OQhV9XcR2Whh8og501gP1QlosU0RWEgFUo](url)

**Comment by Zuqaa** [comment]
So @ImagicTheCat ? :p

**Comment by ImagicTheCat** [comment]
Just to answer to this one, like in real life, not having a license doesn't prevent you to have weapons or drive, but cops can check you to see if you have the license. So just create an item for that, and if you don't want to sell weapons to unlicensed people, use the gunshop permission.

**Comment by Zuqaa** [comment]
Yes but i dont want a player go to a simple marker for buy a licence, i want a point (city to autoroute x) ) and if the vehicle have damage then he not receive the licence

PS: Je sais pas si je me suis bien exprimé mais j'espère que c'est lisible avec mon anglais pitoyable

**Comment by ImagicTheCat** [comment]
Do your own resource, and use the API. vRP is generic, what you want to do is specific. If you have troubles with the API, wait for the release.

**Comment by Zuqaa** [comment]
When i have error with the API vRP/tvRP You answer me as if I had make something bad...

**Comment by ImagicTheCat** [comment]
I can't, I'm not a personal support for everyone. Wait for the release, wait for someone else to help you.

**Comment by Zuqaa** [comment]
J'explique en FR c'est trop dur en EN.... Le probleme est que si tu n'aide pas une personne les personne qui suivront et qui auront le meme probleme vont te demander car il ne trouverons pas eux aussi et ce sera interminable il y aura TROPPP de ticket d'issue or si tu m'aide tu pourrais ensuite le mettre en Tuto dans le readme car je ne te cache pas qu'il est dur a comprendre que ce soit EN ou FR, il nous faudrais un tuto, je suis conscient qu'il est en BETA/ALPHA mais au moins un tuto pour expliquer comment vRP remplace le TriggerEvent/TriggerClientevent et le TriggerServerEvent pourrais aider nombre de gens a t'aider voire te donner leur addon qu'ils ont fait et j'en serais l'un des premiers, j'essaye de faire un pack de jobs pour votre addon, que vous le refusiez ou non je le finirais pour les gens qui le voudront... Voila en esperant que tu ai compris mon message 

Cordialement, Lorenzo

**Comment by ImagicTheCat** [comment]
Bon, je pensais être clair, mais tu me force un peu la main, c'est la seule fois que je te répondrai en français. Il y a déjà un tutoriel sur le README, le README sert à référencer, expliquer un minimum, mais c'est tout. Une fois que j'aurais fait un topic sur FiveM, les gens pourront s'entraider, et je serais le premier à répondre aux questions sur le système de tunnel et de proxy. Maintenant, tu n'as toujours pas compris à quoi sert la section issue, son but est uniquement de rapporter un problème ou, si modéré, proposer une fonctionnalité au code de vRP, et uniquement vRP. Il ne s'agit pas d'une section d'aide. 
Si tu ne peux pas comprendre ça et que tu continues à te servir du système d'issue pour de l'aide ou la résolution de tes propres problèmes, tu sera bloqué. Comprends bien que je n'ai aucun intérêt à faire ça, car plus le nombre de personne rapportant les bugs est grand, plus on peut les résoudre rapidement. De plus, ça pourrait décourager d'autres personnes à rapporter des bugs ou proposer des fonctionnalités, donc merci de garder cet endroit sain et sans embrouille.

**Comment by Zuqaa** [comment]
Encore une fois j'ai l'impression d'avoir fais un truc de mal or je dis juste qu'un tuto simplifier avec plus d'instructions serais le bienvenu, je sais qu'il y a un tuto, je l'ai vu, mais il n'explique pas assez bien au gens comment il remplace le TriggerXXX, de plus je ne voulais pas créer d'embrouilles désolé si c'est l'impression que j'ai donné :( (c'est d'ailleurs pour ça que j'ai dis a la fin de mon message "en esperant que tu ai compris mon message", pour ne pas qu'il soit mal interpréter), Bref désolé du dérangement, a partir de maintenant je vais essayer de me débrouiller seul au niveau de comprendre le systeme vRP, comment il marche ^^ 

Bonne continuation a toi quand même, si il ya des bugs je viendrais les rapporter comme toujours !

Cordialement, Lorenzo
