### ISSUE TITLE
vrpex error

### ISSUE THREAD

**Issue by SuperTSGAMES** [ImagicTheCat/vRP#411]
here is this mistake

Initializing Mono
Initializing Mono completed
Hello!
Found new resource fivem in F:/server\Vrpex-Server/resources//fivem
Found new resource fivem-awesome1501 in F:/server\Vrpex-Server/resources//fivem-awesome1501
Found new resource fivem-map-hipster in F:/server\Vrpex-Server/resources//fivem-map-hipster
Found new resource fivem-map-skater in F:/server\Vrpex-Server/resources//fivem-map-skater
Found new resource pNotify in F:/server\Vrpex-Server/resources//pNotify
Found new resource runcode in F:/server\Vrpex-Server/resources//runcode
Found new resource vrp in F:/server\Vrpex-Server/resources//vrp
Found new resource vrp_adv_garages in F:/server\Vrpex-Server/resources//vrp_adv_garages
Found new resource vrp_adv_homes in F:/server\Vrpex-Server/resources//vrp_adv_homes
Found new resource vrp_armorshop in F:/server\Vrpex-Server/resources//vrp_armorshop
Found new resource vrp_barbershop in F:/server\Vrpex-Server/resources//vrp_barbershop
Found new resource vrp_bars in F:/server\Vrpex-Server/resources//vrp_bars
Found new resource vrp_basic_menu in F:/server\Vrpex-Server/resources//vrp_basic_menu
Resolved live-internal.fivem.net:30110 to 62.210.162.18:30110
Found new resource vrp_basic_mission in F:/server\Vrpex-Server/resources//vrp_basic_mission
Found new resource vrp_carwash in F:/server\Vrpex-Server/resources//vrp_carwash
Found new resource vrp_chairs in F:/server\Vrpex-Server/resources//vrp_chairs
Found new resource vrp_cmds in F:/server\Vrpex-Server/resources//vrp_cmds
Found new resource vrp_dmvschool in F:/server\Vrpex-Server/resources//vrp_dmvschool
Found new resource vrp_drugs in F:/server\Vrpex-Server/resources//vrp_drugs
Found new resource vrp_esx_menu in F:/server\Vrpex-Server/resources//vrp_esx_menu
Found new resource vrp_esx_phone in F:/server\Vrpex-Server/resources//vrp_esx_phone
Found new resource vrp_firstid in F:/server\Vrpex-Server/resources//vrp_firstid
Found new resource vrp_group_display in F:/server\Vrpex-Server/resources//vrp_group_display
Found new resource vrp_home_spawn in F:/server\Vrpex-Server/resources//vrp_home_spawn
Found new resource vrp_hotkeys in F:/server\Vrpex-Server/resources//vrp_hotkeys
Found new resource vrp_id_display in F:/server\Vrpex-Server/resources//vrp_id_display
Found new resource vrp_lees_phone in F:/server\Vrpex-Server/resources//vrp_lees_phone
Found new resource vrp_levys_phone in F:/server\Vrpex-Server/resources//vrp_levys_phone
Found new resource vrp_loadfreeze in F:/server\Vrpex-Server/resources//vrp_loadfreeze
Found new resource vrp_moneydrop in F:/server\Vrpex-Server/resources//vrp_moneydrop
Found new resource vrp_mysql in F:/server\Vrpex-Server/resources//vrp_mysql
Found new resource vrp_nocarjack in F:/server\Vrpex-Server/resources//vrp_nocarjack
Found new resource vrp_paycheck in F:/server\Vrpex-Server/resources//vrp_paycheck
Found new resource vrp_robbery in F:/server\Vrpex-Server/resources//vrp_robbery
Found new resource vrp_scoreboard in F:/server\Vrpex-Server/resources//vrp_scoreboard
Found new resource vrp_tattoos in F:/server\Vrpex-Server/resources//vrp_tattoos
Found new resource vrp_voice_display in F:/server\Vrpex-Server/resources//vrp_voice_display
Found new resource race in F:/server\Vrpex-Server/resources//[gamemodes]/race
Found new resource race-test in F:/server\Vrpex-Server/resources//[gamemodes]/race-test
Found new resource channelfeed in F:/server\Vrpex-Server/resources//[gameplay]/channelfeed
Found new resource irc in F:/server\Vrpex-Server/resources//[gameplay]/irc
Found new resource obituary in F:/server\Vrpex-Server/resources//[gameplay]/obituary
Found new resource obituary-deaths in F:/server\Vrpex-Server/resources//[gameplay]/obituary-deaths
Found new resource playernames in F:/server\Vrpex-Server/resources//[gameplay]/playernames
Found new resource mapmanager in F:/server\Vrpex-Server/resources//[managers]/mapmanager
Found new resource baseevents in F:/server\Vrpex-Server/resources//[system]/baseevents
Found new resource chat in F:/server\Vrpex-Server/resources//[system]/chat
Found new resource hardcap in F:/server\Vrpex-Server/resources//[system]/hardcap
Found new resource rconlog in F:/server\Vrpex-Server/resources//[system]/rconlog
Found new resource scoreboard in F:/server\Vrpex-Server/resources//[system]/scoreboard
Found new resource sessionmanager in F:/server\Vrpex-Server/resources//[system]/sessionmanager
Found new resource spawnmanager in F:/server\Vrpex-Server/resources//[system]/spawnmanager
Found new resource betaguns in F:/server\Vrpex-Server/resources//[test]/betaguns
Found new resource gameInit in F:/server\Vrpex-Server/resources//[test]/gameInit
Found new resource keks in F:/server\Vrpex-Server/resources//[test]/keks
Started resource sessionmanager
Started resource mapmanager
Started resource chat
Started resource spawnmanager
Started resource fivem
Started gametype Freeroam
Started resource hardcap
Started resource rconlog
Started resource scoreboard
Started resource playernames
[vRP] init base tables
Started resource vrp
Loaded mysql.net, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null into ScriptDomain_1930769650
Exception loading assembly I18N: System.IO.FileNotFoundException: Unable to find the specified file.

Server stack trace:
  at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR (System.Int32 errorCode) [0x0000a] in <0123fd5b1a1040fe9d70a7e0d4b28acb>:0
  at (wrapper cominterop) CitizenFX.Core.IScriptHost:OpenHostFile (string)
  at (wrapper cominterop-invoke) CitizenFX.Core.IScriptHost:OpenHostFile (string)
  at CitizenFX.Core.MonoScriptRuntime+WrapScriptHost.OpenHostFile (System.String fileName) [0x00000] in C:\gl\builds\4ff63adb\0\cfx\fivem\code\client\clrcore\MonoScriptRuntime.cs:254
  at (wrapper remoting-invoke-with-check) CitizenFX.Core.MonoScriptRuntime+WrapScriptHost:OpenHostFile (string)
  at (wrapper xdomain-dispatch) CitizenFX.Core.MonoScriptRuntime+WrapScriptHost:OpenHostFile (object,byte[]&,byte[]&,string)

Exception rethrown at [0]:
  at (wrapper xdomain-invoke) CitizenFX.Core.MonoScriptRuntime+WrapScriptHost:OpenHostFile (string)
  at CitizenFX.Core.InternalManager.LoadAssembly (System.String name) [0x00000] in C:\gl\builds\4ff63adb\0\cfx\fivem\code\client\clrcore\InternalManager.cs:112
[vRP/C#] Load MySQL app.
Instantiated instance of script vRP.MySQL.
Started resource vrp_mysql
Started resource vrp_basic_mission
Started resource vrp_armorshop
Started resource vrp_barbershop
Started resource vrp_basic_menu
Started resource vrp_carwash
Started resource vrp_chairs
Started resource vrp_cmds
Started resource vrp_dmvschool
Started resource vrp_drugs
Started resource vrp_esx_menu
Started resource vrp_group_display
Started resource vrp_home_spawn
Started resource vrp_hotkeys
Started resource vrp_id_display
Started resource vrp_lees_phone
Started resource vrp_levys_phone
Started resource vrp_loadfreeze
Started resource vrp_moneydrop
Started resource vrp_nocarjack
Started resource vrp_paycheck
Started resource vrp_robbery
Started resource vrp_scoreboard
Started resource vrp_tattoos
Started resource vrp_voice_display
Started resource pNotify
Started resource vrp_bars
Authenticating server license key...
Server license key authentication succeeded. Welcome!
cfx> Sending heartbeat to live-internal.fivem.net:30110
[vRP] DB driver "vrp_mysql" not initialized yet (42 prepares cached, 6 queries cached).
Started resource fivem-map-skater
Started map fivem-map-skater
[vRP] DB driver "vrp_mysql" not initialized yet (42 prepares cached, 7 queries cached).
[vRP] DB driver "vrp_mysql" not initialized yet (42 prepares cached, 7 queries cached).

**Comment by ScottUK** [comment]
I also get this 🤔

**Comment by WolfM3ST3R** [comment]
Use this db-driver https://github.com/ImagicTheCat/vRP-db-drivers!

**Comment by ImagicTheCat** [comment]
`vrp_mysql` has crappy code, but it should work even with the error message. Anyway, people have developed better MySQL resources, and now vRP can use them using bridges, called vRP SQL "drivers".
