### ISSUE TITLE
vrp_mysql/MySQL.lua not found

### ISSUE THREAD

**Issue by splashlucas** [ImagicTheCat/vRP#412]
For some reason, the MySQL.lua in not included in vrp_mysql which 4 different addons try to access am I missing something?
My server startup looks like this: https://pastebin.com/BzhK6kZZ
I tried testing with vrp_ghmattimysql but it does the same thing

**Comment by splashlucas** [comment]
I'm using vrpex

**Comment by ImagicTheCat** [comment]
And they're probably not.
