### ISSUE TITLE
Error of Voip

### ISSUE THREAD

**Issue by NathanFL** [ImagicTheCat/vRP#415]
randomly when you log in I get this error, I am using the latest vrp and only the vrp and fivem files started in server.cfg  

<img src="https://cdn.discordapp.com/attachments/412008651767939072/433191578740195329/erro.png" title="source: imgur.com" /></a>

**Comment by NathanFL** [comment]
I've already moved to several turn / stun configuration servers and went back to the original and also proceeded to give the error

**Comment by bradxy** [comment]
One person got the same error on my server yesterday, he restarted FiveM and it has not happened again so far... 

Error: Uncaught ReferenceError: libopus is not defined Script: nui://vrp/gui/AudioEngine.js Line:31 Column 3 StackTrace: ReferenceError: libopus is not defined

![voip error](https://user-images.githubusercontent.com/36649225/38630399-aec592c0-3d6b-11e8-9038-5604a00e27ff.jpg)

**Comment by Drew101** [comment]
I am not getting this more and more... When the error happens no other screen elements seem to load, only option is to relog...
