### ISSUE TITLE
Feature Request - vRP.closeItemTransformer(user_id)

### ISSUE THREAD

**Issue by Dylan-Duault** [ImagicTheCat/vRP#419]
This would allow us to close a connection between a player and an item_transformer.
Could be used to cancel the start of an item_transformer if some conditions are not met.

![image](https://user-images.githubusercontent.com/1349678/38929240-f89a39e6-430b-11e8-82d1-3ba5b3d1ec91.png)

**Comment by ImagicTheCat** [comment]
In vRP 2, item transformers have per recipe permissions ("cancel the start") and you can do more advanced stuff with the API https://github.com/ImagicTheCat/vRP/blob/dev/doc/dev/modules/item_transformer.adoc#transformer.
