### ISSUE TITLE
Music radio

### ISSUE THREAD

**Issue by SnaiCrys** [ImagicTheCat/vRP#420]
After the last Fivem update the radio does not work correctly. In the left ear there is noise, and in the right music plays without limit on the distance. 3d positioning does not work.

**Comment by GTA-Vanyangel** [comment]
I tested it 2 days ago, when i set the radio from admin menu --> Custom Audiosource: I heard it without spacialization and no distance limit BUT the other players were hearing it correctly.

Was any players near you hearing it without spacialization too ?

**Comment by SnaiCrys** [comment]
associated with https://github.com/ImagicTheCat/vRP/issues/399

**Comment by ImagicTheCat** [comment]
I can't reproduce the issue, and it doesn't seem related to https://github.com/ImagicTheCat/vRP/issues/399.

**Comment by ImagicTheCat** [comment]
Okay I updated to canary and I had sound issues, unfortunately, this is not related to vRP, you can report this to FiveM.
