### ISSUE TITLE
Lang.lua File

### ISSUE THREAD

**Issue by ResaloliPT** [ImagicTheCat/vRP#425]
Typo in File name Luang.lua instead of Lang.lua at vrp/lib/Luag.lua

Might be intentional or not but some addons are crying over it.

"Error loading script base.lua in resource vrp: lib/utils.lua:49: resource file vrp/lib/Luang.lua not found"

**Comment by ImagicTheCat** [comment]
Not a typo, make sure that all resources used are up-to-date with vRP (master).
