### ISSUE TITLE
[ISSUE] gui/Progressbar.js cfg error

### ISSUE THREAD

**Issue by Melonendk** [ImagicTheCat/vRP#430]
So aperently im getting the issue cfg is not defined on line 52 in progressbar.js in gui

I just added on line 1 -> `var cfg = {}`
And then the error removed itself

**Comment by ImagicTheCat** [comment]
This is not a fix, the config would still be empty. The NUI seems to do weird stuff, no specified order of initialization, no idea why the config table is not passed to JS for some people.

**Comment by Lynex0** [comment]
i have the same issue

**Comment by rpgsa** [comment]
I am also getting the same error except mines on line 51 which is
var width = cfg.anchor_minimap_width/anchor.length; //divide horizontal map space by number of pbars
Any ideas on this?

Thanks
Aaron

**Comment by rpgsa** [comment]
Well I just did a complete reinstall of this and now it works. Strange. Just have to try and figure out why the map flickers..

**Comment by rpgsa** [comment]
vsync was the reason why my screen flickered! D'oh!
