### ISSUE TITLE
[Report Bug] Dupe Weapons

### ISSUE THREAD

**Issue by LeoSHK** [ImagicTheCat/vRP#432]
The Save Weapons to Inventory option, by pressing the ENTER key many times, is duplicating the weapon / ammo items in the inventory.
Using the Police Menu / modules / police.lua

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/commit/cb0164d67cc859e24d7ac378ceeecd092bad8578
