### ISSUE TITLE
Loading issue

### ISSUE THREAD

**Issue by jskov9850** [ImagicTheCat/vRP#438]
When players attempt to sign in without Steam, they get rejected and then a message saying they have to use Steam before they are able to join the server.

However, when they open Steam after trying to sign in without it, they get stuck in the loading screen. Their name isn't visible anywhere, but they can type in chat.

Any tips on this one?

**Comment by Drew101** [comment]
When it rejects them your need to disconnect them from vrp, AddEventHandler("vRP:playerLeave",function(user_id, source) end)

**Comment by ImagicTheCat** [comment]
Probably not related to vRP.
