### ISSUE TITLE
Garage permission

### ISSUE THREAD

**Issue by Kappiii** [ImagicTheCat/vRP#439]
I do this 

  ["politi-biler"]  = {police.cadet
    _config = {blipid=50,blipcolor=4},
    ["police3"] = {"Politi bil 3", 0, ""},
    ["police5"] = {"Politi bil 5", 0, ""},
    ["police7"] = {"Politi bil 7", 0, ""},
    ["police8"] = {"Politi bil 8", 0, ""}

How is it to add a police cadet group for my garage?

**Comment by mickeygeecom** [comment]
Look at this example:
```
["police"] = {
    _config = {vtype="car",blipid=56,blipcolor=38,permissions={"police.vehicle"}},
["spawnname1"] = {"Displayed name",0, "description #1"},
["spawnname2"] = {"Displayed name",0, "description #2"}
},
```

**Comment by Kappiii** [comment]
Im also having troble with the police weapons and gang house/weapon
