### ISSUE TITLE
Getting this every time I start the server.

### ISSUE THREAD

**Issue by bigbluu722** [ImagicTheCat/vRP#440]
https://pastebin.com/qUDAF3fb

Not sure what to do about this error, any assistance would be appreciated.

**Comment by rpgsa** [comment]
Hi,
Have you specified your sql database credentials in the cfg/base.lua file?
The error is here
Unable to connect to any of the specified MySQL hosts.

If you look at that file you will see this:
-- mysql credentials
cfg.db = {
  driver = "vrp_mysql",
  host = "localhost",
  database = "YOUR DATABASE NAME",
  user = "YOUR DATABASE USERNAME",
  password = "YOUR DATABASE PASSWORD"
}

**Comment by rpgsa** [comment]
Just checked further down your file and saw this:
-- mysql credentials
cfg.db = {
  host = "127.0.0.1", -- database ip (default is local)
  database = "vrpfx",   -- name of database
  user = "root",    --  database username
  password = ""   -- password of your database
}
Have you created the database "vrpfx" and perhaps change the 127.0.0.1 to localhost.

**Comment by bigbluu722** [comment]
I've done that yes, I noted in the pastebin that the details for some reason reset every time the server starts back up.

**Comment by bigbluu722** [comment]
Seems I've fixed it with a full reinstall. Going to go ahead and close this.
-V
