### ISSUE TITLE
Item transformer Bug farming away, and itens disapearing from vehicle inventory

### ISSUE THREAD

**Issue by bazantew** [ImagicTheCat/vRP#441]
Players off my serve, is reporting to me, the itens is desapearing from Inventory from vehicle.
And have a item transformer bug. Image to explain. Help-me please.
![img-20180928-wa0023](https://user-images.githubusercontent.com/13602902/46221528-e5b64700-c323-11e8-9820-c55327ad9734.jpg)

**Comment by ImagicTheCat** [comment]
Insufficient info, may be obsolete.
