### ISSUE TITLE
AudioEngine.js Error

### ISSUE THREAD

**Issue by Kalyz** [ImagicTheCat/vRP#442]
Sometimes I log into the server and I get an error, and also when I try to make a call to another player

Error: Uncaught RefereceError: libopus is not defined Script: nui://vrp/gui/AudioEngine.js Line: 300 Column: 18 StackTrace: ReferenceError: libopus is not defined

**Comment by ImagicTheCat** [comment]
duplicate https://github.com/ImagicTheCat/vRP/issues/415
