### ISSUE TITLE
Quick Admin menu

### ISSUE THREAD

**Issue by Kappiii** [ImagicTheCat/vRP#443]
How do i make a menu for F9 or F8 like an admin menu but short and fast?
and the same with police menu how do i make it and where do i put it in?

**Comment by CAHenson** [comment]
reference other uses of vRP.openMenu, should take you where you want to go.

**Comment by DunkoUK** [comment]
Check out my git under vRP/modules/hotkeys.lua and vrp/hotkeys/hotkeys.lua for a basic guide, though those are still a WIP

**Comment by Kappiii** [comment]
We can't find fix it? or rather make it

**Comment by Kappiii** [comment]
Can you make one for us we can't figure it out?

**Comment by ImagicTheCat** [comment]
Not related to vRP core, use the FiveM forum.
