### ISSUE TITLE
[Bug] Losing OwnerShip of Vehicle.

### ISSUE THREAD

**Issue by TerbSEC** [ImagicTheCat/vRP#445]
Hello.
If you access to an Interior or something else that Teleport you away from your personally vehicle.
Then you will lose the Ownership and will not be able to put your Vehicle into your garage again.
It works fine it the Vehicle gets DV, then you can take it out again..

**Comment by ImagicTheCat** [comment]
What version ? 0.5, 1.0 (vrpex) ?

**Comment by TerbSEC** [comment]
I think its on all versions? :) Always been a bug i think.
We are using Before vrpex merge

**Comment by ImagicTheCat** [comment]
vRP doesn't aim to do backward support, that's the reason people should update their resources to the last stable version so everyone can update the framework.

**Comment by yuricampolongo** [comment]
Can you tell us which part of VRP 2 solves this issue? I really need to fix that in my server to disable /dv.

I will be really gladful if you can just tell me which part of the code cause the ownership loss..
