### ISSUE TITLE
[bug] no owned vehicle near 

### ISSUE THREAD

**Issue by DimaCooper** [ImagicTheCat/vRP#447]
Hi, i'm using the latest vrp and i have problem with vehicles. i was testing it about 2 weeks and trying to fix it(unsuccessfully). When i take my cars from garage its ok, i can open vehicle menu and my cars are "mine". But when i ride with other players (and go far away from) my cars become not mine "no owned vehicle near" and other player can't open vehicle menu too  "no owned vehicle near". p.s sorry for my bad english.

**Comment by DimaCooper** [comment]
do you need some help with vrp 2 ? I'm not a pro coder, bun know mach about scripting with lua. i'm almost finished my own server using vrp1.

**Comment by SirOficial** [comment]
What part of the code in vrp 2 did you use to solve this problem? 
I am trying to implement in my vrp 1.0

**Sorry bad English**
