### ISSUE TITLE
UI | Food and water bar dosen't show!

### ISSUE THREAD

**Issue by Hermansen03** [ImagicTheCat/vRP#449]
My Hunger bar is missing don’t know what to do 🗡 

I have a brand new vrp/modules/survival.lua and vrp/gui/progressbar.js from the ImagicTheCat vRP.

MY UI -->
![image](https://user-images.githubusercontent.com/44872330/48708876-161fb080-ec04-11e8-8989-b53fd87a0b8a.png)

**Comment by ImagicTheCat** [comment]
I don't think you are using vRP properly or even know what version you are using.

**Comment by xSamu** [comment]
Try send it and then i can check
