### ISSUE TITLE
Add permissions for buy vehicle/weapon

### ISSUE THREAD

**Issue by Zuqaa** [ImagicTheCat/vRP#45]
All in the title :p

**Comment by ImagicTheCat** [comment]
You need to set the shop group permission.

**Comment by Zuqaa** [comment]
Yes but how to set permission only for the shop police ?

**Comment by ImagicTheCat** [comment]
You need to create a group and set the permission in the config property, next to blipid, etc...

**Comment by Zuqaa** [comment]
Ok thx i just put vRP.hasGroup(user_id,"police")??

**Comment by ImagicTheCat** [comment]
```lua
_config { permission = "my.permission" }
```
Do this, then add the permission to the group of your choice, to have access to the shop.

**Comment by Zuqaa** [comment]
Ok thx ^^
