### ISSUE TITLE
I have a problem with my database

### ISSUE THREAD

**Issue by syndicate1984** [ImagicTheCat/vRP#451]
https://gyazo.com/611df3c2a5f1949394793ae2b021b313
what i can do about it?

**Comment by DarkCrystals** [comment]
I believe I am having the same issue, I've tried fiddling with the database settings within VRP and GHMattiMySQL.
(https://user-images.githubusercontent.com/23016491/48872195-12339000-edb6-11e8-8436-a1bda62d36a2.png)

**Comment by ImagicTheCat** [comment]
You can read the documentation.
