### ISSUE TITLE
Death respawn

### ISSUE THREAD

**Issue by bradxy** [ImagicTheCat/vRP#453]
When dead and you disconnect then re-connect seems to not tp you to city hall after killing you

**Comment by ImagicTheCat** [comment]
Couldn't reproduce, check your player_state spawn option.

**Comment by bradxy** [comment]
When i load up the svr, kill myself, wait.. then disconnect, connect, It flashed weird then does not teleport me to city hall.

If i kill myself then let myself die it spawns normal to city hall.

**Comment by bradxy** [comment]
It would be nice when u are in coma to have a option to press E to respawn or call ems in your phone in a notification. If you disconnect while in coma, when u re-spawn u will ask "press E to respawn or call ems"

**Comment by bradxy** [comment]
Seem fine after some linux server updates
