### ISSUE TITLE
Feature: Add to group count

### ISSUE THREAD

**Issue by bradxy** [ImagicTheCat/vRP#454]
If in any way could you make group count a permission or title, Most servers have more than one police department, mechanic+ and more

**Comment by ImagicTheCat** [comment]
Good point, I'm not using the group properties anyway and the permission `!group.<name>` still exists to keep the actual behavior.

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/commit/4581bd6e4bdfc697029f134c2975048850e8ec38
