### ISSUE TITLE
Vehicle spawn with plate

### ISSUE THREAD

**Issue by bradxy** [ImagicTheCat/vRP#456]
Seems to happen that sometimes the vehicle plates spawn with P000AAA, when leaving, then re-connecting the server session, possibly random...

Then when the plate is like that, there seems to be no way to re-own the vehicle if it is lost, forcing a relog, as the garage is stating it is out.

**Comment by ImagicTheCat** [comment]
What is the frenquency ? Does it happen when you switch between characters without disconnecting ?

**Comment by bradxy** [comment]
The plate things happens often, yesterday was the first time it lost ownership and was unable to re-gain it white the plate was like that. Seems fine when switching characters...

Is it unable to get the registration if it spawns the car before the player...

**Comment by ImagicTheCat** [comment]
Use the last version (https://github.com/ImagicTheCat/vRP/commit/eb0670d8c7b8d3dd7d2e4722b316b54e61b92bc3), you can close the issue yourself if it's not happening anymore.

**Comment by bradxy** [comment]
resolved #456
