### ISSUE TITLE
Home Radio Audio Error

### ISSUE THREAD

**Issue by bradxy** [ImagicTheCat/vRP#460]
Since the VoIP updates the home radio no longer works and gives this error on all stations

nui://vrp/gui/index.html:0, MediaElementAudioSource outputs zeroes due to CORS access restrictions for http://198.7.58.248:15402/stream

nui://vrp/gui/index.html:0, MediaElementAudioSource outputs zeroes due to CORS access restrictions for http://mp3.stream.tb-group.fm/tt.ogg

**Comment by Tousteack** [comment]
Hi,
Same problem with the original radio...
Maybe because of the chrome 11 autoplay (MAJ Dec 2018) ?
Please help.

**Comment by bradxy** [comment]
Is it the same tho, this was fix recently in the dev branch and was working again, but some more changes were made with the audio engine in the dev branch since it stopped working again...

**Comment by ImagicTheCat** [comment]
Browsers are a mess. This should fix it. https://github.com/ImagicTheCat/vRP/commit/aa53b3933f19d0b930336ec791cdc11088750212
