### ISSUE TITLE
 DB driver 

### ISSUE THREAD

**Issue by cosminwindox** [ImagicTheCat/vRP#461]
Hello, im trying to start the server in linux but give me this error...

[vRP] DB driver "ghmattimysql" not initialized yet (44 prepares cached, 7 queries cached).

**Comment by ImagicTheCat** [comment]
Issues are not for help.

**Comment by donnes** [comment]
@ImagicTheCat It's not a help... It's a real issue with your ghmattimysql bridge library.

**Comment by nloyola** [comment]
ghmattimysql only works in Winblows (MS Windows). Too bad we cant use vRP in Linux!
