### ISSUE TITLE
Phone call error

### ISSUE THREAD

**Issue by Origintk** [ImagicTheCat/vRP#462]
When I try to call another player it generates the following error

nui://vrp/gui/AudioEngine.js:10, The Web Audio autoplay policy will be re-enabled in Chrome 71 (December 2018). Please check that your website is compatible with it. https://goo.gl/7K7WLu
nui://vrp/gui/lib/libopus.wasm.js:1, wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
nui://vrp/gui/lib/libopus.wasm.js:1, falling back to ArrayBuffer instantiation
 nui://vrp/gui/lib/libopus.wasm.js:1, failed to asynchronously prepare wasm: CompileError: WebAssembly Instantiation: BufferSource argument is empty
nui://vrp/gui/lib/libopus.wasm.js:1, CompileError: WebAssembly Instantiation: BufferSource argument is empty
nui://vrp/gui/lib/libopus.wasm.js:1, CompileError: WebAssembly Instantiation: BufferSource argument is empty
 nui://vrp/gui/index.html:0, Uncaught (in promise) abort({}). Build with -s ASSERTIONS=1 for more info.
 nui://vrp/gui/lib/libopus.wasm.js:1, Uncaught TypeError: Cannot read property 'apply' of undefined

**Comment by ImagicTheCat** [comment]
Unfortunately old versions of vRP will have broken features as some dependencies (here libopusjs.wasm) will be unavailable (rawgit shutdown) or incompatible (was using master instead of a specific commit).

**Comment by ImagicTheCat** [comment]
**Fix:**
Because CEF/FiveM NUI has some URI metadata issues, the web assembly file (.wasm) had to be loaded from an external source; a CDN. My mistake was to not use a specific version for the file in the CDN link, so now the file is newer and incompatible with old versions of vRP. You can replace the wasm file URI by `http://cdn.jsdelivr.net/gh/ImagicTheCat/libopusjs@c1bced812533ba45290083cf9473de697cb4f4e7/dist/libopus.wasm` at https://github.com/ImagicTheCat/vRP/blob/master/vrp/gui/index.html#L7 . Players may require to clear their FiveM CEF cache too.

**Comment by Krest22** [comment]
I need help. I think only you can help me. In game I don't see menu of server and UI. 
[    245985] [    GTAProcess]        CrBrowserMain/ nui://vrp/gui/lib/libopus.wasm.js:7172, abort("on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)"). Build with -s ASSERTIONS=1 for more info.
[    245985] [    GTAProcess]        CrBrowserMain/ nui://vrp/gui/lib/libopus.wasm.js:7173, abort("on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)"). Build with -s ASSERTIONS=1 for more info.
[    245985] [    GTAProcess]        CrBrowserMain/ nui://vrp/gui/index.html:0, Uncaught (in promise) abort("abort(\"on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)\"). Build with -s ASSERTIONS=1 for more info."). Build with -s ASSERTIONS=1 for more info.
