### ISSUE TITLE
Police Drag

### ISSUE THREAD

**Issue by bradxy** [ImagicTheCat/vRP#464]
Police Drag does not seem to be working

**Comment by bradxy** [comment]
I will test further, i saw the changes for follow while cuffed so that may help.

**Comment by ImagicTheCat** [comment]
Did you exclude other resources while testing ?

**Comment by AceDax** [comment]
I am also having this issue and yes tested with a clean server


out of curiosity is it supposed to force the other player to follow you or does it work like other servers where it attaches their ped to you ped? I haven't seen it work yet so I don't know what I should be looking for

**Comment by SirOficial** [comment]
I have the same problem...

**Comment by Littledevill** [comment]
same problem and without drag the police are basically useless making roleplay for them impossible :/ really needs fixing please :)

**Comment by NotKrma** [comment]
The same problem here..

**Comment by bradxy** [comment]
@ImagicTheCat Hey can we get your expert knowledge to look into this problem, we all loved the follow drag option and no one can get it to work :(
