### ISSUE TITLE
Vehicles

### ISSUE THREAD

**Issue by bradxy** [ImagicTheCat/vRP#465]
Some times vehicles will de-spawn, in this case my trailer de-spawned, and they don't spawn back even tho I have that variable set to true in garage client to re-spawn them periodically...  When they de-spawn vrp thinks they are still out.. A switch character or relog re-spawns the vehicle...

This may be a fivem/linux problem as it seems they are still sorting that one out...

**Comment by bradxy** [comment]
Seems to happen quite often when inside a ipl business for more then 3 minutes..

**Comment by ImagicTheCat** [comment]
Try with vRP 2 only to exclude other resources behavior.

**Comment by bradxy** [comment]
tested with freshly configured vrp2. When vehicles de-spawn randomly, vrp will not re-spawn them, vrp thinks the vehicle is still out..

Is there a way to better detect if a vehicle is out, so vrp can replace it?

**Comment by ImagicTheCat** [comment]
Problem: vehicles are expected to not despawn. Otherwise they will respawn in more cases when it's not expected.

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/commit/85b0e35578a88adccd8e628dccafa079fd4ee9cb
