### ISSUE TITLE
Related to blips

### ISSUE THREAD

**Issue by hartturmch** [ImagicTheCat/vRP#466]
hey guys, how can i change size of blips?
like, skinshops or garages, how do i set it to be smaller?
thanks

**Comment by ImagicTheCat** [comment]
Scale and other properties of blips are not availables for `PoI` map entity (if speaking about vRP 2), they may be added. This is a feature request.

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/commit/9c92788b1743db182540be3dfaaaf71b24e73638
