### ISSUE TITLE
[Feature request] Coma and EMS

### ISSUE THREAD

**Issue by AceDax** [ImagicTheCat/vRP#467]
so the automatic respawn is a nice feature however it has one major flaw. 

the auto respawn feature actually hurts any kind of RP from a medic, the medics are forced to revive players immediately or run the risk of the auto respawn kicking in before RP is finished, further if there are no EMS online or criminal players don't want to get caught so they just don't call ems, players are forced to sit out for 10 minutes while they wait for respawn

I would like to suggest changing it from automatic respawn to  a system where you have to wait 2 or 3 minutes after the initial wait players will then be prompted to respawn using ether a chat command or a key press this wait if EMS is on the way or there is active medical RP going on they can wait to get revived. I personally think this would open up a lot of opportunities for medical RP especially with larger population servers

**Comment by NexzTV** [comment]
I like the idea if you press a "key" the respawn time will be 2-3 more minutes to get a medic before you respawn.

**Comment by Janicki92** [comment]
I agree, this would be best!  Make them wait for a certain period before they can respawn regardless of EMS or not, and then after that, they have the "option" to respawn or continue to wait for EMS if they are close or a message has shown they are on their way!

**Comment by ImagicTheCat** [comment]
No min time for now. https://github.com/ImagicTheCat/vRP/commit/7a3cd45e54b426c70a4ca49cbe94879ea072e4d2

**Comment by AceDax** [comment]
love it so far, can't wait for a minimum time. thank you @ImagicTheCat

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/commit/f476342c19b6158cf1319ded1e9f5ae7fab2f4cf
