### ISSUE TITLE
How to be a cop

### ISSUE THREAD

**Issue by Ykkris** [ImagicTheCat/vRP#47]
Hi, when I go to the computer or cloakroom nothing happen. I've added myself to the police group.

**Comment by ImagicTheCat** [comment]
Did you update your cfg files ? Do you have the police functions in your main menu ? If not, you didn't added exactly the police group (if you added a space, a return, a capital letter, etc).

**Comment by Zuqaa** [comment]
@ImagicTheCat I have make a systeme of rank for police (cadet,sergent,lieutenant and chef), i have add more ATM and fix one bugged atm, i can send my files ? ^^

PS: The bugged atm is at position -711 in the config file ;)

**Comment by ImagicTheCat** [comment]
@Zuqaa Please don't overload issues with unrelated talks. Config files are here for example, simples, and not forcing a way of thinking by adding pre-created ranks. Thanks for the ATM.

**Comment by Aleweadan** [comment]
Sorry for my unrelated message too but I Just want to adress message to Zuqaa in french.

Salut Zuqaa as tu un mail avec lequel je pourrais te parler ?

**Comment by Zuqaa** [comment]
No mail it's private but i contact me on my forum www.evasionrp.eu

**Comment by Aleweadan** [comment]
Ok

**Comment by Ykkris** [comment]
Fixed thank you
