### ISSUE TITLE
Bug: Abusing item_transformer / Area detection

### ISSUE THREAD

**Issue by mickeygeecom** [ImagicTheCat/vRP#476]
It has come to my attention that it's possible to abuse the item_transformer.
If spam-hitting "Enter" while jumping out of a zone where you can transform stuff, it will continue the process while not in the zone.

Already tried reducing the wait to 25 ms without any luck. 

@ImagicTheCat - any pointers, or possible fix?

I suggest it's related to vrp\client\map.lua
```lua
-- areas triggers detections

Citizen.CreateThread(function()
  while true do
    Citizen.Wait(100)

    local px,py,pz = tvRP.getPosition()
    for k,v in pairs(areas) do

      -- detect enter/leave
     local player_in = (GetDistanceBetweenCoords(v.x,v.y,v.z,px,py,pz,true) <= v.radius and math.abs(pz-v.z) <= v.height)

      if v.player_in and not player_in then -- was in: leave
        vRPserver.leaveArea({k})
      elseif not v.player_in and player_in then -- wasn't in: enter
        vRPserver.enterArea({k})
      end

      v.player_in = player_in -- update area player_in
    end
  end
end)
```

**Comment by bradxy** [comment]
This is fixed in vRP2

**Comment by ImagicTheCat** [comment]
vRP has no backward version support.

**Comment by mickeygeecom** [comment]
It's OK. We managed to fix it. Closing aswell.
