### ISSUE TITLE
Nil value (upvalue 'callback')

### ISSUE THREAD

**Issue by Kazoon1991** [ImagicTheCat/vRP#477]
Hallo there.
Haven't been able to find a solution myself or anywhere else, so now i'm trying here. 

Error:
https://cdn.discordapp.com/attachments/533040390559891462/533040689949310996/vsvdv.jpg

Utils file section: 

> function Task(callback, dparams, timeout) 
  if timeout == nil then timeout = 5000 end
.
 local r = {}
  r.done = false
.
 local finish = function(params) 
    if not r.done then
      if params == nil then params = dparams or {} end
      r.done = true
(((LINE 43 - ERROR REFERENCE)))      callback(table.unpack(params))
    end
  end
.
  setmetatable(r, {__call = function(t,params) finish(params) end })
  SetTimeout(timeout, function() finish(dparams) end)
.
  return r
end
.
function parseInt(v)
--  return cast(int,tonumber(v))
  local n = tonumber(v)
  if n == nil then 
    return 0
  else
    return math.floor(n)
  end
end
.
function parseDouble(v)
--  return cast(double,tonumber(v))
  local n = tonumber(v)
  if n == nil then n = 0 end
  return n
end
.
function parseFloat(v)
  return parseDouble(v)
end

IGNORE dots, just to make it into a quote.

It only happens when there is around 12+ on the server. 

Hope you're able to help, i'm kinda out of options here.
All love - Kazoon!

**Comment by bradxy** [comment]
How is this related to vrp?

**Comment by Kazoon1991** [comment]
It's a Vrp file? Resources/vrp/lib/utils.lua
Unless i'm not seeing this correctly, it should be an error in that file or related to.

**Comment by ImagicTheCat** [comment]
vRP has no backward version support, this is old stuff.
