### ISSUE TITLE
Item Permissions

### ISSUE THREAD

**Issue by bradxy** [ImagicTheCat/vRP#479]
I have reached out to others to further test that this is not working, and I believe my setup is set correctly per the documentation... 

Can you please confirm this for us so we can check items on a person... Thank you... Here is the code I am using directly to try and use the permission item check

user:hasPermission("!item.mafiakey.>0") as per the example....

I am removing the Item and returning it as a alternative...

**Comment by ImagicTheCat** [comment]
I remember checking it, was working. I will test it when I will find time (and find 8go for the last update...).

**Comment by ImagicTheCat** [comment]
Just tested it, working fine with `!item.edible|tacos.>0`.

**Comment by bradxy** [comment]
Changed a few things around and now its working.
Thank-you!
