### ISSUE TITLE
Updating VRP?

### ISSUE THREAD

**Issue by Kazoon1991** [ImagicTheCat/vRP#480]
Is it possible to update from an old version of vRP, to a new one, without loosing data?
As far as i've seen the new files has been changed, so taking your edited files, copying over to a new version does not work. There will be communication errors etc.

Is there any way, to completely update form a old vRP version to current or atleast newer - without having to start over?

Thanks, Kazoon! :)

**Comment by ImagicTheCat** [comment]
Issues are not for help, you can use the forum topic instead. It is not clear if you are speaking about modified core files, resources or even the database. But there is no magic way and nothing provided by the project about that.
