### ISSUE TITLE
Stuck on vRP Checking Identifiers

### ISSUE THREAD

**Issue by wolfpepper** [ImagicTheCat/vRP#482]
I have an issue myself and one of my Lead developer have stripped our server for framework updates and we have just the vRP framework. when anyone try's to connect to the server we get Checking vRP identifiers and then its just locks on that and doesn't time out or progress anywhere.  looking through the log files it cant locate the Mysql.lua for alot of the vrp resources. even though the MySQL is linked up Correctly

**Comment by ImagicTheCat** [comment]
deprecated: seems to be about a very old version

**Comment by wolfpepper** [comment]
i have the latest version.....

**Comment by wolfpepper** [comment]
like i downloaded it yesterday kind of new

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/issues/483

**Comment by thomaserkul** [comment]
i have the same issue, please help me
