### ISSUE TITLE
VRP Gets stuck on load

### ISSUE THREAD

**Issue by wolfpepper** [ImagicTheCat/vRP#483]
I have an issue myself and my Lead developer have stripped our server for framework updates and we have just the vRP framework. when anyone try's to connect to the server we get Checking vRP identifiers and then its just locks on that and doesn't time out or progress anywhere. looking through the log files it cant locate the Mysql.lua for alot of the vrp resources. even though the MySQL is linked up Correctly

i downloaded the latest version of the master fork as of yesterday and have tried to redownload it again today and the issue still persists

**Comment by wolfpepper** [comment]
if any further information is needed i can post it in here i downloaded the master fork as of 4:33pm Central US time today and tried wiping my database and my server itself even to get it to start and it wont

**Comment by wolfpepper** [comment]
https://cdn.discordapp.com/attachments/384869785181093900/535679951496675328/logfile.png
here is the log file from the server i also have a text document that has the full log if needed

**Comment by ARL64** [comment]
This is related to the scheduler.
You have to replace the server scheduler file by this one:
https://github.com/citizenfx/fivem/blob/28ccdb507eee3ca6e75f99b19d64e290c8bd7e24/data/shared/citizen/scripting/lua/scheduler.lua
Located here: PATH_TO_YOUR_SERVER/citizen/scripting/lua/scheduler.lua

**Comment by wolfpepper** [comment]
after looking around alot we cant find that particular path at all we get our hosting through zap
![all we have](https://user-images.githubusercontent.com/33947015/51408312-e0c01200-1b23-11e9-8ade-7db992ab46db.PNG) < this is all we get when we open our server directory on the ftp

**Comment by wolfpepper** [comment]
After manually installing we still get the same issue even after replacing the scheduler.lua

**Comment by ARL64** [comment]
```Resource loading for ghmattimysql failed:```
Check you GHMatti resource, download from here: https://github.com/GHMatti/FiveM-MySQL/releases
Configure DB credentials in settings.xml

**Comment by wolfpepper** [comment]
We did that just now and are doing a test run to see if that fixes the issue last night after 12 hours of fussing we decided to take a break and call it a night i will post here shortly if the issue is resolved and close the ticket

**Comment by ARL64** [comment]
Could not find dependency GHMattiMySQL for resource vrp_ghmattimysql.
Put GHMattiMySQL before vrp_ghmattimysql in server.cfg

**Comment by wolfpepper** [comment]
We finally got it to work after a bunch of fussing our issue was a culmanation of 3 things the ghatti wasnt configuring in our database correctly due to having old vrp files there the scheduler wasnt correct and the mysql was configured incorrectly due to a mistype

**Comment by PatalJunior** [comment]
I've got the exact same problem, got the latest artifacts(2083), the latest vrp and GHMattiMySQL, and it's before vrp_ghmattimysql, it's all correct in the settings, any ideas?
![image](https://user-images.githubusercontent.com/39913166/74610403-d7202980-50ea-11ea-9f69-481cf4628904.png)

![image](https://user-images.githubusercontent.com/39913166/74610404-db4c4700-50ea-11ea-9f7c-492f8f112270.png)

![image](https://user-images.githubusercontent.com/39913166/74610406-dedfce00-50ea-11ea-9e0e-50f0a59eb183.png)
