### ISSUE TITLE
HTML space character error

### ISSUE THREAD

**Issue by wolfpepper** [ImagicTheCat/vRP#484]
I keep getting this error everytime we boot the server and login and i have tried everything to fix it i am using the VRP dev build from the github any idea on how to fix it ive even went as far as digging into my old JS scripting knowledge and i cant even figure it out
![20190120125405_1](https://user-images.githubusercontent.com/33947015/51444111-d7b47980-1cb8-11e9-9eea-5ce189b5aa00.jpg)

**Comment by bradxy** [comment]
Are you trying to get different script to work that displays the current Job?

**Comment by wolfpepper** [comment]
yes it was another script we didnt realize was loading
