### ISSUE TITLE
How to get PlayerID in client.lua

### ISSUE THREAD

**Issue by KuhvaDE** [ImagicTheCat/vRP#485]
Hi I am currently trying to get the PlayerID in my Client.lua. Unfortunately I always get ```nil``` back.

My Curent method:
```
vRP = Proxy.getInterface("vRP")
print(vRP.getUserId({}))
```

![error](https://user-images.githubusercontent.com/35656826/51756867-47b06e80-20c2-11e9-84bb-c6749edaac05.png)

**Comment by ImagicTheCat** [comment]
Old version, also use the FiveM forum topic/vRP discord to ask for help.
