### ISSUE TITLE
[bug] Markers not being drawn in game

### ISSUE THREAD

**Issue by AceDax** [ImagicTheCat/vRP#486]
the DrawMarker native seems to no longer function in vRP2, I have even tested it on a completely brand new server with nothing but vRP2. no markers are being drawn anywhere. I believe this is related to recent FiveM updates but I have not yet been able to pinpoint the exact source of the problem

**Comment by ImagicTheCat** [comment]
I can't reproduce the issue (updated client & server).

**Comment by AceDax** [comment]
ok so i resolved my issue, vk_interiors is weird in that if there is an error in its config file rather then spitting out an error and stop working like most scripts it instead doesn't say a word and quietly continues to try and work despite being incorrect which results in breaking the drawmarker native for other scripts. not sure why it does this but after fixing the errors things are working correctly again. so for anyone running vk_interiors watch out for that
