### ISSUE TITLE
[Feature Request] warp points

### ISSUE THREAD

**Issue by AceDax** [ImagicTheCat/vRP#487]
My last issue regarding markers and what was ultimately causing that issue got me thinking about this

Base vRP2 should have a module for custom teleports similar to what vk_interiors does except better because it would be a part of the framework.

Having this module in the base framework would open the door for teleports with group permissions, a feature to teleport vehicles into the biker clubhouses could be added and so on. 

Additionally being part of the framework would make server owners/developers more likely to use it rather that try and hunt down an extension that may or may not exist and may or may not be released

**Comment by ImagicTheCat** [comment]
Do you have example videos for the feature ?

**Comment by AceDax** [comment]
I do not have an example video but I can make one afterwork tonight. 

I can say that it is just teleports from one set of coords to another. Instancing would be a nice feature but ultimately not nessicary for what I am suggesting here.

Somewhere I do have code laying around for teleporting players in vehicles too, I would have to dig through my stuff and find it though

**Comment by ImagicTheCat** [comment]
For more flexibility, the warp would be very simple as a one way teleportation. So a tunnel would require 2 entries and multiple destinations would require multiple warps. Does that suit your needs ?

**Comment by AceDax** [comment]
just for clarification your talking about something like this right?

teleportation 1 = point A to point B
teleportation 2 = point B to point A
teleportation 3 = point C to point D
teleportation 4 = point D to point C

if so then yes that's totally fine, so long as there is a menu pop up that asks first before teleporting otherwise I can see someone getting caught in an infinite teleport loop if it was done just by walking into the circle lol

also for the GTA:O interiors that are garages like the biker club houses if you are in a vehicle can it teleport the vehicle as well? 

but yeah other then that yeah that would be perfect and would get rid of the issue with having to have that extra script

**Comment by ImagicTheCat** [comment]
Yes, a timer will prevent the infinite loop and there will be an option to allow vehicle/player/or both teleportation.

**Comment by AceDax** [comment]
cool something I literally just thought of with vehicle teleportation is heading, not sure if you thought of it too or not but I figured I would mention it at least

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/commit/4bca86235ab2286567ed2d7acc1d6cc14f5aafcd
Heading is not taken in account for all vRP teleportations/coordinates for now, but can already be used as a 4th parameter for the warp module (see Base:vehicleTeleport).
