### ISSUE TITLE
[Feature Request] police PC from cars

### ISSUE THREAD

**Issue by AceDax** [ImagicTheCat/vRP#488]
I have been looking into making this myself but then I thought why not share the idea maybe it will help improve vRP as a whole

basicly the idea is to allow police to open the police PC if they are in a vehicle with the emergency class that way even custom police cars works. 

just a cool thought I wanted to share :)

**Comment by ImagicTheCat** [comment]
This has been requested before, it's not desirable in the core of vRP but you can add it yourself.
