### ISSUE TITLE
Database continuously giving ID of 1 to all players when using vRP

### ISSUE THREAD

**Issue by Hazzer278** [ImagicTheCat/vRP#492]
Hi there

I have recently set up a new FiveM server using the vRP framework

When setting up the vRP framework and linking it to the database it has linked up but
when I connected I got the ID of 1 in the DB but when other players connect it says they have ID 1 and they can't access the F9 menu for anything and they can't view any money etc.. 

If you can help me in any way shape or form this would be massivly appreciated.

**Comment by ImagicTheCat** [comment]
Issues are only for bug reports/feature requests. Is this a bug report ? What version of vRP are you talking about ?

**Comment by Hazzer278** [comment]
Not sure on the version but it is the one that you can download from FiveM forums
