### ISSUE TITLE
[bug] Hair colors not working

### ISSUE THREAD

**Issue by AceDax** [ImagicTheCat/vRP#493]
So I have been asking around and it seems like a common issue, vRP2 doesn't allow any hair color other then black. 

The lead developer in my community says that the arguments for ped hair color are incorrect, he could attempt to fix it but he would rather not mess with the base code for your framework so he told me to relay some info over to you Imagic

The following is word for word from my lead developer:

His code for the skinshop seems fine now that I'm doing my own testing
The numbers make sense
But I think the issue is actually with how he's handling applying the customizations
So there's 74 hair styles, most of which have 1 variation
He's not handling setting hair color explicitly
Which you have to do for that
SetPedHairColor takes 2 arguments
The "color" and the "highlight" color
So effectively
SetPedHairColor(ped, [0-64], [0-64])
But I'd let imagic know

Anyways we don't want to edit the core of your code if we don't have to so we are passing this information along to you, I hope it is helpful

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/commit/e5e9749f055b57081ec97ff645673086ed53b450

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/commit/e5e9749f055b57081ec97ff645673086ed53b450
