### ISSUE TITLE
Visual Vehicle Damage

### ISSUE THREAD

**Issue by bradxy** [ImagicTheCat/vRP#494]
Vehicle damage for the engine, doors, windows and gas tank are working but all visual damage is not saving or perhaps not loading when taking a PV out... It use to work fine...

**Comment by ImagicTheCat** [comment]
"It use to work fine", what are you talking about ? There is a limited number of things implemented to save/restore vehicle damages. See https://github.com/ImagicTheCat/vRP/blob/dev/vrp/client/garage.lua#L464.

**Comment by Kongen2110** [comment]
The link i not working.... But how can i save the vehicle damage to the garage?
