### ISSUE TITLE
[Bug] customizing fines

### ISSUE THREAD

**Issue by AceDax** [ImagicTheCat/vRP#496]
in cfg/police.lua you have a place to list out fines, I customized my server to place all of our traffic tickets there but when we play test it not all of the fines I added show up and sometimes none show up at all. 

I can send you the edits I made to see if you can find a solution if you need them, but at the moment this is really holding back my community from being able to launch our server publicly if the police can not issue fines correctly

**Comment by ImagicTheCat** [comment]
Probably because they don't have enough money (https://github.com/ImagicTheCat/vRP/blob/dev/vrp/modules/police.lua#L207).

**Comment by AceDax** [comment]
ah ok thank you, I believe the issue is solved now, if something like that happens again I will let you know :)
