### ISSUE TITLE
Mysql Problems

### ISSUE THREAD

**Issue by AntwanR942** [ImagicTheCat/vRP#505]
I keep getting this "warning" saying my DB driver is not initialized. I have tried changing the DB names, the DB driver, username, password and I still get this warning. I'm also stuck when joining on "vrp: checking identifiers". There is no documentation on how to actually fix this issue. 
```

This is my server.cfg
endpoint_add_tcp "0.0.0.0:30120"
endpoint_add_udp "0.0.0.0:30120"

set DTF_Password "12345"

start mapmanager
start chat
start spawnmanager
start sessionmanager
start fivem
start hardcap
start rconlog
start playernames

start ghmattimysql

start vrp

restart sessionmanager
```

Here is the Base.lua DB config.
`cfg.db = {
  driver = "ghmattimysql",
  host = "127.0.0.1",
  database = "vrp",
  user = "root",
  password = ""
}`

And here is an image of my DB: 
![Screenshot_12](https://user-images.githubusercontent.com/46630572/54859925-c0baf380-4d0a-11e9-99b7-43a404c126b7.png)

No tables are made, nothing.

**Comment by ImagicTheCat** [comment]
Issues are not for help, after carefully reading the doc you can use the discord or the FiveM forum topic for that purpose.

**Comment by kkkasio** [comment]
same problem here!
