### ISSUE TITLE
Features and Request(Legit)

### ISSUE THREAD

**Issue by ryanlinn13** [ImagicTheCat/vRP#506]
Nice framework has a lot of potential.  One feature I like is the break away from the traditional mysql-async and using GHMattiMySQL.  Anyways, let's get this rolling shall we?

Features that would enhance your framework:

Character Menu Selection UI(When you first load up)
More Food Items and usable drugs( such as meth cocaine etc.)
Better menus like the old style but it's well old...(Use a phone for selecting menu items like a famous framework you know and probably hate)
Better positioning for people to sign in/sign off duty as cops 
Handcuffing Sounds and Animation
Car locks with sound 
Barriers(Spike Strips)
More Police Ranks and Departments
Lawyer and Judge Job
GSR(Gun Shot Reside Feature for Police)
Fire Fighter Job 
More civ jobs seems kinda bland. (fishing )

Thanks for taking your time to read this... I hope you considering my recommendations, I feel they can really enhance your framework and up the competition so to speak.

**Comment by ryanlinn13** [comment]
Oh a better money ui and job display too I hope you really take the time to consider this because I feel this could greatly enhance your framework.

**Comment by ImagicTheCat** [comment]
First, issues or features request should not be batched together unless there is a clear relationship between them. Secondly, vRP is a framework, so it doesn't aim to develop everything people want, but give them tools to do so.

I will quickly answer to each here and close the issue.

- Character Menu Selection UI(When you first load up) **-> extension**
- More Food Items and usable drugs( such as meth cocaine etc.) **-> extension**
- Better menus like the old style but it's well old...(Use a phone for selecting menu items like a famous framework you know and probably hate) **-> I'm satisfied with the menu system, you can overload it with extension**
- Better positioning for people to sign in/sign off duty as cops **-> all config is here as an example, not to be fully playable**
- Handcuffing Sounds and Animation **-> https://github.com/ImagicTheCat/vRP#wip**
- Car locks with sound **-> https://github.com/ImagicTheCat/vRP#wip**
- Barriers(Spike Strips) **-> extension ?**
- More Police Ranks and Departments **-> config, extension**
- Lawyer and Judge Job **-> config, extension**
- GSR(Gun Shot Reside Feature for Police) **->extension**
- Fire Fighter Job **-> config, extension**
- More civ jobs seems kinda bland. (fishing ) **-> config, extension**
