### ISSUE TITLE
[vRP/C#] query exception vRP/create_user

### ISSUE THREAD

**Issue by Suciu123** [ImagicTheCat/vRP#509]
Hello!!! So i just started to get a fivem server,  i spent a lot of time in it, i maked it kinda good, but i have just one more large problem! it's a vRP query exception problem! I really don't know what to do, as i just started this hobby as programming! And after i delete the vRP file that is causing the problem, it's always getting another query exception vRP/ *file* PLEASE HELP ME!
Here is the problem : 
![Screenshot_4](https://user-images.githubusercontent.com/49118155/55330245-39ebe080-5499-11e9-8681-dcd25961f822.png)
![Screenshot_5](https://user-images.githubusercontent.com/49118155/55330250-3bb5a400-5499-11e9-9d7d-0407d5210ea9.png)

**Comment by Suciu123** [comment]
♛ѕυ¢ιυ♛#8821 hey! can u add me up on discord?

**Comment by ImagicTheCat** [comment]
Issues are not for help.
