### ISSUE TITLE
Problem salary

### ISSUE THREAD

**Issue by Zuqaa** [ImagicTheCat/vRP#51]
I have test to make a salary system but it does not work :/ 

What is the problem ??

```lua
Citizen.CreateThread(function ()
  while true do
  
	Citizen.Wait(900000) -- Modifier cette valeur pour la fréquence des salaires (600000 = 10 minutes)
	
  local user_id = tvRP.getUserId(source)
  local jobcadet = tvRP.hasGroup(user_id,"cadet")
  local jobsergent = tvRP.hasGroup(user_id,"sergent")
  local joblieutenant = tvRP.hasGroup(user_id,"lieutenant")
  local jobcapitaine = tvRP.hasGroup(user_id,"capitaine")
  local jobtaxi = tvRP.hasGroup(user_id,"taxi")
  local jobchomeur = tvRP.hasGroup(user_id,"user")
	
  if user_id ~= nil then
    local identity = tvRP.getUserIdentity(user_id)
	
	if jobchomeur then
	   tvRP.giveMoney(user_id,"100")
	   tvRP.notify("Vous avez reçu votre salaire !")
	elseif jobtaxi then
	   tvRP.giveMoney(user_id,"300")
	   tvRP.notify("Vous avez reçu votre salaire !")
	elseif jobcadet then
	   tvRP.giveMoney(user_id,"500")
	   tvRP.notify("Vous avez reçu votre salaire !")
	elseif jobsergent then
	   tvRP.giveMoney(user_id,"800")
	   tvRP.notify("Vous avez reçu votre salaire !")
	elseif joblieutenant then
	   tvRP.giveMoney(user_id,"1000")
	   tvRP.notify("Vous avez reçu votre salaire !")
	elseif jobcapitaine then
	   tvRP.giveMoney(user_id,"1800")
	   tvRP.notify("Vous avez reçu votre salaire !")
    end

```
end
end)

**Comment by ImagicTheCat** [comment]
You need to learn the concept of proxy and tunnel. See the inventory water bottle full example.  Some functions are available as proxy server-side, others client-side (the client-side proxy is the same API as the client-side tunnel). And the tunnel is used to call server-side or client-side functions from the server or the client, using a specific syntax.

**Comment by Zuqaa** [comment]
ok but what is the error in my code :p ?

**Comment by 3rg00** [comment]
Seriously, stop ask anything, Imagic is not here just for your pleasure.
Learn and try yourself, we have everything for to do almost all we want.

Your code is wrong, because you don't use correctly the proxy/tunnel concept. What you want more ? Do you want that we code it for you ? tsss

**Comment by Zuqaa** [comment]
I dont understand...
