### ISSUE TITLE
Hidden Transformer - Informer

### ISSUE THREAD

**Issue by bradxy** [ImagicTheCat/vRP#510]
This does not seem to work at all and seen on other server with the same issue, hidden_transformers they do not appear in the Informer...

**Comment by SirOficial** [comment]
I also have the same problem.

![image](https://user-images.githubusercontent.com/39030538/56105684-d8edef00-5f13-11e9-92e9-700b89b773f6.png)

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/commit/eb0bffe3928da0857daca8f64ed7cde298dad937
