### ISSUE TITLE
[Feature Request] Option to choose between MSGPack and JSON

### ISSUE THREAD

**Issue by tabarra** [ImagicTheCat/vRP#512]
It would be good too have the option to use JSON instead of MSGPack.  
Related to this commit: https://github.com/ImagicTheCat/vRP/commit/6dabc5651f38e0726db9a195e6ed27f8a6697c54

**Comment by ImagicTheCat** [comment]
Complicated to do, because it's not only about JSON, but about binary data VS human readable data I suppose. What's wrong with MessagePack ?

**Comment by tabarra** [comment]
For a simple test I swapped all msgpack functions for json and apparently it worked properly.  
But considering that I just now started with FiveM/vRP, I'm not so sure if I cold tell if everything is working properly or not.

**Comment by ImagicTheCat** [comment]
MessagePack is superior for binary non-human readable storage, so if you want JSON I suppose it's for modifying the structure by editing text, so you need to change the way it is stored by the SQL engine. I'm against that, if you need to read/edit the data from the DB, you can use MessagePack from your favorite language.
