### ISSUE TITLE
[Minor Issue] Ped Models

### ISSUE THREAD

**Issue by AceDax** [ImagicTheCat/vRP#517]
I am not too sure what exactly is the cause of this issue however I believe it could be the player customization stuff which is written specificly for the MP model.

Something my players have noticed is that some of the actual NPC models have a messed up face as if the model itself is broken in some way, my guess is that the player customization is trying to apply certain things made for the MP model only to the NPC models and thus messing up how the NPC model looks. 

although not a huge concern this does render several models completely unusable including dog models which my community wants to use for k9 police force. is there a chance this can be looked into and hopefully corrected. I can provide any additional information required including pictures of the issue.

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/commit/f477f5a31dd4780d115913728ee287962063ea7e
