### ISSUE TITLE
Problem with accent

### ISSUE THREAD

**Issue by Zuqaa** [ImagicTheCat/vRP#52]
Hi the Accent (é, ô, à, è...) has stopped working :(

**Comment by ImagicTheCat** [comment]
Please take time to report issues correctly, this is not a race. Explain, elaborate, where, when, how ?

**Comment by Zuqaa** [comment]
Where : it just does not work... When: Today How: Idk :/

But yesterday it work perfectly..

**Comment by Zuqaa** [comment]
AH i have found.. It's the accent in en.lua else in the other file it working ^^ but how to resolve this ?

**Comment by ImagicTheCat** [comment]
Solved ?

**Comment by Zuqaa** [comment]
No :/

**Comment by ImagicTheCat** [comment]
Don't close the issue until we know more about it.

**Comment by Zuqaa** [comment]
I've described the problem but nobody answers me..

**Comment by xchopin** [comment]
Can you describe your issue ? "It doesn't work" means nothing.
Does the script crash ? Do you see weird characters ? I don't know describe or send a screenshot please.
