### ISSUE TITLE
Mysql problems

### ISSUE THREAD

**Issue by gud1820** [ImagicTheCat/vRP#521]
![147a269ae5c06c470056cc09811fe15946b8b28d_2_690x387](https://user-images.githubusercontent.com/42309996/56473510-8610bc00-646c-11e9-8295-28a3108af4dd.png)

Or se https://pastebin.com/nfGgeVhr

**Comment by gud1820** [comment]
Cut you not help?

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/blob/master/doc/README.adoc#issues--features--help
