### ISSUE TITLE
[Feature Request] Random Outcomes

### ISSUE THREAD

**Issue by Littledevill** [ImagicTheCat/vRP#524]
Having a transformer output a random item depending on whatever number a never generator picks so say you have 5 items and they each have a value the first item has a value of 1-10 so if the number generator picks a number between 1-10 it will give you that item the same for the second item but instead of numbers 1-10 its 11-20 or something along these lines and maybe we can have this included in shops in some way to where you buy like say a scratch card or a lottery ticket and you will get a random ammount of money from 0-10000 depending on if your number was picked

**Comment by CryptoParts** [comment]
Use math.random

**Comment by ImagicTheCat** [comment]
Make/look for extensions. Transformers products/reagents can be extended now. You can create items for the lottery (look at https://github.com/ImagicTheCat/vRP-TCG boosters).
