### ISSUE TITLE
Problem with function of police

### ISSUE THREAD

**Issue by Zuqaa** [ImagicTheCat/vRP#53]
Screenshot: http://prntscr.com/f6bn57

Problem: Cuff:Work, but the all other function does not work and make a error..

**Comment by ImagicTheCat** [comment]
Did you update properly every files, and check every config file differences ?

**Comment by Zuqaa** [comment]
It working yesterday too... i dont have touch the file after

**Comment by ImagicTheCat** [comment]
It doesn't matter it was working yesterday, a lot have changed. If you missed only one new config property, NeoLua will break everything.

**Comment by Zuqaa** [comment]
i haev recheck the last updates and i have add all... but i have modified some code..

Code modified:

Phone.lua (in cfg)

I have add my group of police:

```lua
cfg.services = {
  ["capitaine"] = {
    blipid = 304,
    blipcolor = 38,
    alert_time = 300, -- 5 minutes
    alert_permission = "police.service",
    alert_notify = "~r~Police alerte:~n~~s~",
    notify = "~b~La police arrive, ne bougez pas!"
  },
  ["lieutenant"] = {
    blipid = 304,
    blipcolor = 38,
    alert_time = 300, -- 5 minutes
    alert_permission = "police.service",
    alert_notify = "~r~Police alerte:~n~~s~",
    notify = "~b~La police arrive, ne bougez pas!"
  },
  ["sergent"] = {
    blipid = 304,
    blipcolor = 38,
    alert_time = 300, -- 5 minutes
    alert_permission = "police.service",
    alert_notify = "~r~Police alerte:~n~~s~",
    notify = "~b~La police arrive, ne bougez pas!"
  },
  ["cadet"] = {
    blipid = 304,
    blipcolor = 38,
    alert_time = 300, -- 5 minutes
    alert_permission = "police.service",
    alert_notify = "~r~Police alerte:~n~~s~",
    notify = "~b~La police arrive, ne bougez pas!"
  },
  ["taxi"] = {
    blipid = 198,
    blipcolor = 5,
    alert_time = 300,
    alert_permission = "taxi.service",
    alert_notify = "~y~Taxi alerte:~n~~s~",
    notify = "~y~Le taxi arrive, ne bougez pas!"
  }
}
```

**Comment by Zuqaa** [comment]
And in police.lua (in cfg)

i have modified the gruop too:

 ` service = "capitaine", "lieutenant", "sergent", "cadet" -- service to alert when the tracking is successful`

**Comment by ImagicTheCat** [comment]
Where did you got the idea that this property can handle multiple services ? "service", not "services". And why making multiple services with the same police permission ? Again, NeoLua will not warn you when doing mistakes, and everything will fall apart. This is also why it is so hard to develop on FiveM, don't configure the files if you don't have a good understanding of what you're doing. And if you do, do it  carefully.

This project has already taken 2 weeks of my life, I can't also help you to solve your own problems.

**Comment by Zuqaa** [comment]
no cadet i have 3 permi, sergent 4, lieutenant 5.... etc...

Ok i assigned just to capitaine so :/

**Comment by ImagicTheCat** [comment]
Create a permission, add the permission to multiple groups, set the service permission. That's it.

**Comment by Zuqaa** [comment]
This is what I did just now / yesterday

**Comment by SnaiCrys** [comment]
> Screenshot: http://prntscr.com/f6bn57
> Problem: Cuff:Work, but the all other function does not work and make a error..

fix same problem https://github.com/ImagicTheCat/vRP/pull/54
