### ISSUE TITLE
proxy call vRP.registerMenuBuilder not found

### ISSUE THREAD

**Issue by lRoberth** [ImagicTheCat/vRP#532]
How are you supposed to use resources that need registerMenuBuilder?, any resource that uses that function completely breaks (I updated from a really outdated version to the newest one, took me over three hours to update, but now I can't get working these)

Here's the full error

> error: proxy call vRP:registerMenuBuilder not found
> Error loading script server.lua in resource vrp_dmvschool: citizen:/scripting/lua/scheduler.lua:55: Current execution context is not in the scheduler, you should use CreateThread / SetTimeout or Event system (AddEventHandler) to be able to Await
> stack traceback:
>         [C]: in function 'error'
>         citizen:/scripting/lua/scheduler.lua:55: in field 'Await'
>         @vrp/lib/utils.lua:64: in function <@vrp/lib/utils.lua:63>
>         (...tail calls...)
>         @vrp_dmvschool/server.lua:106: in main chunk
> Failed to load script server.lua.

thx in advance

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/blob/master/doc/README.adoc#issues--features--help
https://github.com/ImagicTheCat/vRP/blob/master/doc/dev/modules/gui.adoc
