### ISSUE TITLE
DB driver issue

### ISSUE THREAD

**Issue by Ex0r** [ImagicTheCat/vRP#536]
```
This has been asked numerous times, and there have been no clear answers on it. I am attemping to setup a test FiveM server with the vRP framework, and I am getting this issue:

[vRP] Extension Garage loaded.
[vRP:Business] 1 commerce chambers
[vRP] Extension Business loaded.
[vRP] Extension Home loaded.
[vRP] Extension home_components loaded.
[vRP:Police] 3 PCs 3 jails 6 fines
[vRP] Extension Police loaded.
[vRP] Extension Radio loaded.
[vRP] Extension PedBlacklist loaded.
[vRP] Extension Edible loaded.
[vRP] Extension Warp loaded.
Started resource vrp
Creating script environments for GHMattiMySQL
Loaded GHMattiMySQL.net, Version=0.6.1.0, Culture=neutral, PublicKeyToken=null into ScriptDomain_1840484399
Instantiated instance of script GHMattiMySQL.Core.
Started resource GHMattiMySQL
Authenticating server license key...
Server license key aucfx> thentication succeeded. Welcome!
Sending heartbeat to live-internal.fivem.net:30110
[vRP] DB driver "ghmattimysql" not initialized yet (39 prepares cached, 5 queries cached).
Started map fivem-map-skater
Started resource fivem-map-skater
server thread hitch warning: timer interval of 163 milliseconds
[vRP] DB driver "ghmattimysql" not initialized yet (39 prepares cached, 5 queries cached).
c[vRP] DB driver "ghmattimysql" not initialized yet (39 prepares cached, 5 queries cached).
[vRP] DB driver "ghmattimysql" not initialized yet (39 prepares cached, 5 queries cached).
[vRP] DB driver "ghmattimysql" not initialized yet (39 prepares cached, 5 queries cached).
[vRP] DB driver "ghmattimysql" not initialized yet (39 prepares cached, 5 queries cached).
[vRP] DB driver "ghmattimysql" not initialized yet (39 prepares cached, 5 queries cached).
[vRP] DB driver "ghmattimysql" not initialized yet (39 prepares cached, 5 queries cached).
[vRP] DB driver "ghmattimysql" not initialized yet (39 prepares cached, 5 queries cached).

As you can see from the log, GHMattiMySQL is loading, but the ghmattimysql db driver is still not initializing. It say for 35 minutes throwing that same error out.
```

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP-db-drivers

**Comment by Ex0r** [comment]
This does not help. I am already using this, and it's not initializing the driver.

**Comment by ImagicTheCat** [comment]
Issues are not for help, most of the time people are not reading/understanding about the DB driver concept.

**Comment by denyck007** [comment]
still does not work

**Comment by nloyola** [comment]
CLEARLY you need to provide more information in your documentation!

**Comment by ImagicTheCat** [comment]
You're probably looking for a tutorial, which the documentation doesn't aim to be currently.

**Comment by nloyola** [comment]
Nice attitude @ImagicTheCat !

**Comment by cobe666** [comment]
Guys, Show some respect to @ImagicTheCat, He is probably a very busy guy and the first reply he wrote actually works if you follow it correctly, if you still cant get it, watch this tutorial : https://www.youtube.com/watch?v=MlyRDgdya-4 thats should answer all of this.

**Comment by filipecamargo10** [comment]
> Guys, Show some respect to @ImagicTheCat, He is probably a very busy guy and the first reply he wrote actually works if you follow it correctly, Still cant get it? Try this, Delete the normal ghmattimysql folder, go to this link https://www.youtube.com/redirect?v=MlyRDgdya-4&event=video_description&q=https%3A%2F%2Fgithub.com%2FGHMatti%2FFiveM-MySQL%2Freleases%2Fdownload%2F0.6.1%2FGHMattiMySQL.zip&redir_token=8AE8CaP_SO3YRMKRNs2NRybgMZl8MTU5MDk3ODgwM0AxNTkwODkyNDAz
> 
> And download that fix, now drag it to your server folder and open the settings file, set your database, username, pass etc and it should work.

In Linux dont work :(

**Comment by cobe666** [comment]
> > Guys, Show some respect to @ImagicTheCat, He is probably a very busy guy and the first reply he wrote actually works if you follow it correctly, Still cant get it? Try this, Delete the normal ghmattimysql folder, go to this link https://www.youtube.com/redirect?v=MlyRDgdya-4&event=video_description&q=https%3A%2F%2Fgithub.com%2FGHMatti%2FFiveM-MySQL%2Freleases%2Fdownload%2F0.6.1%2FGHMattiMySQL.zip&redir_token=8AE8CaP_SO3YRMKRNs2NRybgMZl8MTU5MDk3ODgwM0AxNTkwODkyNDAz
> > And download that fix, now drag it to your server folder and open the settings file, set your database, username, pass etc and it should work.
> 
> In Linux dont work :(

When did I say that it worked in linux?

**Comment by filipecamargo10** [comment]
> > > Guys, Show some respect to @ImagicTheCat, He is probably a very busy guy and the first reply he wrote actually works if you follow it correctly, Still cant get it? Try this, Delete the normal ghmattimysql folder, go to this link https://www.youtube.com/redirect?v=MlyRDgdya-4&event=video_description&q=https%3A%2F%2Fgithub.com%2FGHMatti%2FFiveM-MySQL%2Freleases%2Fdownload%2F0.6.1%2FGHMattiMySQL.zip&redir_token=8AE8CaP_SO3YRMKRNs2NRybgMZl8MTU5MDk3ODgwM0AxNTkwODkyNDAz
> > > And download that fix, now drag it to your server folder and open the settings file, set your database, username, pass etc and it should work.
> > 
> > 
> > In Linux dont work :(
> 
> When did I say that it worked in linux?

Pool Soul

**Comment by sin532100** [comment]
how can i use db_driver in vrp0.5?
