### ISSUE TITLE
Business fonction

### ISSUE THREAD

**Issue by cedricalpatch** [ImagicTheCat/vRP#55]
Hello ,

First I whant tell you... You make really good job!!
I have online test server ( RPF Studio Alpha 1.5 ) for my futur official server, but I donc understand for Business...
When I create a Business, never I have tranfers money?
I try to put Dirty money in item.tranformer.lua but I take the money without Business, can you tell me some info about this great script?

Thanks
Cedric

**Comment by cedricalpatch** [comment]
ok is good sorry!!

**Comment by Aleweadan** [comment]
Then close your issue

**Comment by Zuqaa** [comment]
Yes pls if you have resolve ur problem close the thread ;)

**Comment by ImagicTheCat** [comment]
Business are here to launder dirty money, by default, you can only launder your business capital per 24 hours.

**Comment by cedricalpatch** [comment]
yes thanks I have found solution ... I closed this issues ;)
