### ISSUE TITLE
error: proxy call vRP:getUserIdentity not found

### ISSUE THREAD

**Issue by aburashedb52** [ImagicTheCat/vRP#553]
become these error and id in the phone gone , the blips gone, people can't buy new car

**Comment by Santagain** [comment]
https://github.com/ImagicTheCat/vRP/tree/master/doc/dev
https://github.com/ImagicTheCat/vRP/blob/master/doc/dev/modules/identity.adoc

**Comment by aburashedb52** [comment]
ty i removed command and its worked( Allow User Variables=true)
