### ISSUE TITLE
New way to fix the HUD position.

### ISSUE THREAD

**Issue by tabarra** [ImagicTheCat/vRP#557]
Recently the FiveM team posted this snippet in their cookbook:  
[Useful snippet: getting the top left of the minimap in screen coordinates](https://cookbook.fivem.net/2019/08/12/useful-snippet-getting-the-top-left-of-the-minimap-in-screen-coordinates/)  
```lua
SetScriptGfxAlign(string.byte('L'), string.byte('B'))
local minimapTopX, minimapTopY = GetScriptGfxPosition(-0.0045, 0.002 + (-0.188888))
ResetScriptGfxAlign()
local w, h = GetActiveScreenResolution()
return { w * minimapTopX, h * minimapTopY }
```  
  
The magic numbers come directly from the game frontend xml.  
Could this fix the issue of misaligned HUD to some resolutions?

**Comment by ImagicTheCat** [comment]
Implemented it in master, but it's still wrong for some resolutions and based on the whole minimap, even the blurred parts. `minimap_mask` or `minimap_blur` elements don't work as expected either. At least, it's more consistent.

**Comment by bradxy** [comment]
For some reason adding the resource_manifest_version to vrp seems breaks a bunch of client functions, veh_blacklist, ped_blacklist and eventually storing vehicles stops working.

**Comment by ImagicTheCat** [comment]
@bradxy create a new issue, I think it's about deleting

**Comment by tabarra** [comment]
Closing this issue since you already implemented it, even though its not perfect.  
Feel free to open it again if you want to.
