### ISSUE TITLE
Artifact 1462 -> 1552 Tunnel.lua error

### ISSUE THREAD

**Issue by zbadrabbit** [ImagicTheCat/vRP#560]
Upgraded from 1462 to 1549 (also tried 1552). We are now receiving:

`` SCRIPT ERROR: [string "vrp/lib/Tunnel.lua"]:100: attempt to call a nil value (upvalue 'TriggerRemoteEvent')``

This leaves the user logging in stuck at "Loading character" and never progresses. 

Ideas?

**Comment by XShaan** [comment]
The same issue please fix it.

**Comment by ImagicTheCat** [comment]
Talked about here https://github.com/ImagicTheCat/vRP/pull/559, you can downgrade the server version until it gets fixed.

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/commit/e334d9520ca51b53e7a0fc66e9016ddd3d040689

**Comment by sisanc6** [comment]
ImagicTheCat porque no ofreces un soporte claro y conciso? sirve tu comentario cuando el problema esta resuelto no cuando respondes con otro cuestionamiento!
