### ISSUE TITLE
Item Transformer Bug

### ISSUE THREAD

**Issue by DavidFdes** [ImagicTheCat/vRP#563]
Do you know how to fix the bug of item_transformers?
If you stand at the edge of the coords, jump forward + press enter it bugs and you can harvest anywhere on the map, you dont need to stand on the coords to do it. And you can even do multiple ones at the same time.

**Comment by ImagicTheCat** [comment]
Probably deprecated.

**Comment by DavidFdes** [comment]
How is it deprecated? Server is updated and the bug persists.

**Comment by ImagicTheCat** [comment]
You didn't give any detail about the vRP version used; a bug like this has been previously fixed. https://github.com/ImagicTheCat/vRP/tree/master/doc#issues--features--help
