### ISSUE TITLE
Lscustom VRP base

### ISSUE THREAD

**Issue by godegodes** [ImagicTheCat/vRP#568]
Hey guys!

I have problems with my VRP base.
I added cars (addon) and these cars hasnt modelhash.
So when make any changes to these cars within bennys (tunning modifications) the changes do not save.

My code is like this:

[170] = {modelHash = 0, modelName = "g7cross"}, - Saveiro

People said me that the modifications can be saved by modelhash **OR** modelName, so if I don't have the model, it must be zero in value, but it doesn't work.

**Does anyone have any idea what can i do?**

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/tree/master/doc#issues--features--help
