### ISSUE TITLE
Item issues

### ISSUE THREAD

**Issue by IllInuz** [ImagicTheCat/vRP#574]
Whenever a user tries to store stuff in his trunk (without them knowning the trunk is full)
They loose their items.

When a user tries to load more then 250 rounds in to ANY gun, they loose the remainder and it will only load 250 rounds.

Whenever a user eats something but the cooldown is still applicable, they loose the item.

Weapon shops, can sell any weapon body, but not all ammunation works to load in to the gun.
For example:
WBODY|WEAPON_VINTAGEPISTOL works, but the ammo WAMMO|WEAPON_VINTAGEPISTOL is unuseable.

**Comment by ImagicTheCat** [comment]
What version are you using ? A head ommit hash would be useful.

**Comment by IllInuz** [comment]
Latest version, i tried on a clean install yesterday.

Op vr 29 nov. 2019 18:02 schreef Imagic <notifications@github.com>:

**Comment by ImagicTheCat** [comment]
The 250 ammo and vintage pistol issues are both internal to GTA V, I don't see a clean way to solve this. Don't overload the weapon and use pistol ammos for the vintage pistol.

I couldn't reproduce the edible/trunk issues, it is unlikely that you are actually using the latest version.
