### ISSUE TITLE
Static choices in menu.

### ISSUE THREAD

**Issue by zThundy** [ImagicTheCat/vRP#575]
Hello guys. I have a question: i recently made a societies script for vrp that can let you update the paycheck of each rank. I was wondering if is there a way to create a sub-menu inside the society menù (that i have already built) to show just the paycheck of that rank:

example:
Captain: 2000
Liutenent: 1000
ecc....

without any function triggered on click.

**Comment by zThundy** [comment]
oh and i'm using an old version of vrp (dunko edited).

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/blob/master/doc/README.adoc#issues--features--help
