### ISSUE TITLE
Hud food and water, key menu

### ISSUE THREAD

**Issue by NewHopeGame** [ImagicTheCat/vRP#58]
I wish I could climb a little bit the bars of hunger is water, it is possible because I can not. As well as changing the key to open the "m" menu does not work. Thank you for your reply

**Comment by ImagicTheCat** [comment]
I don't understand your question about the survival progress bars.
The menu use the phone keys, check you configuration.

**Comment by NewHopeGame** [comment]
I would like to move the bars a little higher, is for the menu I had put "m" which replaces the "up" but no change in "controls"

**Comment by ImagicTheCat** [comment]
If you have an azerty keyboard, you shouldn't rely on what you see in the keys configuration.

**Comment by NewHopeGame** [comment]
So "m" in French gives her what in English if you know
