### ISSUE TITLE
Clarify documentation

### ISSUE THREAD

**Issue by IamN5** [ImagicTheCat/vRP#580]
I recently moved to vRP2, managed to create some extensions, but I’m having problems using vRP Client Extensions client-side. I’m trying to load my client.lua into vRP like this:

```
local Proxy = module("vrp", "lib/Proxy")

local vRP = Proxy.getInterface("vRP")

async(function()
    vRP.loadScript("tp_inventory", "client")
end)
```
Even though client.lua exists inside my “tp_inventory” resource I get this error:

> "SCRIPT ERROR: @vrp/lib/utils.lua:51 resource file tp_inventory/client.lua not found"

[Error image](https://cdn.discordapp.com/attachments/613210251075911681/657095302792347661/unknown.png)

Am I trying to load it the wrong way? Also, I think it would be nice if you could add how to do it correctly to the documentation instead of:

> “The content of server_vrp.lua is now executed in the vRP context and can now use the API. The same thing should be done client-side.”

So that way people don’t get confused as I did.
Thank you, and you did an awesome job at vRP2!!

**Comment by ImagicTheCat** [comment]
Did you added your client script to the client files of your resource ?

I'm afraid I can't clarify more, the behavior is symmetric by using the `module` function which uses the FiveM API about resource's files, as you can see: https://github.com/ImagicTheCat/vRP/blob/c33ed0d0a6228e4438fa53cdf90128379844380d/vrp/client/base.lua#L11

**Comment by ImagicTheCat** [comment]
Well, maybe removing the specialized example will help. https://github.com/ImagicTheCat/vRP/commit/b1428ffbb3af0f7aa3d2533e29e6f9371581f43f

**Comment by IamN5** [comment]
So, looking at the examples, when server.lua is loaded using loadscript it appears it does not need to be included at "server_scripts", but the client script does? Anyway, adding it to the client scripts solved the problem. Example of the __resource.lua for anyone who needs it:
```
server_scripts{ 
    "@vrp/lib/utils.lua",
    "vRP.lua",
}

client_scripts {
    "@vrp/lib/utils.lua",
    "vRPcli.lua",
    "client.lua"
}`
```
But when the client loads the script, some of the client modules break ([image](https://cdn.discordapp.com/attachments/613210251075911681/657281992685256707/unknown.png)).
This is how I'm initializing the client script:
```
local Proxy = module("vrp", "lib/Proxy")
local Tunnel = module("lib/Tunnel")

local cvRP = module("vrp", "client/vRP")
vRP = cvRP()

local tpInventory = class("tpInventory", vRP.Extension)

function tpInventory:__construct()
    vRP.Extension.__construct(self);
end
```
Tried to initialize it like the server script, just declaring the extension class and constructing it, but it doesnt seem to be the right way to do it as vRP becomes undefined.
So, does it differ from the server-side logic or am I doing something stupid?
Thanks for attention.

**Comment by ImagicTheCat** [comment]
This is more about FiveM than vRP. `client_scripts` and `server_scripts` are script loaders. Files loaded in the vRP context are just file, you don't execute them in your own resource. Files are always available server-side, but client-side files should be added to `files` (for downloading).

Check the FiveM documentation.

**Comment by IamN5** [comment]
Got it, also that error was a silly mistake of mine. I forgot to register the extension. Thanks for the help @ImagicTheCat, hope to contribute to your project :)
