### ISSUE TITLE
voice chat cuts of 

### ISSUE THREAD

**Issue by xii7lm** [ImagicTheCat/vRP#581]
hello

i have this error comes to server cmd after that voice cut out from the server and no one can talk in the game or join to the server 

```
INFO: Timeout, closing. - [11] [174] abdallahalabdallah705@
INFO: Timeout, closing. - [27] [207] J.!@
INFO: Timeout, closing. - [12] [218] ZM3@
INFO: Timeout, closing. - [13] [224] N7R@
INFO: Timeout, closing. - [14] [235]  aLshammry 
```

also when i try to join again this message appears

https://cdn.discordapp.com/attachments/656781200165437470/657168098998353920/unknown.png

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/tree/master/doc#issues--features--help
