### ISSUE TITLE
Issue with database and vrp_lscustoms

### ISSUE THREAD

**Issue by fabiohuerta** [ImagicTheCat/vRP#582]
Hey, i was trying to move my fivem server to a dedicated vps, i managed to create a databse and everything went smooth-ish until i try to connect to my server , when i do, i get a identification error, and the console displays this message

 query exception vRP/lscustoms_columns : System.AggregateException: One or more errors occurred. ---> MySql.Data.MySqlClient.MySqlException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'IF NOT EXISTS veh_type varchar(255) NOT NULL DEFAU

I'm kind of new to this and im stuck here. i don't really know what to do,  thanks in advance

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/tree/master/doc#issues--features--help
