### ISSUE TITLE
DB driver "ghmattimysql" not initialized yet

### ISSUE THREAD

**Issue by MiddleSkillz** [ImagicTheCat/vRP#584]
so im trying to run vRP and im getting this when trying to start my server

**Comment by MiddleSkillz** [comment]
update i go have hmattimysql installed

**Comment by MiddleSkillz** [comment]
i do have ghmattimysql installed

**Comment by VHall1** [comment]
Remove it from any subfolders, leave ghmattimysql on your main resources folder.

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/tree/master/doc#issues--features--help
