### ISSUE TITLE
VOIP / Voice isssue - cant hear some players

### ISSUE THREAD

**Issue by ELF0001** [ImagicTheCat/vRP#591]
so when i take a admin call i cant hear hu ever it is that im tp'ing to
dont know if it is the tp that is the reason
dont see any errors in server or client console
can se the player speaking but not hear the voice ?

**Comment by ELF0001** [comment]
can see in the VOIP window that the player disconnected and is not reconnecting to the voip ?

**Comment by highrp** [comment]
try onother voip server . public server have issue mybe far for your player server and gonna packet lost

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/tree/master/doc#issues--features--help
