### ISSUE TITLE
Future plans for vRP ??

### ISSUE THREAD

**Issue by thug-thug** [ImagicTheCat/vRP#592]
Hi ImagicTheCat, how are u?
Your work is incredible, we are grateful to be public!
There is a growing and promising community today, with incredible advances that have not been made on any other platform, I call you to know the platform: AltV. (https://altv.mp/)
However, this platform is still a little lacking in good work like yours. What do you think about taking your project to the community in the future? Could this be part of your future plans? Or would you do that for a price?

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/tree/master/doc#issues--features--help

Porting vRP can be interesting in some cases, but Lua is not even supported here. Also, I get disinterested by this kind of modding projects, too much troubles in the long term.
