### ISSUE TITLE
BLOB Database

### ISSUE THREAD

**Issue by xSamiVS** [ImagicTheCat/vRP#594]
The database create a BLOB column in all the "dvalue" and isn't readable or editable.

Example table "vrp_server_data": https://i.imgur.com/LotF63W.jpg

**Comment by ImagicTheCat** [comment]
vRP 2 data functions are binary based, in this case the field contains MessagePack formatted data.

**Comment by xSamiVS** [comment]
Its possible to debinary the data functions?

**Comment by ImagicTheCat** [comment]
You want to deserialize the data; MessagePack is well specified, it has implementations in most languages.

**Comment by vrsshelby** [comment]
stupid serialization !! Low perfomance increase and make so difficult to edit the data. Amateur developers.
