### ISSUE TITLE
vrp_mysql errors

### ISSUE THREAD

**Issue by HeyyCzer** [ImagicTheCat/vRP#596]
Hello, guys :)
I'm creating a FiveM server. I downloaded vRP and followed all the steps for installation. On startup, when vRP says it is establishing connection to the DB using the vrp_mysql there is the following error:
![Screenshot_1](https://user-images.githubusercontent.com/43618377/75614029-dd62cc80-5b12-11ea-8807-fbad3e51d493.png)

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/tree/master/doc#issues--features--help
