### ISSUE TITLE
ADD-ON CARS

### ISSUE THREAD

**Issue by raedoob** [ImagicTheCat/vRP#607]
add-on cars not woking with me in VRP 2 framework tring to add add-on car and not spwan
error loading script modules/garage.lua in resoucre vrp:  @vrp/lib/utils.lua:48 error parsing module vrp/cfg/garages:[string "vrp/cfg/garage.lua"]:91: '}' expexted (to close at line 59) near '['

stack traceback:
            @vrp/lib/utils.lua:48 in function  'module'
            @vrp/modules/garage.lua:386: in local 'constructor'
            [string  "vrp/lib/Luaoop.lua"]:377: infunction <[string  "vrp/lib/Luaoop.lua"]:340>
            (...tails calls...)
            [string  "vrp/vRPShared.lua"]:77: in method 'registerExtension'
           @vrp/modules/garage.lua: in main chunk
stack traceback:
            [C]: in function  'error'
            @vrp/lib/utils.lua:48 in function  'module'
            @vrp/modules/garage.lua:386: in local 'constructor'
            [string  "vrp/lib/Luaoop.lua"]:377: infunction <[string  "vrp/lib/Luaoop.lua"]:340>
            (...tails calls...)
            [string  "vrp/vRPShared.lua"]:77: in method 'registerExtension'
           @vrp/modules/garage.lua: in main chunk
failed to load script modules/garage.lua

**Comment by raedoob** [comment]
any advice?

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/tree/master/doc#issues--features--help
(the config file has a syntax error; please don't use the github to ask help)

**Comment by raedoob** [comment]
well is this a manner ???

**Comment by raedoob** [comment]
Just stop being rude okay !!!
