### ISSUE TITLE
do not load the characters or identifications of people (vrp2.0)

### ISSUE THREAD

**Issue by Axl64** [ImagicTheCat/vRP#609]
I have a server open to 200 people and some people stay with the character "Skater" or "Hipster", the main menu does not open. and anything script that requires your ID gives error

**Comment by Axl64** [comment]
I realized that the error is due to some error. This changes the "Source" for people, causing bugs and the disconnection of its user, putting a source greater than 6000 when this happens.
https://gyazo.com/8e86ccef9a9f06a686026fa4153c34bb

**Comment by Axl64** [comment]
the problem came from the rejoin function, I had to do something that instead of rejoin would drop it and load everything again

`else -- already connected
            self:log(user.name.." ("..user.endpoint..") re-joined (user_id = "..user.id..")")
			local user2 = self.users[user_id]
			if user2 then
				self:dropPlayer(user2.source)
				DropPlayer(source, "Dropped for rejoin")
			end
           -- self.users_by_source[user.source] = nil -- remove old entry
            --user.source = source -- update source
           -- self.users_by_source[source] = user -- new entry
			

            -- reset first spawn
            --user.spawns = 0

            --self:triggerEvent("playerRejoin", user)
            deferrals.done()
          end`

**Comment by ImagicTheCat** [comment]
deprecated
