### ISSUE TITLE
Problem to add more item transformers

### ISSUE THREAD

**Issue by hadesfx8** [ImagicTheCat/vRP#61]
Hi,
I am looking for add several item transformers, but impossible to add more than one. I tried several methods in the modules/item_transformer.lua file. Is it possible to add more than one?

Thanks in advance :)

**Comment by SnaiCrys** [comment]
New item transformers need to add to vRP/vrp/cfg/item_transformers.lua

**Comment by hadesfx8** [comment]
Yes sorry I meant this file the and not the modules

**Comment by SnaiCrys** [comment]
Send your sample cfg / item_transformers.lua file to see what's wrong.

**Comment by hadesfx8** [comment]
I fix my error :) thx for all  and sorry for inconvenience
