### ISSUE TITLE
Create script problem

### ISSUE THREAD

**Issue by xXxAleXxX01** [ImagicTheCat/vRP#610]
I made a system for vrp 2. I go on the server and it works, and when I restart the game it doesn't work, but if I restart the server it works.
Client 1
https://cdn.discordapp.com/attachments/378160863724568577/702609201393827860/Screenshot_463.png
Client 2
https://cdn.discordapp.com/attachments/378160863724568577/702609232142270474/Screenshot_464.png
Server
https://cdn.discordapp.com/attachments/378160863724568577/702609253617369118/Screenshot_465.png

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/tree/master/doc#issues--features--help
