### ISSUE TITLE
Cannot use "self" when loaded in vRP context

### ISSUE THREAD

**Issue by IamN5** [ImagicTheCat/vRP#611]
For example, lets take this simple test client script (loaded correctly into vRP context by a client file):
```
local TPTest = class("TPTest", vRP.Extension)

function TPTest:__construct()
  vRP.Extension.__construct(self)

  self.open = false
  self.chestid = nil
end

function TPTest:open()
  self.open = true
end

function TPTest:toggleTest()
  if self.open then
    print("open is true")
    print("chestid: "..chestid)
  else
    print("open is false")
  end
end

vRP:registerExtension(TPTest)
```
When the TPTest's method "toggleTest" is called by another extension or vRP module, "self" is actually a nil value local variable so we can't access TPTest "open" variable.
Is this behavior intentional? Am I doing something wrong?

**Comment by ImagicTheCat** [comment]
Issues are not for help.
https://github.com/ImagicTheCat/vRP/tree/master/doc#issues--features--help

Your problem is probably related to Lua and how "OOP" works.
