### ISSUE TITLE
self.remote

### ISSUE THREAD

**Issue by JewishRapper** [ImagicTheCat/vRP#612]
For some reason if youre passing a variable from client to server and in the called func u call a client func the passing var goes as nil.

Examle:
var = 5
(clientFunc) self.remote._serverFunc(var) -> (_serverFunc(var)) self.remote._anotherClientFunc(var) ->(anotherClientFunc(var))
and on anotherClientFunc var becomes nil
am i doing something wrong?

**Comment by ImagicTheCat** [comment]
Where is the source parameter ?
