### ISSUE TITLE
Problem function vRP.users !

### ISSUE THREAD

**Issue by xXxAleXxX01** [ImagicTheCat/vRP#614]
![Screenshot_31](https://user-images.githubusercontent.com/61098010/81482594-e4a80400-9240-11ea-9522-5a871fff1784.png)
After about 60-70 players this function is buggy, this part of the code is part of a script that shows the ids above each player. After 60-70 players, the new entrants have about 3 ids superimposed over their heads.

**Comment by xXxAleXxX01** [comment]
I have on my script user.id, not user_id

**Comment by ImagicTheCat** [comment]
Hard to know if this is about vRP and not the third-party code.
