### ISSUE TITLE
Loadout system

### ISSUE THREAD

**Issue by 3rg00** [ImagicTheCat/vRP#62]
Hello ImagicTheCat, did you planned to integrate a basic loadout system, for example with the police? I'm currently work on it because set the model cop directly on cloackroom is not really good, will be better to made a flag coop take in service and add to the cloackroom a few skin customization and bulletproof gilet for example. 
What do you think about it?

**Comment by ImagicTheCat** [comment]
Loadout ? I will make a generic cloakroom, it's maybe what you need.

**Comment by 3rg00** [comment]
Yes but not with model loading, with skin parts.

**Comment by ImagicTheCat** [comment]
How that ? You just need to add a "model" property.

**Comment by 3rg00** [comment]
Precisely, i don't want to add a "model". I want that players can take Cop service, and be able to set the uniform (just the skin, not the cop model), and when they want to stop service (take a breathe), they should retrieve "civilian" clothes.
Beside, I want the player who is in service to be able to automatically have his weapons, according to his rank.

**Comment by ImagicTheCat** [comment]
Groups are here for that, I will add more callbacks, onspawn is not enough. The group selector is coming.

**Comment by ImagicTheCat** [comment]
Added the group selector, so now you have onjoin, onspawn, onleave, with that you can give weapons and uniform using the API.

**Comment by 3rg00** [comment]
So I will check it, thank a lot, you are really the best !
