### ISSUE TITLE
Missing Support for running on Linux

### ISSUE THREAD

**Issue by nloyola** [ImagicTheCat/vRP#620]
Any plans to support Linux?

ghmattimysql only works on Winblows (MS Windows).

**Comment by ImagicTheCat** [comment]
Where does this claim come from ?

**Comment by filipecamargo10** [comment]
sad but true... 

`[vRP] DB driver "ghmattimysql" not initialized yet (39 prepares cached, 5 queries cached).`
stucked here.

**Comment by nloyola** [comment]
I downloaded [GHMatti/FiveM-MySQL](https://github.com/GHMatti/FiveM-MySQL/releases) release 0.6.1. The zip file only contains DLLs and has no Linux libraries:

![Screenshot from 2020-05-31 08-01-53](https://user-images.githubusercontent.com/334607/83345569-0151cc00-a315-11ea-81c8-1f20b884f5c9.png)

**Comment by filipecamargo10** [comment]
> I downloaded [GHMatti/FiveM-MySQL](https://github.com/GHMatti/FiveM-MySQL/releases) release 0.6.1. The zip file only contains DLLs and has no Linux libraries:
> 
> ![Screenshot from 2020-05-31 08-01-53](https://user-images.githubusercontent.com/334607/83345569-0151cc00-a315-11ea-81c8-1f20b884f5c9.png)
Not working on Linux um this moment. Lets wait.

**Comment by ImagicTheCat** [comment]
Tested under GNU/Linux and working. `.dll` files are not an indicator of the lack of GNU/Linux support (ex: Mono). 

You're probably doing something wrong. It may be related to the madness of Windows not being case sensitive, luring people into naming mistakes.

**Comment by nloyola** [comment]
But... I have not renamed anything... I''m using the packages just like they were downloaded from GitHub...

Should not it all work if I've followed all the instructions?

**Comment by ImagicTheCat** [comment]
Create another issue and preferably with an error report if there is one.

**Comment by nloyola** [comment]
OK got it working! Sorry @ImagicTheCat for giving you a hard time.

**Comment by vrsshelby** [comment]
> OK got it working! Sorry @ImagicTheCat for giving you a hard time.

What you do to work ?

**Comment by nloyola** [comment]
@vrsshelby  you need the following folders in `FXServer/server-data/resources`:

* `GHMattiMySQL`
* `vrp`
* `vrp_ghmattimysql`

In your `server.cfg` you need:

```
start GHMattiMySQL
start vrp
start vrp_ghmattimysql
```

In `FXServer/server-data/resources/vrp/cfg/base.lua` you need the following:

```lua
cfg.db = {
  driver = "ghmattimysql",
  host = "127.0.0.1",
  database = "_your_db_name_",
  user = "_your_db_user_name_",
  password = "_your_db_user_password_",
}
```

I don't think `database`, `user` and `password` in this file get used. However, you do need the right settings in `GHMattiMySQL/settings.xml`:

```xml
<configuration>
  <setting key="MySQL:UseConvars">false</setting>
  <setting key="MySQL:Server">localhost</setting>
  <setting key="MySQL:Port">3306</setting>
  <setting key="MySQL:Database">_your_db_name_</setting>
  <setting key="MySQL:Username">_your_user_name_</setting>
  <setting key="MySQL:Password">_your_db_user_password_</setting>
  <setting key="MySQL:Debug">true</setting>
</configuration>
```

You have to have **MariaDB** or **MySQL** installed and the service running.

**Comment by vrsshelby** [comment]
Nothing yet :(

![error](https://user-images.githubusercontent.com/6546277/83578204-8bb05080-a50c-11ea-98ac-967dd04106a5.png)

**Comment by vrsshelby** [comment]
The problem was in my `unzip ` command which caused me to lose some files, I re-bundled the files with tar and everything worked correctly.
