### ISSUE TITLE
Error in Console !

### ISSUE THREAD

**Issue by Zuqaa** [ImagicTheCat/vRP#64]
Screen: http://prntscr.com/f73it5

name.lua is my HUD :'(

Line 13: local identity = vRP.getUserIdentity(user_id)

**Comment by Zuqaa** [comment]
He worked very well before the Update

**Comment by 3rg00** [comment]
Its your resource, no ?

**Comment by Zuqaa** [comment]
I have resolve the problem ;) I just have add the group "citizen" and it work
