### ISSUE TITLE
module\edible.lua

### ISSUE THREAD

**Issue by Boss-Man-Dev** [ImagicTheCat/vRP#640]
Audio Source error for edibles line 125.

error:
     vRP.EXT.Audio.remote._playAudioSource(-1, "sounds/drinking.ogg", 1, 0,0,0, 30, user.source)
     ![error](https://user-images.githubusercontent.com/54071671/104832362-8cf57a00-585e-11eb-8ecb-1492ee11d779.png)
fix:
    vRP.EXT.Audio.remote._playAudioSource(-1, self.cfg.liquid_sound, 1, 0,0,0, 30, user.source)
    ![fix](https://user-images.githubusercontent.com/54071671/104832392-c0380900-585e-11eb-8267-e11ea8f9d32b.png)

**Comment by ImagicTheCat** [comment]
Are you interested in making a pull request or git patch ? I can do it myself, but it can be interesting for you to learn.

**Comment by Boss-Man-Dev** [comment]
Yea i can do that. It will be either get done tonight, tm morning or the next day.

**Comment by Boss-Man-Dev** [comment]
created a pull request

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/pull/641
