### ISSUE TITLE
permission level garage

### ISSUE THREAD

**Issue by cedricalpatch** [ImagicTheCat/vRP#65]
Hello,

Can you tell me for code of garage permission if this code is good?

    ["police"] = {
    _config = {vtype="car",blipid=50,blipcolor=4,permission="police"},
    ["police"] = {"police 1",1, ""},
    ["police2"] = {"police 2",1, ""},
    ["police3"] = {"police 3",1, ""},
    ["police4"] = {"police 4",1, ""},
 },
 {"police",476.57, -1020.82, 28.03}

I havent the menu when im police group?

Thanks

**Comment by ImagicTheCat** [comment]
Permission is not the group, permissions are owned by groups. Check your groups configuration.

**Comment by cedricalpatch** [comment]
ok.... thank a lot for your quick repply ;)

**Comment by cedricalpatch** [comment]
So you speack about this?

cfg.users = {
  [1] = { -- give superadmin and admin group to the first created user on the database
    "superadmin",
    "admin"
  }

I try this but not menu spawn??

    _config = {vtype="car",blipid=50,blipcolor=4,permission=1},

**Comment by Zuqaa** [comment]
No... Exemple : In your code you have the group superadmin and admin and in this group you have, give.money, and other... 

So your permission=givemoney (exemple..)

**Comment by ImagicTheCat** [comment]
You need to learn the concept of permissions. This issue is not really related to vRP.
