### ISSUE TITLE
Problem with job selection + proposition

### ISSUE THREAD

**Issue by Zuqaa** [ImagicTheCat/vRP#66]
Hi, (juste je pourrais pas expliquer ça en EN c'est trop complexe)

En gros, imagine ya taxi dans le job selector je choisis taxi, j'ai les fonctions taxi mais si apres je choisie police, j'aurais les fonctions de police MAIS je garderais les fonctions de Taxi or je me demandais si tu pouvais modifier ça et que si tu choisis un job ca te supprime le job choisis precedemment !

Cordialement, Lorenzo

**Comment by ImagicTheCat** [comment]
Use the gtype property, it is explained in the groups config file comments.
