### ISSUE TITLE
change police skin

### ISSUE THREAD

**Issue by cedricalpatch** [ImagicTheCat/vRP#67]
You think I can change the customization uniform by skin?

**Comment by ImagicTheCat** [comment]
Check the config files.

**Comment by Drakma** [comment]
Sorry for posting to a closed issue, however I am having a tough time here.  I understand how you can change skins (I have a couple now).  However, I can't seem to find Sheriff or EMS skins.  I don't want to use a model, as people are unique.  Can you possibly point me in the right direction for where I can find those numbers used in the cloakroom.lua?

**Comment by ImagicTheCat** [comment]
Not an help section, use the FiveM forum topic. Being sorry will not help me keeping the issue section clear for everyone.
