### ISSUE TITLE
Online apartments

### ISSUE THREAD

**Issue by ARL64** [ImagicTheCat/vRP#68]
The wiki you asked me
[gtanet](https://wiki.gtanet.work/index.php?title=Online_Interiors_and_locations)

**Comment by ImagicTheCat** [comment]
Thanks, will try to add diversity to the default slots config.

**Comment by ARL64** [comment]
No problem :)

**Comment by 3rg00** [comment]
Updated IPLLOADER:
`if cfg.iplload then
  Citizen.CreateThread(function()
    LoadMpDlcMaps()
    EnableMpDlcMaps(true)
    RequestIpl("chop_props")
    RequestIpl("FIBlobby")
    RemoveIpl("FIBlobbyfake")
    RequestIpl("FBI_colPLUG")
    RequestIpl("FBI_repair")
    RequestIpl("v_tunnel_hole")
    RequestIpl("TrevorsMP")
    RequestIpl("TrevorsTrailer")
    RequestIpl("TrevorsTrailerTidy")
    RemoveIpl("farm_burnt")
    RemoveIpl("farm_burnt_lod")
    RemoveIpl("farm_burnt_props")
    RemoveIpl("farmint_cap")
    RemoveIpl("farmint_cap_lod")
    RequestIpl("farm")
    RequestIpl("farmint")
    RequestIpl("farm_lod")
    RequestIpl("farm_props")
    RequestIpl("facelobby")
    RemoveIpl("CS1_02_cf_offmission")
    RequestIpl("CS1_02_cf_onmission1")
    RequestIpl("CS1_02_cf_onmission2")
    RequestIpl("CS1_02_cf_onmission3")
    RequestIpl("CS1_02_cf_onmission4")
    RequestIpl("v_rockclub")
    RemoveIpl("hei_bi_hw1_13_door")
    RequestIpl("bkr_bi_hw1_13_int")
    RequestIpl("ufo")
    RemoveIpl("v_carshowroom")
    RemoveIpl("shutter_open")
    RemoveIpl("shutter_closed")
    RemoveIpl("shr_int")
    RemoveIpl("csr_inMission")
    RequestIpl("v_carshowroom")
    RequestIpl("shr_int")
    RequestIpl("shutter_closed")
    RequestIpl("smboat")
    RequestIpl("cargoship")
    RequestIpl("railing_start")
    RemoveIpl("sp1_10_fake_interior")
    RemoveIpl("sp1_10_fake_interior_lod")
    RequestIpl("sp1_10_real_interior")
    RequestIpl("sp1_10_real_interior_lod")
    RemoveIpl("id2_14_during_door")
    RemoveIpl("id2_14_during1")
    RemoveIpl("id2_14_during2")
    RemoveIpl("id2_14_on_fire")
    RemoveIpl("id2_14_post_no_int")
    RemoveIpl("id2_14_pre_no_int")
    RemoveIpl("id2_14_during_door")
    RequestIpl("id2_14_during1")
    RequestIpl("coronertrash")
    RequestIpl("Coroner_Int_on")
    RemoveIpl("Coroner_Int_off")
    RemoveIpl("bh1_16_refurb")
    RemoveIpl("jewel2fake")
    RemoveIpl("bh1_16_doors_shut")
    RequestIpl("refit_unload")
    RequestIpl("post_hiest_unload")
    RequestIpl("Carwash_with_spinners")
    RequestIpl("ferris_finale_Anim")
    RemoveIpl("ch1_02_closed")
    RequestIpl("ch1_02_open")
    RequestIpl("AP1_04_TriAf01")
    RequestIpl("CS2_06_TriAf02")
    RequestIpl("CS4_04_TriAf03")
    RemoveIpl("scafstartimap")
    RequestIpl("scafendimap")
    RemoveIpl("DT1_05_HC_REMOVE")
    RequestIpl("DT1_05_HC_REQ")
    RequestIpl("DT1_05_REQUEST")
    RequestIpl("FINBANK")
    RemoveIpl("DT1_03_Shutter")
    RemoveIpl("DT1_03_Gr_Closed")
    --Lom Bank
    RequestIpl("ex_sm_13_office_01a")
    RequestIpl("ex_sm_13_office_01b")
    RequestIpl("ex_sm_13_office_01c")
    RequestIpl("ex_sm_13_office_02a")
    RequestIpl("ex_sm_13_office_02b")
    RequestIpl("ex_sm_13_office_02c")
    RequestIpl("ex_sm_15_office_03a")
    RequestIpl("ex_sm_13_office_03b")
    RequestIpl("ex_sm_13_office_03c")
    --Maze Bank West
    RequestIpl("ex_sm_15_office_01a")
    RequestIpl("ex_sm_15_office_01b")
    RequestIpl("ex_sm_15_office_01c")
    RequestIpl("ex_sm_15_office_02a")
    RequestIpl("ex_sm_15_office_02b")
    RequestIpl("ex_sm_15_office_02c")
    RequestIpl("ex_sm_15_office_03a")
    RequestIpl("ex_sm_15_office_03b")
    RequestIpl("ex_sm_15_office_03c")
    --Online Apartments
    RequestIpl("apa_v_mp_h_01_a")
    RequestIpl("apa_v_mp_h_01_b")
    RequestIpl("apa_v_mp_h_01_c")
    RequestIpl("apa_v_mp_h_02_a")
    RequestIpl("apa_v_mp_h_02_b")
    RequestIpl("apa_v_mp_h_02_c")
    RequestIpl("apa_v_mp_h_03_a")
    RequestIpl("apa_v_mp_h_03_b")
    RequestIpl("apa_v_mp_h_03_c")
    RequestIpl("apa_v_mp_h_04_a")
    RequestIpl("apa_v_mp_h_04_b")
    RequestIpl("apa_v_mp_h_04_c")
    RequestIpl("apa_v_mp_h_05_a")
    RequestIpl("apa_v_mp_h_05_b")
    RequestIpl("apa_v_mp_h_05_c")
    RequestIpl("apa_v_mp_h_06_a")
    RequestIpl("apa_v_mp_h_06_b")
    RequestIpl("apa_v_mp_h_06_c")
    RequestIpl("apa_v_mp_h_07_a")
    RequestIpl("apa_v_mp_h_07_b")
    RequestIpl("apa_v_mp_h_07_c")
    RequestIpl("apa_v_mp_h_08_a")
    RequestIpl("apa_v_mp_h_08_b")
    RequestIpl("apa_v_mp_h_08_c")
    --Arcadius Business Centre
    RequestIpl("ex_dt1_01_office_01a")
    RequestIpl("ex_dt1_01_office_01b")
    RequestIpl("ex_dt1_01_office_01c") 
    RequestIpl("ex_dt1_02_office_01a")
    RequestIpl("ex_dt1_02_office_01b")
    RequestIpl("ex_dt1_02_office_01c") 
    RequestIpl("ex_dt1_03_office_01a")
    RequestIpl("ex_dt1_03_office_01b")
    RequestIpl("ex_dt1_03_office_01c") 
    --Maze Bank Building
    RequestIpl("ex_dt1_11_office_02b")
    RequestIpl("ex_dt1_11_office_02c")
    RequestIpl("ex_dt1_11_office_02a")
    RequestIpl("ex_dt1_11_office_01a")
    RequestIpl("ex_dt1_11_office_01b")
    RequestIpl("ex_dt1_11_office_01c")
    RequestIpl("ex_dt1_11_office_03a")
    RequestIpl("ex_dt1_11_office_03b")
    RequestIpl("ex_dt1_11_office_03c")
    --Clubhouse & Warehouses
    RequestIpl("bkr_biker_interior_placement_interior_0_biker_dlc_int_01_milo")
    RequestIpl("bkr_biker_interior_placement_interior_1_biker_dlc_int_02_milo")
    RequestIpl("bkr_biker_interior_placement_interior_2_biker_dlc_int_ware01_milo")
    RequestIpl("bkr_biker_interior_placement_interior_3_biker_dlc_int_ware02_milo")
    RequestIpl("bkr_biker_interior_placement_interior_4_biker_dlc_int_ware03_milo")
    RequestIpl("bkr_biker_interior_placement_interior_5_biker_dlc_int_ware04_milo")
    RequestIpl("bkr_biker_interior_placement_interior_6_biker_dlc_int_ware05_milo")
    RequestIpl("ex_exec_warehouse_placement_interior_1_int_warehouse_s_dlc_milo")
    RequestIpl("ex_exec_warehouse_placement_interior_0_int_warehouse_m_dlc_milo")
    RequestIpl("ex_exec_warehouse_placement_interior_2_int_warehouse_l_dlc_milo")
    RequestIpl("imp_impexp_interior_placement_interior_1_impexp_intwaremed_milo_")
    end)
end`
