### ISSUE TITLE
vRP.getPosition problem

### ISSUE THREAD

**Issue by Zuqaa** [ImagicTheCat/vRP#69]
I create a tow job (depanneur) and i have a error in concole..
Screen of error: http://prntscr.com/f79l5d

Line 307 : carTargetDep = GetClosestVehicle(posdepmenu['x'], posdepmenu['y'], posdepmenu['z'], 10.0,0,70)

Complete code: 

```lua
---- Reparer vehicule civil
local choice_vehcivil = {function(player,choice)
	posdepmenu = vRPclient.getPosition(player,{},function(x,y,z)
	carTargetDep = GetClosestVehicle(posdepmenu['x'], posdepmenu['y'], posdepmenu['z'], 10.0,0,70)
	if carTargetDep ~=nil then
			platecarTargetDep = GetVehicleNumberPlateText(carTargetDep)
	end
      play_dep(player)
      vRPclient.notify(player,{"Réparation en cours..."})
	  Wait(20000)
	  SetVehicleFixed(carTargetDep)
      vRPclient.notify(player,{"~h~Vous avez ~g~réparé ~w~le véhicule"})
end
end, lang.depanneur.menu.vehcivil.description()}
```

**Comment by SnaiCrys** [comment]
Use luaparse to check the code. You forgot to close the bracket.

**Comment by Zuqaa** [comment]
What is LuaParse and how have LuaParse :p And what you want say per "round bracket" o_o

**Comment by Zuqaa** [comment]
Ok so i'm very stupid round bracket is "(",")" x) thx i test this now

**Comment by Zuqaa** [comment]
Ok its good now i have a problem with the line 307 :D 

Screen: http://prntscr.com/f7a0n4

Line: 	carTargetDep = GetClosestVehicle(posdepmenu['x'], posdepmenu['y'], posdepmenu['z'], 10.0,0,70)

**Comment by Zuqaa** [comment]
Ok now i have other error with this myvehi2 = GetVehiclePedIsUsing(GetPlayerPed(player))

**Comment by ImagicTheCat** [comment]
Unrelated to vRP.

**Comment by Zuqaa** [comment]
Okey but why it doesnt work ?
