### ISSUE TITLE
Index out of range with ch_tptocoords

### ISSUE THREAD

**Issue by 3rg00** [ImagicTheCat/vRP#70]
Hello, when I try to use the admin cmd ch_tptocoords, I have an error type "Index out of range".
Ive looked and the debug show that only the first number will be inserted, after, the errors appear.
Example for (-786.8663, 315.7642, 217.6385) coords, only "-786.8663" is inserted.

**Comment by ImagicTheCat** [comment]
No parenthesis, only comma.

**Comment by 3rg00** [comment]
Yep I know, I wrote commas only for example here. I type it: -786.8663, 315.7642, 217.6385 and it doesn.t work. I made some tests, and for example if I type: 12, 12, 12 it works perfectly

**Comment by ImagicTheCat** [comment]
I think this is the same issue you had with toTable(), your mono environment seems to fail to insert elements in tables sometimes. What is your mono version ? I have no issue on windows and on linux mono 4.8.0.

**Comment by 3rg00** [comment]
Maybe, I will check it

**Comment by 3rg00** [comment]
I updated to mono 5.0, problem still the same :(

**Comment by ImagicTheCat** [comment]
I had issue with 5.0, try to downgrade to 4.8.0 If you still have the issue, install a fresh vRP and test it. If it works, something is wrong with what you did on the server (other addons, modified vRP, etc).

**Comment by 3rg00** [comment]
1. Wich version of mono 4.8.0 do you have ? x.0.520 ? x.0.483 ?
2. I always made theses tests with a fresh install of vRP, i don't modify the core also

**Comment by ImagicTheCat** [comment]
I don't know exactly, but the 4.8 should work.

**Comment by 3rg00** [comment]
I made a completely fresh install on Windows10 with only .Net 4.5, still the same problem.
Maybe I will switch on Linux, I can't reproduce this on this...

**Comment by ImagicTheCat** [comment]
You are the only one I know with this issue, that's strange. Do you still have the toTable issue ? Try to create a business and open the chamber of commerce to test it.

**Comment by 3rg00** [comment]
I made some tests agains, I downloaded the Fivem Server again, and now its works perfectly... Thanks a lot :)
