### ISSUE TITLE
Problem last connection 

### ISSUE THREAD

**Issue by Zuqaa** [ImagicTheCat/vRP#73]
Helloooo (Je préviens que je vais parler FR car je serais pas expliquer en EN...)

En gros le premier de connecté sur le serveur va voir le message derniere connexion avec les ip des autres, ex: Je suis le premier a m'être co au serveur si quelqu'un le join moi je vais voir la notif avec l'ip du mec or c'est pas a moi de le recevoir (je précise que la personne qui se co la recois aussi donc en gros tout le monde la recois...)

**Comment by ImagicTheCat** [comment]
Errors in console ?

**Comment by Zuqaa** [comment]
No

**Comment by ImagicTheCat** [comment]
Should be fixed now.

**Comment by Zuqaa** [comment]
Thx ^^
