### ISSUE TITLE
Installing and Connecting issues

### ISSUE THREAD

**Issue by Geronimin** [ImagicTheCat/vRP#75]
Hi there, thanks for all the tools you're leaving to everybody,
My friend Joce speaked about you yesterday, but he hasn't the time to explain me aas i wasn't here.

Im getting issues when i call your API, i don't know i have to call it as a ressource, i started a new server from scratch, and acutally nobody can connect to it ( it's loading and blocking @ initializing) 

Thanks again !

**Comment by Zuqaa** [comment]
It's a problem with the gamemode, u have set the gamemode on fivem and the map on fivem-map-skater ?

If yes clear the cache of your server ;)

**Comment by Zuqaa** [comment]
If you problem is resolved close the issue

**Comment by Geronimin** [comment]
where i choose the gamemode i did search in directory ? Map's on fivem-map-skater

**Comment by Zuqaa** [comment]
logicaly you have a folder "fivem" and in the ressource you have "resource_type 'gametype' { name = 'vRP -
 by Imagic' }

client_script 'fivem_client.lua'"

You have add - fivem and the - fivem-map-skater in your citymp file ???

**Comment by Zuqaa** [comment]
and your database is ok ?

**Comment by Geronimin** [comment]
yeah database has been created correctly :)

**Comment by Zuqaa** [comment]
Ok so it's your gamemode

**Comment by Zuqaa** [comment]
If you have any other gamemode installed, desinstall (ex: essentialmode..)

**Comment by Geronimin** [comment]
fivem wasn't called on my .yml file.. don't juge me i'm tired xD

**Comment by Geronimin** [comment]
yep that's what i did imma trying it, _ressource from fivem folder 
"resource_type 'gametype' { name = 'Freeroam' }"

**Comment by Geronimin** [comment]
Yes it's ok now ty very well, i have additionnal question more general about scripting and sharing my scripts, + i would like to have information with the conflict and compatibility of the scripts you can run on vrp

Thank for you're time my friend :)

**Comment by Zuqaa** [comment]
vRP is not compatible with any addon have, 'TriggerEvent', 'TriggerServerEvent, 'TriggerClientEvent' and any other command, he is not compatible with addon essentialmode

I recall that vRP is a Framework, and not a gamemode such as EssentialMode adaptable to any addon..

**Comment by Zuqaa** [comment]
If your problem is resolved please, close the issue ^^

**Comment by ImagicTheCat** [comment]
Hi, to clarify some things:
* vRP is an addon before being a framework, it's not a gamemode, so just use it as a suit of tools to build your server, with any other addons
* the only conflict to my knowledge is the very old MySql.Data.dll version used by some scripts, vRP use the recent version, the 4.5. Only one version of MySQL can be loaded at a time, so a previously loaded old mysql version will cause vRP to not work (you can try to fix this by loading vRP first in the resource list)

@Zuqaa: You are wrong, the tunnel and proxy use the TriggerEvent system, it's just a layer on top of it, so there are no problems using them or not.

**Comment by Geronimin** [comment]
Yes ill close the issues, maybe it's can be good to speak a bit guys, i know i looked like very begginer, but ill scripts things that ill share with you, wanna vocal 10-15 min (fr or eng) just to win time, and to know what is missing that ill nee to dev.

I close the ticket, bybye if u don't want, have a good day
Ty for you time ! :)

**Comment by Zuqaa** [comment]
@ImagicTheCat Sry for the error so ^^ and thx for have correcting me

**Comment by Zuqaa** [comment]
Je peux t'expliquer si tu veux, en gros tu peux développer de tous sur vRP, @ImagicTheCat a juste fais un magnifique travaille en simplifiant la connexion client/server pour faire des addons, on le dis jamais assez mais rien que d'avoir fais ça il révolutionne la façon de faire des addons sur FiveM et je pense que même si tu est débutant tu pourras comprendre comment faire des addons utilisant vRP (même si c'est complexe a comprendre)

Voila, je pense que je t'ai tout expliquer apres tu peux lire le Readme il y a toutes les infos !

Cordialement, Lorenzo

**Comment by Geronimin** [comment]
Oui j'ai deja lu j'ai bien vu toute la doc et toute les fonctions utilisable, c'est monstreux l'accessibilité que ca offre en terme de création de scripting et de personalisation de serv, je vais bosser un coup je partagerais tout ca apres :)

**Comment by Zuqaa** [comment]
No problem, good luck ;) !
