### ISSUE TITLE
Question about job

### ISSUE THREAD

**Issue by Zuqaa** [ImagicTheCat/vRP#76]
Hi, im on your server and i have see some blip for job (pêche,or...), it is coming in vRp :p ??

**Comment by ImagicTheCat** [comment]
It's built using vRP.

**Comment by Zuqaa** [comment]
That means no ?

**Comment by ImagicTheCat** [comment]
You don't understand, all the things on the test server are using vRP, it's just configuration. 
vRP is a generic tool to build a RP server, it is not a ready-made RP server.

But the test server configuration will be released when completed.

**Comment by Zuqaa** [comment]
:D YES !

THX DUDE !
