### ISSUE TITLE
Item transformer to job (recolt, treatment...)

### ISSUE THREAD

**Issue by Zuqaa** [ImagicTheCat/vRP#77]
With the item transformer its possible to make the same systeme of you ?? with the pecheur and or ?

**Comment by ImagicTheCat** [comment]
I'm a man of my word, so you will not be able to add issues anymore (cf. https://github.com/ImagicTheCat/vRP/issues/71 https://github.com/ImagicTheCat/vRP/issues/41 https://github.com/ImagicTheCat/vRP/issues/69 https://github.com/ImagicTheCat/vRP/issues/74).

Wait for the project to be released on the FiveM forum, so you will be able to ask help to other vRP users.

**Comment by 3rg00** [comment]
He doesn't have access to Fivem forums, because he was banned :).
