### ISSUE TITLE
Item transformer system

### ISSUE THREAD

**Issue by SnaiCrys** [ImagicTheCat/vRP#8]
The lack of markers and blips on the map in item transformer system. I think it is better to embed in the system itself, instead of doing separately.

**Comment by ImagicTheCat** [comment]
The configuration of an item transformer is already big, so I will think about it.

**Comment by ImagicTheCat** [comment]
So, I added an additional blips/markers config file. Since it's about static places, it is better to just add the blips/markers configured as you want in this file instead of making the item transformer less understandable.
