### ISSUE TITLE
Customization improvement

### ISSUE THREAD

**Issue by 3rg00** [ImagicTheCat/vRP#80]
Hello, do you planned to improve to skin customization with Mask and other accessories?
I Saw that the setCustomization function doesnt include the SetPedPropIndex()

**Comment by ImagicTheCat** [comment]
If you can explain to me how the function works, I will try to add something generic.

**Comment by 3rg00** [comment]
Tts exactly the same thing of SetPedComponentVariation().
For example for mask wearing: SetPedPropIndex( GetPlayerPed(-1), 0, 0, maskNumberHere, 2) -- First 0 = Head, Second = Helmet/Mask/Headphone Type, 2 = Constant

SetPedPropIndex(GetPlayerPed(-1), 1, 11, 3, 2) --> Sunglasses

**Comment by 3rg00** [comment]
You can check this: https://marekkraus.sk/gtav/skins/
for listing

**Comment by ImagicTheCat** [comment]
Mask are already available using the proper ped part, how many different props are available ?

**Comment by 3rg00** [comment]
If you look at https://wiki.gtanet.work/index.php?title=Character_Components, section "Props", you will see all that availables :)

**Comment by ImagicTheCat** [comment]
3 must be the watches ?

**Comment by 3rg00** [comment]
Index 1 for glasses, there is 25 variations after

**Comment by ImagicTheCat** [comment]
I know but there are watches in lambda menu, I think it's the index 3. 
Well, I will see what I can do.

**Comment by ImagicTheCat** [comment]
note for myself: SetPedPropIndex(int ped, int componentid, int drawableid, int textureid, bool attach)

**Comment by 3rg00** [comment]
Okay :). I think it will be awesome if we can provide differents skinshops, same as Garages (luxe, etc..)

**Comment by ImagicTheCat** [comment]
Not really possible, the basic_skinshop is generic, it is used to customize any ped, not only the mp.

**Comment by ImagicTheCat** [comment]
Done, for the record, watches were at index 6. Can't wait to wear a top hat.

**Comment by 3rg00** [comment]
Guy, you're a machine... Thanks a lot for the feature, I will do tests tomorrow :).

**Comment by ImagicTheCat** [comment]
It will not always be like that, I will slow down soon, but this feature was very cool to make.

**Comment by 3rg00** [comment]
Yep I know, you already made a very lot of stuff, you really need to take a breathe now :).
