### ISSUE TITLE
Is it possible to add for the cops ?

### ISSUE THREAD

**Issue by Armagryzor** [ImagicTheCat/vRP#82]
Hi Sir,

I hope it's not a stupid question ... Is it possible to add for cops this features 👍 

-Cloakroom
-Armory
and Fines sytem like this one ; https://github.com/indilo53/fivem-esx_policejob

Thank you..

**Comment by ImagicTheCat** [comment]
Cloakroom and armory (specific gunshop) are already available.
Will think about the fine system.

**Comment by Armagryzor** [comment]
Hi Sir,

Little idea for cops... is it possible to have on the cop menu a function like " besoin de renfort " need backup ?

**Comment by ImagicTheCat** [comment]
Why not using the phone service ?

**Comment by Armagryzor** [comment]
Why not!!

Your framework is awesome , BIG thank's .. For me it's ready to use and start to play.. Just if you can add jail system and fine for the cops ans after a medic

**Comment by ImagicTheCat** [comment]
Nice, don't hesitate to post in the connection timeout issue if you experience it.

**Comment by ImagicTheCat** [comment]
Most police functions are now done.
