### ISSUE TITLE
Change key for palyer menu ?

### ISSUE THREAD

**Issue by Geronimin** [ImagicTheCat/vRP#84]
Is it possible ? :) 

With kinds regards, Muto.

**Comment by SnaiCrys** [comment]
`if IsControlJustPressed(3,27) then vRPserver.openMainMenu({}) end`
vRP/vrp/client/gui.lua
https://wiki.fivem.net/wiki/Controls

**Comment by ImagicTheCat** [comment]
All the keys are based on the phone keys. Tell your players to change the key to open the phone, it's better to let players choose their key instead of changing it "server-side".

**Comment by Geronimin** [comment]
Yes very good idea, your framework is amazing im just discovering it and you doc is so well righted tx srsly <333

**Comment by Geronimin** [comment]
i close
