### ISSUE TITLE
Display Job improvement

### ISSUE THREAD

**Issue by 3rg00** [ImagicTheCat/vRP#85]
Hello @ImagicTheCat did you planned to display the current job of players, same of money display?
I try to understand how its possible with groups and the gtype "job" (for example).

**Comment by 3rg00** [comment]
In fact, I search in first how to display only for admin, in the list option in-game

**Comment by ImagicTheCat** [comment]
Not planned, there are no jobs system in vRP, just a way to do it by using groups. 

You can list the groups of a player, and I can add something to get each group definition (gtype and permissions).

**Comment by 3rg00** [comment]
Is it possible to display the groups of a player directly ingame?

**Comment by ImagicTheCat** [comment]
As an admin tool ? not yet.

**Comment by 3rg00** [comment]
Okay, thanks :). I will wait, it's same to be a little hard for me to dev it...
