### ISSUE TITLE
Despawn vehicule in garage central police station

### ISSUE THREAD

**Issue by Aleweadan** [ImagicTheCat/vRP#86]
Hello, I would suggest a script to allow despawn the police vehicle when entering the garage of the main police station without having to open the menu. We enter the garage with the vehicle and it disappears. However, as I am not a developer, I can not write the function properly. Here's my script beginning:

in module/police.lua

-- vehicle despawn function
Citizen.CreateThread(function()
if zone = (cfg.vehicledespawn1) or zone = (cfg.vehicledespawn2) then
		local playerPed = GetPlayerPed(-1)
		if IsPedInAnyVehicle(playerPed, 0) then
			local vehicle = GetVehiclePedIsIn(playerPed,  false)
			DeleteVehicle(vehicle)
		end
end

in cfg/police.lua

-- vehicle despwan position

cfg.vehicledespawn1 = {462.74353027344, 1014.4481811523, 28.065481185913}
cfg.vehicledespawn2 = {462.40914916992, 1019.7089233398, 28.104162216187}

**Comment by ImagicTheCat** [comment]
You can not bypass the basic garage system if you use it in the first place. But you can do it easily using the area API and the undocumented functions of **client/basic_garage.lua** using the client tunnel vRP.despawnGarageVehicle(vtype,max_range).

**Comment by Aleweadan** [comment]
I will try thanks for your reply.
