### ISSUE TITLE
Error SQL 

### ISSUE THREAD

**Issue by Tacktiik** [ImagicTheCat/vRP#87]
DoInitFile : error creating script environment for resource vrp : No conversion defined from Mysqlconnection to mysqlconnection 

(base.lua:47:1)

Possible d'avoir une BDD complète car je n'y arrive vraiment pas.

**Comment by ImagicTheCat** [comment]
MySql incompatibilies, check your other resources, or try to load vRP first in the server config.

**Comment by Tacktiik** [comment]
https://img15.hostingpics.net/pics/818493Sanstitre.png

**Comment by 3rg00** [comment]
It make a nonsense to use essentialmode with vRP...

**Comment by Tacktiik** [comment]
It's disabled now and still the error

**Comment by ImagicTheCat** [comment]
In all case, try to put vRP first to load the vRP MySql.Data.dll version.

**Comment by Tacktiik** [comment]
I can not find the .sql file

**Comment by Aleweadan** [comment]
Just config your vRP config file and sql Will be created on your DB.

**Comment by ImagicTheCat** [comment]
Solved ?
