### ISSUE TITLE
The problem of synchronization.

### ISSUE THREAD

**Issue by SnaiCrys** [ImagicTheCat/vRP#9]
Sometimes players don't see models of each other. However, they can still fight each other.
![cd4b7-clip-1125kb](https://cloud.githubusercontent.com/assets/4284827/25755392/8a78c196-31cb-11e7-9470-a927ad4d7efb.jpg)

**Comment by ImagicTheCat** [comment]
They see their own model ? If yes, I don't know what can be the issue, since it is related to the networking of FiveM/gtaV. And I think I remember having the same problem once, before even starting vRP so...

**Comment by SnaiCrys** [comment]
Yes, they see. We tried to find a correlation between our actions and a problem, but it didn't help to understand.

**Comment by xchopin** [comment]
I think it's because the server doesn't notify all the clients, I don't know how the function works but it should emit a signal for all the listeners (using the design pattern observer)

**Comment by SnaiCrys** [comment]
We tested it on a vanilla fivem and everything was fine with the synchronization of the models. Maybe this is due to the setting of the standard model for players when they are connected to vrp?

**Comment by ImagicTheCat** [comment]
Did you try to go to a skinshop while invisible to others, near them changing clothes ?

**Comment by Zuqaa** [comment]
Dude, I have the same problem but if i change my skin at skinshop i'm visible ^^ i think the problem is the skin

**Comment by SnaiCrys** [comment]
When using skinshop, player becomes visible to all.

**Comment by ImagicTheCat** [comment]
Okay, I will do an auto-set of the skin every minutes for each client to fix the issue, until I know a better way.

**Comment by ImagicTheCat** [comment]
Added now, tell me if the problem persists.

**Comment by Zuqaa** [comment]
Ok ;)

**Comment by SnaiCrys** [comment]
The problem still persists.

**Comment by ImagicTheCat** [comment]
This is strange, I will need more testing to find a fix.

**Comment by ImagicTheCat** [comment]
Does this happen only when an user didn't customize his skin, the first time, or even after customization ?
Or is it only a problem related to the default skin, set the first time ?

**Comment by Zuqaa** [comment]
Its the default skin the problem when i have customize my skin, directly the player see me

**Comment by ImagicTheCat** [comment]
Try to update the cfg/player_state.lua (only the "for" part), and delete your user data to test the default skin visibility.

**Comment by SnaiCrys** [comment]
> Does this happen only when an user didn't customize his skin, the first time, or even after customization ?
> Or is it only a problem related to the default skin ?

The problem is only if the player has not set up the skin after the first connection.

**Comment by ImagicTheCat** [comment]
Even after the last update of cfg/player_state.lua ?

**Comment by SnaiCrys** [comment]
Oh, we missed this update. Unfortunately, everyone went to bed and I can check only tomorrow.

**Comment by ImagicTheCat** [comment]
Anything new ?

**Comment by SnaiCrys** [comment]
It seems now the problem is solved.
