### ISSUE TITLE
Problem queue event vRP:tunnel_req

### ISSUE THREAD

**Issue by CrazyForge** [ImagicTheCat/vRP#90]
Hello, since the last update i have a problem with vRP, he work perfectly, but in console (F8) i have this message queue event vRP:tunnel_req and he spammed all the seconds this message :/

you have a idea ?

And he spam with this some message with file gta 5 ex: gta5/update/.....

**Comment by ImagicTheCat** [comment]
Can you take a screenshot of the original message ? Did you update your cfg files accordingly ?

**Comment by CrazyForge** [comment]
No it's good, it's not a error, it's just the update FiveM, now he show all command executed by the server..

**Comment by ImagicTheCat** [comment]
Each seconds ? Are you sure ?
