### ISSUE TITLE
Remove/add blips when group joined/leaved

### ISSUE THREAD

**Issue by 3rg00** [ImagicTheCat/vRP#91]
Hello @ImagicTheCat, I have a problem with the "onjoin/onleave" function, the onjoin works perfectly but when user leave a group, blips are still displayed.

I use this code:
`  ["Mineur"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player)
          vRPclient.setNamedBlip(player,{"Gisement d'or",12,12,12,85,60,"Gisement d'or moyen"}) 
          vRPclient.setNamedBlip(player,{"Gisement d'or 2",12,12,12,85,60,"Gisement d'or riche"})
      end
      ,onleave = function(player) 
        vRPclient.RemoveNamedBlip(player,{"Gisement d'or"}) 
        vRPclient.RemoveNamedBlip(player,{"Gisement d'or 2"}) 
      end
    },
    "mineur.functions",
    "mineur.garage"
  },`

Do you have any example that works correctly?

**Comment by ImagicTheCat** [comment]
When you use tunnels, be careful because you will not have any error message (since it will need to check if the function exists client-side, a loss of bandwidth). You put a capital letter out from nowhere.

**Comment by 3rg00** [comment]
Huh ? where I put a capital letter ?

**Comment by ImagicTheCat** [comment]
**R**emoveNamedBlip

**Comment by 3rg00** [comment]
Omg...
Thanks
