### ISSUE TITLE
vRPserver using ?

### ISSUE THREAD

**Issue by 3rg00** [ImagicTheCat/vRP#93]
Just a noob question again, how is it possible to use the giveMoney function in clientside ?
I tried to use this: vRPserver.giveMoney(,{playervar, 3500}) but it doesn't work, I think Im wrong with the parameters...

**Comment by ImagicTheCat** [comment]
You can't, the server proxy API is not the same as the server tunnel API.
If it was, any player will be able to increase his money.

**Comment by 3rg00** [comment]
So its the same for items adding ?

**Comment by ImagicTheCat** [comment]
There are 3 categories of API, proxy, server tunnel and client tunnel. Proxy is used server-side, client tunnel is used server-side and server tunnel is used client-side.
