### ISSUE TITLE
Business model item transformation ?

### ISSUE THREAD

**Issue by psykozdu29** [ImagicTheCat/vRP#95]
**Hello I would like to know if someone could share a complete job already done to take as model**

 _(Bonjour je voudrais savoir si quelqu'un pourrait partager un métier complet déjà fait pour le prendre comme model)_

**Comment by 3rg00** [comment]
http://93.115.96.185/fivem/servers/FR_cfg.zip

**Comment by psykozdu29** [comment]
**thank you very much
I have trouble understanding everything ^^**

_(Merci beaucoup
J'ai du mal à tout comprendre ^^)_
