### ISSUE TITLE
Idea for job mission !

### ISSUE THREAD

**Issue by CrazyForge** [ImagicTheCat/vRP#97]
helo i have a idea for you, you could do a job mission ressembling to Trucker Job on FiveM ?

**Comment by CruelAlpha** [comment]
There is a trucker job out there in the forums, you need to integrate it with fivem money

**Comment by jakepavek** [comment]
Please don't tell him what he NEEDS to do. He did this all for us be
greatful.

**Comment by CruelAlpha** [comment]
@jakepavek im not telling what @ImagicTheCat the cat has to do im talking about what @CrazyForge  has to do.
What are you on about???

**Comment by jakepavek** [comment]
Oh sorry lol I was responding via email didn't see

**Comment by ImagicTheCat** [comment]
Done, now people need to build some interesting missions using the vRP.addStaticMenuChoices or other.
