### ISSUE TITLE
Question Time : onJoin = DrawMarker groups

### ISSUE THREAD

**Issue by CrazyForge** [ImagicTheCat/vRP#98]
It is possible to make a onjoin = job.onjoin and make a marker to a position

**Comment by 3rg00** [comment]
Read documentation you have your answer inside.

**Comment by CrazyForge** [comment]
-_- not a marker the circle, the marker on the map.. the point

**Comment by 3rg00** [comment]
The blip, yes it's possible, look th documentation.

**Comment by CrazyForge** [comment]
![small_gtav_tow](https://cloud.githubusercontent.com/assets/28700039/26192135/d05e0eca-3bb0-11e7-8c90-d95a1cd018a6.jpg)

**Comment by CrazyForge** [comment]
Ahh xD it's good i have find this : vRP.setGPS(x,y)
